import type {
  ArchitectureDef,
  AxisDef,
  Blueprint,
  PlaybookSection,
  PrincipleDef,
  ResolvedArchitecture,
  RuleSetting,
  Tier,
} from '../config';
import {
  readSetting,
  resolveArchitecture,
} from '../config';
import { renderResolvedTestFilesOperational } from './test-files';
import {
  renderModuleGrowthAuthority,
  renderModuleGrowthProtocol,
  renderModuleRunwayFact,
} from './module-growth';
import { formatOwns } from '../markdown';

export interface AgentGateFact {
  id: string;
  setting: RuleSetting;
  holder: 'inspect' | 'lint';
}

export interface CompactContractFacts {
  gates: AgentGateFact[];
  handbook: string;
  lintIntegration?: 'verified' | 'unverified' | 'reference-only';
}

function rulesOfTier(rules: Record<string, RuleSetting> | undefined, tier: Tier) {
  return Object.entries(rules ?? {}).filter(([, setting]) => readSetting(setting).tier === tier);
}

function claudePrinciples(principles: PrincipleDef[] | undefined): PrincipleDef[] {
  if (!principles) {
    return [];
  }

  return principles.filter((principle) => principle.land === 'claude');
}

function gateLabel({ id, setting }: AgentGateFact): string {
  const value = readSetting(setting).value;

  return `\`${id}\`${value === undefined ? '' : ` = ${value}`}`;
}

function inspectDiagnosisClause(gates: string): string {
  return `${gates} is diagnosed only when \`npx blueprint inspect --baseline\` runs; `
    + 'the baseline grandfathers recorded findings, so this is not continuous '
    + 'edit-time prevention and a green lint says nothing about it';
}

export function renderHeader(): string {
  return [
    '## Architecture contract (generated from blueprint)',
    '',
    '> Generated by `@kekkai/blueprint` — edit the blueprint, not this block.',
    '> Your own notes belong OUTSIDE the markers; init rewrites only between them.',
    '> The strictness is the product — it keeps AI development inside the declared',
    '> architecture. Never soften or bypass; disagreements go to the maintainer.',
  ].join('\n');
}

const CONTRACT_DOC = 'node_modules/@kekkai/blueprint/agent-contract.md';

export function renderCompactContract(
  blueprint: Blueprint,
  facts: CompactContractFacts,
): string {
  const { architecture } = blueprint;
  const resolved = resolveArchitecture(architecture);
  const chain = resolved.layers.map((layer) => `\`${layer.name}\``).join(' → ');
  const { gates, handbook, lintIntegration = 'unverified' } = facts;

  const topology = resolved.topology === 'module-first'
    ? 'Module → Layer → Unit'
    : 'Layer → Unit';

  const lintGates = gates.filter(({ holder }) => holder === 'lint').map(gateLabel);
  const inspectGates = gates.filter(({ holder }) => holder === 'inspect').map(gateLabel);

  const extras = [
    ...(blueprint.componentShape?.length ? ['component-shape axes'] : []),
    ...(claudePrinciples(blueprint.principles).length ? ['behavioral principles'] : []),
    ...(blueprint.playbook?.length ? ['the working playbook'] : []),
  ];

  return [
    renderHeader(),
    '',
    `- Framework: \`${blueprint.framework}\`. Canonical source-root alias: \`${architecture.alias}\`.`,
    ...moduleFlowLine(resolved),
    `- Layer flow: ${chain} — transitive: a layer may import **any** layer after it, unless the target narrows its importers.`,
    `- **Before adding, moving, or renaming any file** — placement, ${resolved.topology === 'module-first' ? 'module boundaries, ' : ''}unit shapes, ownership, naming${extras.length ? `, ${extras.join(', ')}` : ''}: read [${handbook}](${handbook}) (generated from the same blueprint — always current).`,
    '- **Operating discipline** — how to follow the flow, react to lint failures, '
    + `and the pre-commit checklist: read [${CONTRACT_DOC}](${CONTRACT_DOC}) `
    + '(ships inside the package — present once dependencies are installed, '
    + 'always matching the installed version). Upgrade Blueprint only with '
    + '`npx @kekkai/blueprint@latest upgrade` and remove it only with `npx blueprint remove` '
    + 'before uninstalling the package; `--dry-run` previews either.',

    `- Hard gates (${lintIntegrationClause(lintIntegration)}): one-way imports, unit entries, ownership, relative escapes${lintGates.length ? `, ${lintGates.join(', ')}` : ''}${inspectGates.length ? `; ${inspectDiagnosisClause(inspectGates.join(', '))}` : ''}. When a gate fails, fix the structure — never \`eslint-disable\`, never relocate the violation to a sibling.`,

    `- You are the gate for: no undeclared architectural folders under \`${architecture.alias}/\` (\`blueprint inspect --baseline\` verifies — red only on what you introduced). Move code into the declared ${topology} topology. ${growthAuthority(resolved, handbook)}`,
  ].join('\n');
}

function growthAuthority(resolved: ResolvedArchitecture, handbook: string): string {
  return resolved.topology === 'module-first'
    ? renderModuleGrowthAuthority(handbook)
    : 'If the architecture has genuinely outgrown this config, that is the owner\'s decision — '
      + 'say so and stop; never expand it yourself.';
}

function lintIntegrationClause(
  status: 'verified' | 'unverified' | 'reference-only',
): string {
  const scope = 'on files the architecture globs match; '
    + 'an empty declared position is runway, not protection';

  if (status === 'verified') {
    return `verified alive in the project's lint run ${scope}`;
  }

  if (status === 'reference-only') {
    return `emitted only as a reference and not enforced by the project's lint run yet ${scope}`;
  }

  return `emitted, but effective project-lint wiring is unverified until \`blueprint doctor\` proves it ${scope}`;
}

function moduleFlowLine(resolved: ResolvedArchitecture): string[] {
  return resolved.topology === 'module-first'
    ? [
        ...(resolved.moduleRunway ? [`- Module runway: ${renderModuleRunwayFact()}`] : []),
        '- Module flow: each module may import itself and modules transitively reachable through '
        + '`dependsOn`; declaration order grants no permission. The layer flow must also pass, and '
        + 'cross-module imports use the canonical source-root alias.',
      ]
    : [];
}

export function renderContext(blueprint: Blueprint): string {
  const { framework, architecture } = blueprint;
  const resolved = resolveArchitecture(architecture);
  const chain = resolved.layers.map((layer) => `\`${layer.name}\``).join(' → ');

  return [
    '### Context',
    '',
    `- Framework: \`${framework}\`. Canonical source-root alias: \`${architecture.alias}\`.`,
    ...(resolved.modules.length
      ? [`- Modules: ${resolved.modules.map((module) => {
          const dependencies = module.dependsOn.length
            ? module.dependsOn.map((dependency) => `\`${dependency}\``).join(', ')
            : 'none';

          return `\`${module.name}\` (depends on ${dependencies})`;
        }).join('; ')}`]
      : []),
    ...(resolved.moduleRunway ? [`- Module runway: ${renderModuleRunwayFact()}`] : []),
    `- Layer flow: ${chain}`,
  ].join('\n');
}

export function renderPlacement(architecture: ArchitectureDef): string {
  const resolved = resolveArchitecture(architecture);

  const moduleLines = resolved.modules.map((module) => {
    const dependencies = module.dependsOn.length
      ? module.dependsOn.map((dependency) => `\`${dependency}\``).join(', ')
      : 'none';

    return `- \`${module.root}/\` — ${module.name === 'app'
      ? 'reserved router-composition module; all nested source uses the container position.'
      : `module: ${module.definition.does}.`} `
      + `DIRECT DEPENDENCIES: ${dependencies}.`;
  });

  const runwayRoot = resolved.sourceRoot === '.' ? '<module>' : `${resolved.sourceRoot}/<module>`;

  const positions = resolved.moduleRunway
    ? resolved.layers.map((layer) => ({ layer, root: `${runwayRoot}/${layer.name}` }))
    : resolved.layerPositions;

  const lines = positions.map((position) => {
    const { definition: layer, allowedImporters } = position.layer;
    const parts = [`- \`${position.root}/\` — layer: ${layer.does}.`];

    if (layer.mustNot?.length) {
      parts.push(` MUST NOT: ${layer.mustNot.join('; ')}.`);
    }

    const owns = formatOwns(layer.owns);

    if (owns) {
      parts.push(` OWNS: ${owns}.`);
    }

    if (layer.allowedImporters) {
      const importers = allowedImporters
        .map((importer) => (importer.selfOnly ? `${importer.layer} (selfOnly)` : importer.layer))
        .join(', ');

      parts.push(` IMPORTABLE BY: ${importers}.`);
    }

    return parts.join('');
  });

  const unitLines = resolved.layers.map((layer) => layer.unit.layout === 'folder'
    ? `- \`${layer.name}\` units: one folder per unit; only \`${layer.unit.entry}\` is importable from outside.`
    : `- \`${layer.name}\` units: one file per unit.`);

  const testPolicy = resolveArchitecture(architecture).testFiles;

  const exemptLine = testPolicy.architectureExemptions.length
    ? [`- ${renderResolvedTestFilesOperational('agent-placement', 'en', testPolicy)}`]
    : [];

  const runwayLines = resolved.moduleRunway
    ? [`- \`${runwayRoot}/\` — no domain module is declared yet. Each module declared through `
      + 'the module growth protocol below repeats these inner layers, and its root files take the '
      + 'container position.']
    : [];

  return [
    '### Where code goes',
    '',
    ...moduleLines,
    ...runwayLines,
    ...lines,
    ...unitLines,
    ...exemptLine,
  ].join('\n');
}

export function renderModuleGrowth(architecture: ArchitectureDef): string {
  const resolved = resolveArchitecture(architecture);

  return resolved.topology === 'module-first'
    ? renderModuleGrowthProtocol({ runway: resolved.moduleRunway }, '###')
    : '';
}

export function renderNaming(naming: Record<string, string> | undefined): string {
  const entries = Object.entries(naming ?? {});

  if (!entries.length) {
    return '';
  }

  return [
    '### Naming',
    '',
    ...entries.map(([concept, convention]) => `- \`${concept}\`: ${convention}`),
  ].join('\n');
}

export function renderHardRules(
  blueprint: Blueprint,
  gates: AgentGateFact[],
  lintIntegration: 'verified' | 'unverified' | 'reference-only' = 'unverified',
): string {
  const { architecture } = blueprint;

  const bullets = [
    '- Cross-layer imports go only downstream; local same-layer imports never use the alias.',
    `- Every cross-layer or cross-module import uses the canonical source-root alias `
    + `\`${architecture.alias}\`; additional aliases are for resolution, not alternate boundary `
    + 'spellings.',
    '- Statically resolvable dynamic imports follow the same alias, flow, and unit-entry rules. '
    + 'A runtime-dependent target is unverified, never a proven legal dependency.',
  ];

  const folderEntries = [
    ...new Set(
      resolveArchitecture(architecture).layers
        .map((layer) => layer.unit)
        .filter((shape) => shape.layout === 'folder')
        .map((shape) => `\`${shape.entry}\``),
    ),
  ];

  if (folderEntries.length) {
    bullets.push(`- Import a folder unit via its ${folderEntries.join(' / ')}, never its internals.`);
  }

  bullets.push(
    '- Restricted packages / globals live only in their owning layer (see "Where code goes").',
    '- Relative imports stay inside their layer. Folder units reach siblings only through '
    + 'their entries; no redundant segments (`./../`, `././`).',
  );

  for (const fact of gates) {
    const held = fact.holder;
    const gate = gateLabel(fact);

    if (held === 'lint') {
      bullets.push(`- ${gate} is ${lintIntegration === 'verified'
        ? 'verified alive in the project lint run'
        : lintIntegration === 'reference-only'
          ? 'present only in the reference config and is not a project-lint gate yet'
          : 'emitted but not yet verified alive in the project lint run'}.`);
    }

    if (held === 'inspect') {
      bullets.push(`- ${inspectDiagnosisClause(gate)}.`);
    }
  }

  bullets.push(
    '- When lint fails, fix the structure — move the code or extract a lower layer. '
    + 'Never silence it with `eslint-disable`, and never relocate the violation to a sibling.',
  );

  return ['### Machine checks', '', ...bullets].join('\n');
}

export function renderComponentShape(axes: AxisDef[] | undefined): string {
  if (!axes?.length) {
    return '';
  }

  const bullets = axes.map((axis) => {
    const triage = axis.triage
      ? ` (triage: \`${axis.triage}\` is an entry point, never the verdict)`
      : '';

    return `- **${axis.name}** — ${axis.say} ${axis.why}${triage}`;
  });

  return [
    '### Component shape (orthogonal axes — judge each independently)',
    '',
    'A set, not a pipeline: never infer one axis holds because another does.',
    '',
    ...bullets,
  ].join('\n');
}

export function renderBehavioral(
  architecture: ArchitectureDef,
  principles: PrincipleDef[] | undefined,
  rules: Record<string, RuleSetting> | undefined,
): string {
  const topology = resolveArchitecture(architecture).topology === 'module-first'
    ? 'Module → Layer → Unit'
    : 'Layer → Unit';

  const growth = resolveArchitecture(architecture).topology === 'module-first'
    ? 'Grow modules only through the module growth protocol above; outgrowing the inner layers '
    + 'or rules is the owner\'s call to make — report it, do not edit the architecture to fit '
    + 'what you just wrote.'
    : 'Outgrowing the config is the owner\'s call to make — report it, do not edit the '
      + 'architecture to fit what you just wrote.';

  const bullets = [
    `- Do not create undeclared architectural folders under \`${architecture.alias}/\`. Follow the declared ${topology} topology. (lint can't see every folder — inspect will.) ${growth}`,
    ...claudePrinciples(principles).map(
      (principle) => `- **${principle.say}** — ${principle.why}`,
    ),
  ];

  if (rules?.deadCode !== undefined && readSetting(rules.deadCode).tier === 'error') {
    bullets.push(
      '- **Dead code is error-tier, but no lint rule can gate it** — '
      + '`npx knip` is the gate (in init\'s install set); '
      + 'wire it into whatever verification you run.',
    );
  }

  if (rulesOfTier(rules, 'warn').length) {
    bullets.push(
      '- Treat a `warn`-tier lint result as a review entry point — look there, don\'t ignore it.',
    );
  }

  return [
    '### Behavioral rules (no tool enforces these — you are the gate)',
    '',
    ...bullets,
  ].join('\n');
}

export function renderPlaybook(playbook: PlaybookSection[] | undefined): string {
  if (!playbook?.length) {
    return '';
  }

  const blocks = playbook.map((section) =>
    [
      `#### ${section.title}`,
      '',
      ...section.rules.map(
        (rule) => `- **${rule.say}**${rule.why ? ` ${rule.why}` : ''}`,
      ),
    ].join('\n'));

  return [
    '### Working playbook (judgment rules — you are the gate)',
    '',
    ...blocks.join('\n\n').split('\n'),
  ].join('\n');
}

export function renderLifecycle(heading: '##' | '###'): string {
  return [
    `${heading} Upgrading or removing Blueprint`,
    '',
    '- **"Upgrade Blueprint to the latest version"** — run '
    + '`npx @kekkai/blueprint@latest upgrade --dry-run`, then '
    + '`npx @kekkai/blueprint@latest upgrade`. '
    + 'The running release is the only target. When it writes `blueprint-upgrade.md`, do exactly '
    + 'those operations, record each with `npx blueprint upgrade --complete <operation-id>`, and '
    + 're-run `npx blueprint upgrade` until it reports the upgrade complete. A bare `npm update` '
    + 'skips migrations and verification; never apply release notes or a hand-made migration.',
    '- **"Remove Blueprint from this project"** — run `npx blueprint remove --dry-run`, resolve '
    + 'every conflict it lists, then run `npx blueprint remove`. It reverses only what it can '
    + 'prove Blueprint owns and uninstalls `@kekkai/blueprint` last; never uninstall the package '
    + 'first or delete shared files by hand, and review everything it reports as kept.',
  ].join('\n');
}

export function renderChecklist(blueprint: Blueprint): string {
  const { architecture, principles } = blueprint;
  const resolved = resolveArchitecture(architecture);

  const items = [
    `- [ ] Imports follow the one-way flow and use \`${architecture.alias}\` across layer or module `
    + 'boundaries (no upstream layers, alternate aliases, or local same-layer aliases).',
    '- [ ] Statically resolvable dynamic imports pass the same boundary checks; runtime-dependent '
    + 'targets are treated as unverified.',
    `- [ ] New code sits in the declared ${resolved.topology === 'module-first'
      ? 'module and layer'
      : 'layer'}; folder units expose only their declared entry.`,
  ];

  if (architecture.naming && Object.keys(architecture.naming).length) {
    items.push('- [ ] Names follow the conventions above.');
  }

  items.push(`- [ ] No new undeclared folders under \`${architecture.alias}/\`.`);

  if (blueprint.componentShape?.length) {
    items.push('- [ ] Changed units hold against every component-shape axis, judged one by one.');
  }

  if (claudePrinciples(principles).length) {
    items.push('- [ ] The behavioral principles above are upheld.');
  }

  return ['### Before you commit', '', ...items].join('\n');
}
