import { operationalText } from './operational-contract';

export const UPGRADE_HELP = operationalText([
  'blueprint upgrade — move this repository to the running Blueprint release.',
  '',
  'Run it through the release you want: `npx @kekkai/blueprint@latest upgrade`, or a',
  'pinned `npx @kekkai/blueprint@<version> upgrade`. The running package is the only',
  'target authority; there is no --to flag, and upgrade never downgrades. A bare',
  '`npm update` only moves the dependency: it skips migrations, the Agent playbook,',
  'reconciliation, and verification, so it is not a Blueprint upgrade.',
  '',
  'One repository-wide lifecycle, recorded in .blueprint-lifecycle.json:',
  '  · plans first: reads the lifecycle checkpoint, or proves it from the installed',
  '    package on a repository adopted before lifecycle state existed; resolves the',
  '    upgrade operations of every release in (source, target], removes canceled and',
  '    superseded ones, and orders the rest before anything runs',
  '  · records the pending upgrade, moves @kekkai/blueprint to the target through the',
  '    detected package manager, and continues with that installed copy',
  '  · runs deterministic migrations in code by reconciling every adopted application',
  '    through `blueprint init`',
  '  · writes one resolved playbook, blueprint-upgrade.md, when semantic work remains',
  '    for the coding Agent; each operation is recorded with --complete',
  '  · runs `blueprint inspect --baseline` and `blueprint doctor` in every adopted',
  '    application and records the new lifecycle only when all of them pass',
  '',
  'Supported sources start at 3.2.0. Starting an upgrade requires a clean Git worktree;',
  'a pending upgrade resumes with `npx blueprint upgrade` and never repeats completed work.',
  '',
  'Flags:',
  '  --dry-run                  Print the source, target, applications, install',
  '                             command, migrations, and resolved semantic plan.',
  '                             Changes nothing.',
  '  --complete <operation-id>  Record one semantic operation as done once its',
  '                             verification passes. Not combinable with --dry-run.',
  '',
  'Examples:',
  '  npx @kekkai/blueprint@latest upgrade --dry-run   # see the complete plan',
  '  npx @kekkai/blueprint@latest upgrade             # upgrade to the latest release',
  '  npx blueprint upgrade --complete review-retired-module-private',
  '  npx blueprint upgrade                            # resume, verify, and finish',
]);

export const REMOVE_HELP = operationalText([
  'blueprint remove — de-adopt Blueprint without guessing what it owns.',
  '',
  'Run it before uninstalling the package. It plans the complete cleanup first and',
  'classifies every action by the evidence that Blueprint owns it:',
  '  · Blueprint files (config, lifecycle state, baseline, backups, unfinished',
  '    authoring, transformation, or upgrade artifacts, *.blueprint.* references)',
  '    are deleted',
  '  · generated outputs are deleted while they still carry Blueprint\'s marker',
  '  · shared Agent documents lose only the BLUEPRINT:START/END section',
  '  · .gitignore, package script, tsconfig/jsconfig paths, and Vite alias edits are',
  '    reversed only when .blueprint-lifecycle.json records the exact edit and the',
  '    file still contains it; alias wiring that source still imports is kept',
  '  · @kekkai/blueprint is uninstalled last, with recorded ESLint packages nothing',
  '    else still uses',
  '',
  'A diverged or repeated recorded edit, broken markers, or a remaining file that',
  'still imports @kekkai/blueprint, runs the Blueprint CLI, or loads a deleted',
  'blueprint.config.mjs stops the whole removal before any change. Run from one',
  'application of a multi-app repository to de-adopt only it; a package its adopted',
  'siblings still use stays installed. Repositories adopted before lifecycle records',
  'lose only provable artifacts and get a report of what could not be proven.',
  '',
  'Flags:',
  '  --dry-run   Print the complete plan, what stays for you to review, and the',
  '              uninstall command. Changes nothing.',
  '',
  'Examples:',
  '  npx blueprint remove --dry-run   # see what would be removed and what blocks it',
  '  npx blueprint remove             # remove Blueprint, then the package last',
]);
