import type {
  FindingFact,
  LayerToModuleEvidenceFact,
  ProjectTransformationFact,
  TransformationPreflightFact,
} from './transformation';

export interface TransformationBriefFacts {
  evidence: LayerToModuleEvidenceFact;
  preflight: TransformationPreflightFact;
  findings: FindingFact[];
  state: ProjectTransformationFact;
  install: string;
  cleanup: string;
  repositoryApplication?: string;
  repositoryApplicationCount?: number;
}

export function layerToModuleBrief(facts: TransformationBriefFacts): string {
  return [
    renderHeader(facts),
    renderSnapshot(facts),
    renderPhaseOne(facts.install),
    renderCandidates(facts.evidence),
    renderOwnershipBoundary(),
    renderMovement(facts.state),
    renderCutover(),
    renderBaseline(facts.findings),
    renderVerification(facts.cleanup),
  ].join('\n');
}

function renderHeader(facts: TransformationBriefFacts): string {
  const repositoryScope = facts.repositoryApplicationCount
    ? [
        `This section is the work unit for \`${facts.repositoryApplication}\` inside one `
        + `${facts.repositoryApplicationCount}-application repository transformation.`,
        'Do not report transformation success until every application section has reached the',
        'same target topology and passed the repository-wide verification at the top of this file.',
      ]
    : [
        'Transform this one selected application from layer-first to module-first without turning',
        'Blueprint into a domain classifier or codemod. Preserve the starting commit, use '
        + '`git mv` for',
        'tracked files, rewrite imports deliberately, and cut source + config + emitted rules '
        + 'over as',
        'one reviewable working-tree change.',
      ];

  return [
    '# Blueprint layer-first → module-first transformation playbook',
    '',
    '> Generated by `blueprint init --topology module-first` after the topology decision and',
    '> transformation preflight passed. Execute it end to end; the measured evidence is neutral,',
    '> while domain ownership remains your semantic decision.',
    '> `blueprint-transformation.json` is the machine-consumed obligation. Do not delete it.',
    `> After verification, init retires it and ${facts.cleanup}`,
    '',
    '## Goal and boundary',
    '',
    ...repositoryScope,
    '',
    'The CLI has supplied candidates, closures, graph limits, and pre-transform debt below.',
    'You decide module names, ownership, merge/split, neutral extraction, cycles, and collisions.',
  ].join('\n');
}

function renderSnapshot(facts: TransformationBriefFacts): string {
  const { evidence, preflight, state } = facts;

  return [
    '',
    '## Measured transformation snapshot',
    '',
    '- Current topology: `layer-first`',
    '- Target topology: `module-first`',
    `- Framework/router: \`${state.framework ?? 'unknown'}\`${state.hasNext ? ` / Next.js ${state.nextRouter ?? 'unresolved'} Router` : ''}`,
    `- Selected source root/application scope: \`${facts.repositoryApplication ?? evidence.sourceRoot}\``,
    `- Recoverable starting commit: \`${preflight.head.commit}\``,
    `- Git worktree at preflight: clean (${preflight.worktree.changes?.length ?? 0} changes)`,
    `- Import-resolution basis: \`${evidence.resolutionBasis}\``,
    `- Canonical source wiring: ${entries(evidence.aliases)}`,
    `- Source-root bootstrap/wiring: ${list(evidence.rootWiring)}`,
    `- Import-analysis limits: ${evidence.unknownDynamicImports} runtime-dependent dynamic import(s), ${evidence.parseFailures.length} parse failure(s)`,
    '',
    'Do not move source-root bootstrap/provider wiring merely to make it fit a module. It remains',
    'at the source root unless the framework requires a different physical location.',
  ].join('\n');
}

function renderPhaseOne(install: string): string {
  return [
    '',
    '## Phase 1 — prove the 4.0 layer-first state before movement',
    '',
    '1. Keep the starting commit, current config, and current baseline recoverable in Git.',
    '2. Verify the installed package is the build that generated this playbook. If it is missing:',
    '',
    '```bash',
    install,
    '```',
    '',
    '3. The accepted preflight already captured the layer-first origin. While this module-first',
    '   transformation is pending, do not request the opposite topology or re-run adoption.',
    '   Run only `npx blueprint inspect --json` and `npx blueprint deps --json` to read evidence.',
    '4. Save their output outside tracked application files as the pre-transform evidence.',
    '   Existing findings are migration input, not a reason to stop. Invalid config, unresolved',
    '   scope, failed analysis, or contradictory identities are reasons to stop before movement.',
    '5. Do not update or rewrite the baseline in this phase. Its old identities are evidence.',
  ].join('\n');
}

function renderCandidates(evidence: LayerToModuleEvidenceFact): string {
  const noDomainCandidates = evidence.routerCandidates.length
    ? [
        'No container or page-fallback domain candidate was measured. Continue from the route',
        'composition closures below; route segment names are evidence, never automatic modules.',
        '',
      ]
    : [
        'No container, page, or App Router seed was measured. Stop and define why the repository',
        'is still provably layer-first before inventing domain candidates.',
        '',
      ];

  return [
    '',
    '## Neutral candidate and graph evidence',
    '',
    `Primary seed source: \`${evidence.seedSource}\`. Containers win when present; pages are the fallback.`,
    `Current layer units: ${evidence.sourceLayers.map((entry) => `${entry.layer}=[${entry.units.join(', ')}]`).join('; ') || '(none)'}`,
    `Canonical governed unit edges (same identities as inspect/deps): ${edgeList(evidence.edges)}`,
    `Overlaps: ${evidence.overlaps.map((entry) => `${entry.unit} ← ${entry.seeds.join(', ')}`).join('; ') || '(none)'}`,
    `Orphans: ${list(evidence.orphans)}`,
    `Cycles: ${evidence.cycles.map((cycle) => cycle.join(' → ')).join('; ') || '(none)'}`,
    `Case-insensitive collision risks: ${evidence.collisionRisks.map((entry) => `${entry.identity} ← ${entry.units.join(', ')}`).join('; ') || '(none measured before destinations exist)'}`,
    `Unresolved alias-like imports: ${evidence.unresolvedAliasLikeImports.map((entry) => `${entry.unit}: ${entry.specifier}`).join('; ') || '(none)'}`,
    `Relative import structural evidence: ${relativeImports(evidence)}`,
    'Relative evidence uses the canonical architecture resolver and reports whether its governed',
    'target unit was measured. It does not verify exact files, extensions, index resolution, or',
    'runtime-dependent specifiers; do not call an unmeasured target a proven missing file.',
    ...evidence.parseFailures.map((failure) => `Parse failure: ${failure.path} — ${failure.message}`),
    '',
    '### Domain candidate closures',
    '',
    ...(evidence.candidates.length
      ? evidence.candidates.flatMap(renderCandidate)
      : noDomainCandidates),
    '### Router composition closures',
    '',
    ...(evidence.routerCandidates.length
      ? evidence.routerCandidates.flatMap(renderCandidate)
      : ['(none)', '']),
    'A closure is evidence, not ownership. Fan-in greater than one is not proof of neutrality,',
    'and a seed name is not a promised module name.',
  ].join('\n');
}

function renderCandidate(candidate: LayerToModuleEvidenceFact['candidates'][number]): string[] {
  return [
    `#### ${candidate.seed} (${candidate.source} seed)`,
    '',
    `- Recorded source members: ${list(candidate.memberPaths)}`,
    `- Reachable units: ${list(candidate.reachableUnits)}`,
    `- Direct seed imports: ${edgeList(candidate.directImports)}`,
    `- Edges inside closure: ${edgeList(candidate.closureEdges)}`,
    `- Consumers entering closure: ${edgeList(candidate.closureConsumers)}`,
    `- Unresolved alias-like evidence: ${list(candidate.unresolvedAliasLikeImports)}`,
    '',
  ];
}

function relativeImports(evidence: LayerToModuleEvidenceFact): string {
  return evidence.relativeImports.map((entry) => [
    `${entry.importer}: ${entry.specifier}`,
    `→ ${entry.structuralTarget ?? '(outside governed structure)'}`,
    `(${entry.targetUnitMeasured ? 'target unit measured' : 'target unit not measured'})`,
  ].join(' ')).join('; ') || '(none)';
}

function renderOwnershipBoundary(): string {
  return [
    '',
    '## Agent decisions only you may make',
    '',
    '1. Read route descriptions, product language, ownership docs, and the code behind each seed.',
    '2. Choose final domain boundaries and names. Merge related seeds; split broad seeds when the',
    '   business responsibilities differ. Record the evidence for each decision in the handoff.',
    '3. A unit reached only by one confirmed domain closure moves into that module.',
    '4. A unit reached by several modules but with a clear domain owner stays with that owner;',
    '   consumers depend on it. Do not call fan-in "shared".',
    '5. Extract only truly neutral code with no domain owner, and name the module precisely',
    '   (`platform`, `infrastructure`, or `ui` when that is what it is). Never create an empty or',
    '   catch-all `shared` module.',
    '6. Resolve overlaps, cycles, orphans, and destination collisions explicitly. If ownership',
    '   remains ambiguous, stop with that exact decision instead of applying a score or threshold.',
  ].join('\n');
}

function renderMovement(state: ProjectTransformationFact): string {
  const router = !state.hasNext
    ? [
        'For React/Vue, move route composition from the layer-first pages/router surface into the',
        'reserved module-first `app` composition surface. Distinguish routes and providers from',
        'ordinary domain units; a nested route-related file is not automatically an inner layer.',
      ]
    : [
        'This is a Next.js App Router application. Preserve the framework-owned physical `app/**`',
        'tree. Configure it as reserved module `app` at the container position; route segments are',
        'not inner layers and `app` does not repeat the ordinary modules’ technical-layer shape.',
      ];

  return [
    '',
    '## Filesystem movement and import rewrite',
    '',
    '1. Write down the approved source → destination table before moving anything. Recheck it for',
    '   exact and case-insensitive collisions. Do not let one move overwrite another.',
    '2. Use `git mv` for every tracked move. Move owned components, hooks, contexts, services, and',
    '   other units below their final modules while retaining meaningful inner technical layers.',
    '   Containers are module seeds, not repeated inner technical layers. Move their screen or',
    '   composition entry files to the owning module root, alongside its technical-layer folders.',
    '   For example: containers/Loadout/LoadoutScreen.tsx → loadout/LoadoutScreen.tsx,',
    '   never loadout/containers/Loadout/LoadoutScreen.tsx. Resolve collisions before moving.',
    '3. Rewrite literal module paths in imports, exports, dynamic imports, unshadowed',
    '   CommonJS require calls, and TypeScript import-equals to the canonical source-root alias.',
    '   If a move needs dynamic binding or other source-body changes, stop: this verifier cannot',
    '   prove that refactor. Preserve the origin and resolve it before claiming completion.',
    '   Runtime-dependent dynamic imports remain explicitly unverified.',
    '4. Remove obsolete empty layer-first directories only after every contained file is accounted',
    '   for. Do not introduce an AST printer, formatter migration, or repository-wide codemod.',
    ...router,
  ].join('\n');
}

function renderCutover(): string {
  return [
    '',
    '## Config, module DAG, and cutover',
    '',
    '1. After ownership and destination decisions are complete, derive direct module edges from',
    '   the resulting imports: `A imports B` means A declares `dependsOn: [B]`.',
    '2. Do not derive final `dependsOn` from the old graph. You may move ownership, extract a',
    '   specifically named neutral module, or break a cycle; you may not leave a real edge',
    '   undeclared. Transitive reachability follows from the direct DAG.',
    '3. Prepare the final config with modules, repeated inner layers, canonical aliases, router',
    '   `app` when present, final `dependsOn`, and all still-relevant style/project contracts.',
    '   Remove the old pages and containers layer declarations after assigning their recorded',
    '   roles to reserved app and domain modules. Review allowedImporters and other layer-name',
    '   references; remove obsolete references and express cross-module edges with dependsOn.',
    '   Do not preserve an obsolete layer declaration just to make a misplaced folder pass lint.',
    '4. Do not put the module-first config live while source still occupies the layer-first tree.',
    '   Apply source moves, import rewrites, config, emitted ESLint, and generated guidance as one',
    '   reviewable cutover, then validate them together.',
  ].join('\n');
}

function renderBaseline(findings: FindingFact[]): string {
  return [
    '',
    '## Baseline review — never rewrite paths mechanically',
    '',
    `Pre-transform inspection recorded ${findings.length} finding(s):`,
    ...(findings.length
      ? findings.map((finding) => `- ${finding.rule} · ${finding.path} · ${finding.subject || '(no subject)'}`)
      : ['- (none)']),
    '',
    'After cutover, run plain `npx blueprint inspect --json` before touching the baseline.',
    'Classify every result as pre-existing debt under a new identity, understood migration',
    'residue, or a new transformation regression. Resolve every architecture error, including',
    'pre-existing errors: retirement does not apply baseline suppressions. Only then run',
    '`npx blueprint inspect --update-baseline`, followed by `npx blueprint inspect --baseline`.',
    'The handoff must state the classification result; "findings existed" is not enough.',
  ].join('\n');
}

function renderVerification(cleanup: string): string {
  return [
    '',
    '## Verification and handoff',
    '',
    'Run and inspect:',
    '',
    'Before running the commands, fill `target.decisions` in `blueprint-transformation.json`.',
    'Give every recorded source unit one decision with `destinations` '
    + 'and `members: [{ source, destination }]`.',
    'Map each origin member exactly once; keep its source extension and use unique destinations.',
    'Preserve member contents except import/export module paths and CRLF normalization; '
    + 'perform other refactors after verified retirement.',
    'Git retains the application-scoped origin independently of this file; deleting it blocks '
    + 'init rather than cancelling the obligation.',
    'Final architecture errors must be resolved without adding baseline suppressions.',
    'Do not edit the recorded origin facts and do not delete the obligation or this playbook;',
    '`init --topology module-first` verifies and retires them only after the final state agrees.',
    '',
    '```bash',
    'git status --short',
    'git diff --stat',
    'git diff --summary',
    'npx blueprint inspect --json',
    'npx blueprint deps --json',
    'npx blueprint inspect --baseline',
    'npx blueprint init --topology module-first --no-install',
    'npx blueprint doctor --json',
    '# then the adopter repository\'s lint, typecheck, test, and build commands',
    '```',
    '',
    'Add one legal cross-module import as a positive control and one forbidden reverse import as',
    'a temporary negative control. The negative probe must fail through emitted ESLint/inspect;',
    'remove it and re-run. Confirm static and supported dynamic imports resolve after movement.',
    '',
    `The successful init retires ${cleanup} before the final doctor run. Report the before/after tree, Git rename/diff`,
    'evidence, ownership decisions, final module DAG, collision/cycle/orphan resolution, baseline',
    'classification, inspect/deps/ESLint agreement, adopter gates, and any remaining unverified',
    'runtime-dependent imports. Git rename percentages are supporting evidence, not the verdict.',
  ].join('\n');
}

function list(values: string[]): string {
  return values.length ? values.map((value) => `\`${value}\``).join(', ') : '(none)';
}

function entries(values: Record<string, string>): string {
  const mapped = Object.entries(values).map(([alias, target]) => `${alias} → ${target}`);

  return mapped.length ? mapped.join(', ') : '(none detected)';
}

function edgeList(edges: { from: string; to: string; count: number }[]): string {
  return edges.length
    ? edges.map((edge) => `${edge.from} → ${edge.to} (${edge.count})`).join(', ')
    : '(none)';
}
