import { operationalText } from './operational-contract';
import type { OperationalText } from './operational-contract';
import { renderUpgradeVerification } from './upgrade-instructions';
import type { UpgradeVerificationRuleFact } from './upgrade-instructions';

export interface UpgradePlaybookOperationFact {
  id: string;
  introducedIn: string;
  applications: string[];
  evidence: Record<string, string[]>;
  supersedes: { id: string; completed: boolean }[];
  completed: boolean;
  instruction: OperationalText;
  verification: UpgradeVerificationRuleFact;
}

export interface UpgradePlaybookFact {
  source: string;
  target: string;
  migrations: string[];
  operations: UpgradePlaybookOperationFact[];
}

function applicationLine(operation: UpgradePlaybookOperationFact): string {
  return `Applications: ${operation.applications.map((key) => {
    const evidence = operation.evidence[key];

    return evidence?.length ? `\`${key}\` (measured: ${evidence.join(', ')})` : `\`${key}\``;
  }).join(', ')}`;
}

function supersessionLines(operation: UpgradePlaybookOperationFact): string[] {
  return operation.supersedes.map((entry) => entry.completed
    ? `Replaces \`${entry.id}\`, which already ran in this repository: converge from its result `
    + 'instead of undoing it blindly.'
    : `Replaces \`${entry.id}\`, which never ran here: do not perform it.`);
}

function operationSection(operation: UpgradePlaybookOperationFact, index: number): string[] {
  const status = operation.completed ? 'done — do not repeat' : 'pending';

  return [
    `### ${index + 1}. \`${operation.id}\` — introduced in ${operation.introducedIn} — ${status}`,
    '',
    applicationLine(operation),
    '',
    ...supersessionLines(operation).flatMap((line) => [line, '']),
    operation.instruction,
    '',
    `${renderUpgradeVerification(operation.verification)} Record it with `
    + `\`npx blueprint upgrade --complete ${operation.id}\`.`,
    '',
  ];
}

export function renderUpgradePlaybook(fact: UpgradePlaybookFact): OperationalText {
  const migrations = fact.migrations.length
    ? fact.migrations.map((id) => `\`${id}\``).join(', ')
    : 'none beyond regenerated outputs';

  return operationalText([
    '# Blueprint upgrade playbook',
    '',
    `> Generated by \`blueprint upgrade\` for ${fact.source} → ${fact.target}. Temporary: `
    + '`blueprint upgrade` deletes it when the upgrade completes. Never edit '
    + '`.blueprint-lifecycle.json` by hand.',
    '',
    '## Already done in code',
    '',
    `- The project dependency is @kekkai/blueprint ${fact.target}.`,
    `- Deterministic migrations: ${migrations}. \`blueprint init\` regenerated Blueprint outputs.`,
    '',
    '## Semantic operations, in order',
    '',
    `This is the complete effective plan for every release in (${fact.source}, ${fact.target}]. `
    + 'Canceled and superseded instructions are already removed. Do only what is listed; never '
    + 'apply release notes or CHANGELOG entries directly, and never repeat an operation marked '
    + 'done.',
    '',
    ...fact.operations.flatMap(operationSection),
    '## Finish',
    '',
    '1. Run `npx blueprint upgrade`. It re-runs `blueprint init`, then `blueprint inspect '
    + '--baseline` and `blueprint doctor` in every adopted application, and records the new '
    + 'lifecycle only when all of them pass.',
    '2. If verification fails, fix regressions and record only understood pre-existing debt. Never '
    + 'lower a rule, threshold, or boundary to reach green; report a blocker to the owner instead.',
    '3. Run the project\'s own lint, typecheck, test, and build commands.',
    '',
  ]);
}
