import fs from 'node:fs';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

import type { Blueprint } from '../config';
// Test-only import of the full emit module — src keeps the patterns-leaf
// boundary; the fixture needs emitLint's real selectors, not a paraphrase.
import { reactPreset } from '../presets';
import {
  cli,
  configSource,
  flattenProse,
  makeRepo,
  react,
  reactBlueprint,
  read,
  rm,
  write,
} from './conformance';
import type { CliResult, RepoSpec } from './conformance';

/**
 * The adoption conformance suite, grouped by scenario — every scenario
 * below was once a live complaint from an agent adopting the tool on a
 * real repo (the batch numbers point into the feedback ledger). Field runs
 * should only ever find NEW scenarios.
 */

const dirs: string[] = [];

const repo = (spec: RepoSpec = {}): string => {
  const dir = makeRepo(spec);

  dirs.push(dir);

  return dir;
};

afterEach(() => {
  while (dirs.length) {
    rm(dirs.pop() as string);
  }
});

describe('flattenProse · the helper the prose assertions rest on', () => {
  // Every wrap-insensitive assertion in this file is only as good as this collapse,
  // and nothing asserted the collapse itself. A markdown wrap is a newline plus the
  // next line's indentation — a RUN of whitespace — so replacing each character
  // individually instead of each run leaves the needle unmatched by a different
  // amount of space. On a positive assertion that is a false red; on a negative one
  // it passes on nothing, which is the failure this helper exists to prevent.
  it('collapses a run of whitespace to one space, not one space per character', () => {
    expect(flattenProse('init created\n   only to hold this command'))
      .toBe('init created only to hold this command');

    expect(flattenProse('two\t\t tabs and spaces')).toBe('two tabs and spaces');
  });

  // The documented asymmetries, because they are what makes it safe to use on a
  // needle written as one line: a paragraph break is still a match, and nothing
  // about punctuation, wording or order is relaxed.
  it('matches across a paragraph break, and relaxes nothing else', () => {
    expect(flattenProse('one sentence.\n\nAnother one.')).toBe('one sentence. Another one.');

    expect(flattenProse('Order, punctuation: kept — verbatim.'))
      .toBe('Order, punctuation: kept — verbatim.');
  });

  // Leading and trailing whitespace becomes a single space rather than disappearing,
  // which is why the needles in this file are written without either.
  it('leaves one space where it trimmed, so needles carry no edges', () => {
    expect(flattenProse('\n  padded  \n')).toBe(' padded ');
  });
});

describe('fail-loud floor', () => {
  it('a command that needs a config says so on stderr and exits 1', async () => {
    const impact = await cli(repo(), ['impact']);

    expect(impact.code).toBe(1);
    expect(impact.output).toContain('author the config first');
  });

  it('rejects the manufactured-net workaround: a layer literally named * (batch 9)', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource({
          ...reactBlueprint,
          architecture: {
            ...reactBlueprint.architecture,
            layers: [{ name: '*', does: 'root files smuggled into the net' }],
          },
        }),
      },
    });

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(1);
    expect(doctor.output).toContain('glob or path characters');
    expect(doctor.output).toContain('Root files are wiring, not a layer');
  });
});

describe('greenfield scaffold — init alone completes (batches 1 & 4)', () => {
  it('init → inspect green → doctor passes all 7 checks', async () => {
    const dir = repo({ packageJson: react() });

    const init = await cli(dir, ['init', '--no-install']);

    expect(init.code).toBe(0);
    expect(read(dir, 'blueprint.config.mjs')).toContain('reactPreset');
    expect(read(dir, 'eslint.config.mjs')).toContain('Generated by @kekkai/blueprint');
    // No tsconfig existed — init creates jsconfig so the alias resolves (B1's gap).
    expect(read(dir, 'jsconfig.json')).toContain('"~app/*"');
    expect(read(dir, 'docs/architecture-handbook.md')).toContain('# ');

    // The scaffolded config imports the package; offline fixtures have no
    // node_modules (--no-install), so swap in the equivalent preset as data.
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    const inspect = await cli(dir, ['inspect']);

    expect(inspect.code).toBe(0);
    expect(inspect.output).toContain('Coverage:');

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(0);
    // A `--no-install` fixture has no resolvable eslint, so the survival check cannot
    // run — and the banner no longer counts that skip as a pass (field run #129).
    expect(doctor.output).toContain('⊘ Adoption unverified — 6 of 7 checks passed');
    expect(doctor.output).not.toContain('all 7 checks passed');
  });
});

describe('"complete" says what it leaves out (field runs #71–#73)', () => {
  it('names the uncommitted working tree under the banner', async () => {
    // Three agents independently closed on the same gap, in their own words: "what I
    // reported as complete is complete minus commit". The playbook says a ratchet in
    // an uncommitted tree is not installed; doctor is the last thing on screen and
    // said only "Adoption complete", so the two truths never met where a reader is.
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--no-install']);
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(0);
    expect(doctor.output).toContain('6 of 7 checks passed');
    expect(doctor.output).toContain('nothing adoption wrote is committed');
    expect(doctor.output).toContain('not installed');
    // The remedy, and whose call it is — a note that only states the problem sends an
    // adopting agent to `git init`, which the playbook forbids it from doing.
    expect(doctor.output).toContain('Initialise version control and commit');
    expect(doctor.output).toContain('owner\'s call');
  });

  it('drops the note once the repo is version-controlled', async () => {
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--no-install']);
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));
    fs.mkdirSync(path.join(dir, '.git'));

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(0);

    // The banner is the LAST line, not merely followed by no VCS wording: the note
    // rides in a `? [x] : []` spread, and an empty arm is only pinned by a seam that
    // would notice anything appearing in it.
    expect(doctor.output.trimEnd().endsWith('proves what those checks cover.')).toBe(true);
  });

  it('carries the same note on the JSON channel', async () => {
    // Two channels reporting the same run must not know different things.
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--no-install']);
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    const doctor = await cli(dir, ['doctor', '--json']);
    const parsed = JSON.parse(doctor.output) as { ok: boolean; note?: string };

    expect(parsed.ok).toBe(true);
    expect(parsed.note).toContain('not installed');
  });
});

describe('a step that creates files owns them (field runs #71–#73)', () => {
  it('the playbook says deleting its build artifacts is safe, and whose call it is', async () => {
    // All three field runs flagged the same discomfort: the playbook asks for a build
    // to prove the alias resolves, and `dist/` + `*.tsbuildinfo` then sit untracked in
    // someone's tree. "Leave them to the repo's ignore rules" reads as "you may not
    // touch these" without the sentence that says removal is safe.
    // Forced onto a starter, which is the only path that asks for a build — and the
    // path all three field agents were on.
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--authoring', '--no-install']);

    const playbook = read(dir, 'blueprint-authoring.md') ?? '';

    expect(playbook).toContain('a step THIS playbook asked for');
    expect(playbook).toContain('deleting them is safe');
    expect(playbook).toContain('the build can be re-run');
    expect(playbook).toContain('the owner\'s call');
  });
});

describe('init UX honesty — re-runs and starters tell the truth (batch 10)', () => {
  it('a forced playbook on a starter leads with the early-exit verdict', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    const init = await cli(dir, ['init', '--authoring', '--no-install']);

    expect(init.code).toBe(0);

    const playbook = read(dir, 'blueprint-authoring.md') ?? '';

    // The conclusion an agent needs sits at the top, not mid-ceremony.
    expect(playbook.indexOf('Read this first')).toBeGreaterThan(-1);
    expect(playbook.indexOf('Read this first')).toBeLessThan(playbook.indexOf('## Method'));
    expect(playbook).toContain('npx blueprint init --preset');
  });

  it('second init over a wired vite starter emits no alias instructs', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        // Template-style JSONC — the comment survives init's surgery, so the
        // second run cannot JSON.parse the file it wired itself.
        'tsconfig.json': '{\n  // template comment\n  "compilerOptions": {\n    "strict": '
          + 'true,\n  },\n}\n',
        'vite.config.ts': 'import { defineConfig } from \'vite\'\n\nexport default '
          + 'defineConfig({\n  plugins: [],\n})\n',
      },
    });

    const first = await cli(dir, ['init', '--no-install']);

    expect(first.code).toBe(0);
    expect(read(dir, 'tsconfig.json')).toContain('"~app/*"');
    expect(read(dir, 'vite.config.ts')).toContain('\'~app\'');
    // The both-contracts note names the flag that avoids the second round
    // trip — the field agent never discovered --agent existed.
    expect(first.output).toContain('--agent claude|codex');

    // The scaffolded config imports the package; offline fixtures swap it for data.
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    const second = await cli(dir, ['init', '--no-install']);

    expect(second.code).toBe(0);
    // The field complaint: init #2 printed "Add the import alias to
    // tsconfig…" over a file init #1 had already wired — a false todo that
    // reads as a regression. Both alias instructs must stay silent now.
    expect(second.output).not.toContain('Add the import alias');
    expect(second.output).not.toContain('resolve.alias');
  });
});

describe('--agent persists into the scaffold — no chicken-and-egg (field issue #5)', () => {
  it('first init with --agent claude emits one contract and declares it in the '
    + 'config', async () => {
    const dir = repo({ packageJson: react() });

    const init = await cli(dir, ['init', '--agent', 'claude', '--no-install']);

    expect(init.code).toBe(0);
    expect(read(dir, 'blueprint.config.mjs')).toContain('emit: { agents: [\'claude\'] }');
    expect(read(dir, 'CLAUDE.md')).toContain('<!-- BLUEPRINT:START -->');
    expect(read(dir, 'AGENTS.md')).toBeNull();
    expect(init.output).not.toContain('Wrote both');
  });
});

describe('stale contracts cannot hide behind green (field issues #2–#3)', () => {
  it('doctor flags a hand-touched contract outside emit.agents', async () => {
    // Init only instructs when the stale file carries hand-written content —
    // without this check the orphan lived on with every gate green.
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource({
          ...reactBlueprint,
          emit: { agents: ['claude'] },
        }),
        'CLAUDE.md': '<!-- BLUEPRINT:START -->\ncontract\n<!-- BLUEPRINT:END -->\n',
        'AGENTS.md': '# our own notes\n\n<!-- BLUEPRINT:START -->\nold\n<!-- BLUEPRINT:END -->\n',
      },
    });

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(1);
    expect(doctor.output).toContain('✗ no leftover reference, authoring, or stale contract files');
    expect(doctor.output).toContain('AGENTS.md');
    expect(doctor.output).toContain('needs its block removed by hand');
  });
});

describe('scaffold matches the doctrine — no invented structure (batch 11)', () => {
  it('scaffolds guidance dirs only into an empty tree', async () => {
    const rooted = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    const init = await cli(rooted, ['init', '--no-install']);

    expect(init.code).toBe(0);
    // Code already lives here — an unbuilt layer's absence is its true
    // state; a .gitkeep shell would contradict "never invent a layer".
    expect(read(rooted, 'src/components/.gitkeep')).toBeNull();
    expect(read(rooted, 'src/pages/.gitkeep')).toBeNull();

    const empty = repo({ packageJson: react() });

    await cli(empty, ['init', '--no-install']);

    // A truly empty tree still gets the guidance scaffold.
    expect(read(empty, 'src/components/.gitkeep')).toBe('');
  });

  it('re-init removes the stale generated contract when emit.agents narrows', async () => {
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--no-install']);

    expect(read(dir, 'AGENTS.md')).toContain('<!-- BLUEPRINT:START -->');

    // The field workflow was config-edit → re-init → *manual rm* — the last
    // step is init's job when the file is wholly its own output.
    write(dir, 'blueprint.config.mjs', configSource({
      ...reactPreset({ name: 'fixture' }),
      emit: { agents: ['claude'] },
    }));

    const second = await cli(dir, ['init', '--no-install']);

    expect(second.code).toBe(0);
    expect(second.output).toContain('stale agent contract');
    expect(read(dir, 'AGENTS.md')).toBeNull();
    expect(read(dir, 'CLAUDE.md')).toContain('<!-- BLUEPRINT:START -->');
  });
});

describe('init output reads correctly when skimmed (field issues #34, #36)', () => {
  it('a deletion does not wear the writes\' ✓', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    // A plain init leaves a pristine preset scaffold; --authoring reclaims it
    // so the playbook can author the real one.
    expect((await cli(dir, ['init', '--no-install'])).code).toBe(0);

    const authoring = await cli(dir, ['init', '--authoring', '--no-install']);

    expect(authoring.code).toBe(0);
    // The field agent filtered init's output for `write` and missed its own
    // config being reclaimed, then spent commands hunting the disappearance.
    // The cause was always in the note; the mark is what makes the line stop
    // a skimming reader.
    expect(authoring.output).toContain('− rm: blueprint.config.mjs (pristine preset scaffold');
    expect(authoring.output).not.toContain('✓ rm:');
    expect(authoring.output).toContain('✓ write: blueprint-authoring.md');
  });

  it('the install line does not stutter its own kind', async () => {
    const dir = repo({ packageJson: react() });

    const plan = await cli(dir, ['init', '--dry-run']);

    expect(plan.code).toBe(0);
    expect(plan.output).toContain('would install: eslint,');
    expect(plan.output).not.toContain('install: install');
  });
});

describe('the fixture DSL itself', () => {
  it('puts console back after a run', () => {
    // `cli()` swaps console.log/error to capture output and restores them in a
    // finally. Skip the restore and every later console call in the process
    // appends to an array nobody reads: the next scenario's `output` comes back
    // empty and its assertions pass against nothing. A whole batch of green with
    // no evidence behind it, which is worse than a red.
    const log = console.log;
    const error = console.error;

    return cli(repo(), ['--version']).then((result) => {
      expect(result.code).toBe(0);
      expect(console.log).toBe(log);
      expect(console.error).toBe(error);
    });
  });

  it('names the manifest it writes when the spec does not', () => {
    // detect reads `pkg.name` into `projectName`, which titles the handbook and
    // is quoted into the generated config. A nameless default would run every
    // scenario that does not care about the name against a manifest npm rejects.
    expect(JSON.parse(read(repo(), 'package.json') ?? 'null')).toEqual({ name: 'fixture' });

    // And a spec that DOES name it wins — the default is a fallback, not a floor.
    expect(JSON.parse(read(repo({ packageJson: react() }), 'package.json') ?? 'null'))
      .toMatchObject({ name: 'fixture', dependencies: { react: '^18.0.0' } });
  });

  it('removes a path that is already gone without throwing', () => {
    // Scenarios delete artifacts mid-test (the authoring cleanup, for one) and
    // the afterEach sweeps the same paths again. Without `force`, that second
    // removal throws ENOENT out of teardown and takes the rest of the queue's
    // cleanup with it — leaving temp dirs behind on every later failure.
    const dir = makeRepo();

    rm(dir);
    expect(() => rm(dir)).not.toThrow();
    expect(read(dir, 'package.json')).toBeNull();
  });
});

/**
 * `emit.handbook` and `emit.agents[].path` are adopter-supplied strings that
 * reached `fs.writeFileSync` unchecked: `../CLAUDE.md` wrote one directory up, an
 * absolute path wrote wherever it pointed, and both runs printed ✓ beside the
 * escaping path. `SECURITY.md` puts "anything outside the project root" in scope,
 * so the tool was contradicting its own stated boundary — and because blueprint's
 * pitch is that an *agent* authors the config, the realistic input is a relative
 * path off by one directory rather than a hostile one. Refused in the planner, so
 * the refusal is atomic and `--dry-run` cannot print a plan the run would reject.
 */
describe('init writes only inside the repo it runs in', () => {
  const escaping = (emit: Blueprint['emit']): Blueprint => ({
    ...reactPreset({ name: 'fixture' }),
    emit,
  });

  /**
   * The project root is a subdirectory of the fixture, so a path that leaves the root
   * still lands inside what this test owns and removes. Pointing an escape at the
   * system temp directory is an assertion about shared global state, and it poisoned
   * itself once: a mutation run executed a mutant with the guard removed, the write
   * landed there for real, and every later run then saw the file it asserts is absent.
   */
  const nested = (): { dir: string; outside: string } => {
    const fixture = repo({ packageJson: react() });
    const dir = path.join(fixture, 'project');

    write(dir, 'package.json', JSON.stringify(react()));

    return { dir, outside: fixture };
  };

  /** Everything the refusal has to say, in the one channel the agent is guaranteed. */
  const assertRefused = (init: CliResult, dir: string, offending: string): void => {
    const output = flattenProse(init.output);

    expect(init.code).toBe(1);
    expect(output).toContain(offending);
    expect(output).toContain('outside the project root');
    expect(output).toContain('nothing was written');
    expect(output).toContain('emit.handbook');
    expect(output).toContain('emit.agents[].path');

    // Atomic: the eslint config sits below the handbook in plan order, so a guard
    // that fired per action would have written it before reaching the bad one.
    expect(read(dir, 'eslint.config.mjs')).toBeNull();
    expect(read(dir, 'docs/architecture-handbook.md')).toBeNull();
    expect(fs.existsSync(path.resolve(dir, offending))).toBe(false);
  };

  it('refuses an emit.handbook above the root and leaves the tree untouched', async () => {
    const { dir } = nested();

    write(
      dir,
      'blueprint.config.mjs',
      configSource(escaping({ handbook: '../escaped-handbook.md' })),
    );

    assertRefused(await cli(dir, ['init', '--no-install']), dir, '../escaped-handbook.md');
  });

  it('refuses an absolute emit.agents path, however ordinary the directory', async () => {
    // Absolute, and pointing at the fixture that contains the project — containment
    // is judged against the project root, not against how exotic the path looks.
    const { dir, outside } = nested();
    const target = path.join(outside, 'escaped-contract.md');

    write(
      dir,
      'blueprint.config.mjs',
      configSource(escaping({ agents: [{ target: 'claude', path: target }] })),
    );

    assertRefused(await cli(dir, ['init', '--no-install']), dir, target);
  });
});

/**
 * The ratchet's identity used to include the finding's message. This repo rewords
 * findings as it learns to explain them better — two of the commits before this one
 * did nothing else — and each such release silently retired every baseline entry for
 * the rules it touched: the recorded text stopped matching, the same old debt came
 * back as `fresh`, the recorded entry counted as `stale`, and a brownfield CI went
 * red on an upgrade that changed no code. Identity is now the rule, the path and a
 * subject, none of which a rewording touches. A baseline recorded under the old key
 * is refused rather than reinterpreted: read under the new one it would suppress
 * nothing, which is the wall of red the ledger exists to prevent, arriving with no
 * stated cause.
 */
