import { afterEach, describe, expect, it } from 'vitest';

import type { Blueprint } from '../config';
import { reactPreset } from '../presets';
import { cli, configSource, makeRepo, read, rm, wiredEslintConfig, write } from './conformance';
import type { RepoSpec } from './conformance';

/**
 * The adoption conformance suite, grouped by scenario — every scenario
 * below was once a live complaint from an agent adopting the tool on a
 * real repo (the batch numbers point into the feedback ledger). Field runs
 * should only ever find NEW scenarios.
 */

const dirs: string[] = [];

const repo = (spec: RepoSpec = {}): string => {
  const dir = makeRepo(spec);

  dirs.push(dir);

  return dir;
};

afterEach(() => {
  while (dirs.length) rm(dirs.pop() as string);
});

const react = (deps: Record<string, string> = {}) => ({
  name: 'fixture',
  dependencies: { react: '^18.0.0', ...deps },
});

const reactBlueprint: Blueprint = {
  framework: 'react',
  architecture: {
    alias: '~app',
    layers: [
      { name: 'components', does: 'render UI' },
      { name: 'services', does: 'data access' },
    ],
    module: { layout: 'flat', entry: 'index', private: [] },
  },
  rules: { unusedVars: 'error' },
};

describe('fail-loud floor', () => {
  it('a command that needs a config says so on stderr and exits 1', async () => {
    const impact = await cli(repo(), ['impact']);

    expect(impact.code).toBe(1);
    expect(impact.output).toContain('author the config first');
  });

  it('rejects the manufactured-net workaround: a layer literally named * (batch 9)', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource({
          ...reactBlueprint,
          architecture: {
            ...reactBlueprint.architecture,
            layers: [{ name: '*', does: 'root files smuggled into the net' }],
          },
        }),
      },
    });

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(1);
    expect(doctor.output).toContain('glob or path characters');
    expect(doctor.output).toContain('Root files are wiring, not a layer');
  });
});

describe('greenfield scaffold — init alone completes (batches 1 & 4)', () => {
  it('init → inspect green → doctor passes all 7 checks', async () => {
    const dir = repo({ packageJson: react() });

    const init = await cli(dir, ['init', '--no-install']);

    expect(init.code).toBe(0);
    expect(read(dir, 'blueprint.config.mjs')).toContain('reactPreset');
    expect(read(dir, 'eslint.config.mjs')).toContain('Generated by @kekkai/blueprint');
    // No tsconfig existed — init creates jsconfig so the alias resolves (B1's gap).
    expect(read(dir, 'jsconfig.json')).toContain('"~app/*"');
    expect(read(dir, 'docs/architecture-handbook.md')).toContain('# ');

    // The scaffolded config imports the package; offline fixtures have no
    // node_modules (--no-install), so swap in the equivalent preset as data.
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    const inspect = await cli(dir, ['inspect']);

    expect(inspect.code).toBe(0);
    expect(inspect.output).toContain('Coverage:');

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(0);
    expect(doctor.output).toContain('Adoption complete — all 7 checks passed');
  });
});

describe('brownfield playbook — semantics stated, nothing reverse-engineered (batches 1–3)', () => {
  it('init writes the playbook with the rules an agent used to dig from dist', async () => {
    const files = Object.fromEntries([
      ...Array.from({ length: 8 }, (_, i) => [
        `src/components/C${i}.jsx`,
        `export const c${i} = ${i};`,
      ]),
      ...Array.from({ length: 4 }, (_, i) => [
        `src/services/s${i}.js`,
        `import { c${i} } from '../components/C${i}';\nexport const s${i} = c${i};`,
      ]),
    ]);

    const dir = repo({ packageJson: react(), files });
    const init = await cli(dir, ['init', '--no-install']);

    expect(init.code).toBe(0);

    const playbook = read(dir, 'blueprint-authoring.md');

    expect(playbook).toContain('## Semantics the linter holds you to');
    expect(playbook).toContain('must not import each other'); // folder ≠ entry-only (batch 6 fix)
    expect(playbook).toContain('is a complete outcome'); // zero debt is legitimate (batch 4)
    expect(playbook).toContain('into ONE entry'); // flat-config merge trap (batches 5–6)
    expect(playbook).toContain('includes test files'); // survey/inspect count gap (batch 2)
    expect(playbook).toContain('cross-check every translated clause'); // stale intent docs (batch 2)
    expect(read(dir, '.claude/commands/blueprint-author.md')).toContain('blueprint-authoring.md');
  });
});

describe('alias wiring honesty (batches 1 & 4 + self-review)', () => {
  it('reads the commented tsconfig every Vite + TS starter ships', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'tsconfig.json': `{
          // path aliases — keep in sync with vite.config.ts
          "compilerOptions": {
            /* the "@/*" style key is itself comment-shaped */
            "paths": { "~app/*": ["./src/*"], },
          },
        }`,
      },
    });

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.output).toContain('✓ import alias wired to the toolchain');
  });

  it('rejects the vacuous "@" substring match, accepts a quoted token', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource({
          ...reactBlueprint,
          architecture: { ...reactBlueprint.architecture, alias: '@' },
        }),
        // '@' lives inside every scoped import — this is NOT wiring.
        'vite.config.js': 'import react from \'@vitejs/plugin-react\';\nexport default {};',
      },
    });

    const red = await cli(dir, ['doctor']);

    expect(red.code).toBe(1);
    expect(red.output).toContain('✗ import alias wired to the toolchain');
    expect(red.output).toContain('"@/*": ["./src/*"]');

    write(
      dir,
      'vite.config.js',
      'import react from \'@vitejs/plugin-react\';\n'
      + 'export default { resolve: { alias: { \'@\': \'/src\' } } };',
    );

    const green = await cli(dir, ['doctor']);

    expect(green.output).toContain('✓ import alias wired to the toolchain');
  });
});

describe('zero-debt honesty — notes are not debt (batch 4)', () => {
  it('names an empty suppressions ledger as ceremony (field run #1)', async () => {
    // The first live harness run: the agent obeyed `--suppress-all` on a
    // clean lint, got an empty ledger, and had to discover the asymmetry
    // with the baseline (zero debt writes no file) by itself.
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'eslint-suppressions.json': '{}',
      },
    });

    const doctor = await cli(dir, ['doctor']);
    const line = doctor.output.split('\n').find((entry) => entry.includes('ceremony'));

    expect(line).toContain('delete it (zero lint debt needs no ledger)');
  });

  it('refuses to lock info findings and retires an info-era baseline', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'blueprint.config.mjs': configSource(reactBlueprint) },
    });

    // Declared layers, nothing built yet: info notes only.
    const locked = await cli(dir, ['inspect', '--update-baseline']);

    expect(locked.code).toBe(0);
    expect(locked.output).toContain('informational note(s) are not debt');
    expect(read(dir, '.blueprint-baseline.json')).toBeNull();

    // A pre-1.13 baseline that recorded an info entry still suppresses…
    write(dir, '.blueprint-baseline.json', JSON.stringify({
      findings: [{
        rule: 'missing-layer',
        path: 'src/services',
        message: 'Declared layer "services" has no folder yet.',
      }],
    }));

    const legacy = await cli(dir, ['inspect', '--baseline']);

    expect(legacy.code).toBe(0);

    // …and the next lock retires it instead of preserving the off-label note.
    const relocked = await cli(dir, ['inspect', '--update-baseline']);

    expect(relocked.output).toContain('removed');
    expect(read(dir, '.blueprint-baseline.json')).toBeNull();
  });

  it('names the vacuous net instead of passing an empty room as green', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'src/main.jsx': 'export default 1;', // root wiring — outside every net
      },
    });

    const inspect = await cli(dir, ['inspect']);

    expect(inspect.code).toBe(0);
    expect(inspect.output).toContain('Enforcement is vacuous');

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.output).toContain('clean, but vacuous');
  });
});

describe('impact tells the truth in isolation (batch 5, real eslint)', () => {
  it('separates blueprint hits, isolation artifacts, and stale disables', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'src/components/f.jsx': 'export const f = (unused) => 1;\n',
        'src/components/legacy.jsx':
          '/* eslint-disable custom/no-bad-script-literals -- house rule lives in our config */\n'
          + 'export const legacy = 1;\n',
        'src/components/stale.jsx':
          '// eslint-disable-next-line no-console -- nothing here triggers it\n'
          + 'export const stale = 1;\n',
      },
    });

    const impact = await cli(dir, ['impact']);

    expect(impact.code).toBe(0);
    expect(impact.output).toContain('no-unused-vars');
    // The stale disable is not a parse failure — the file is fine (batch 5),
    // and it sits under the caveat heading, outside the total (batch 8).
    expect(impact.output).toContain('Isolation caveats');
    expect(impact.output).toContain('unused-disable-directive — 1 file(s)');
    expect(impact.output).not.toContain('parse-error —');
    expect(impact.output).toContain('1 hit(s)');
    // Rules from the repo's own config render apart and never count.
    expect(impact.output).toContain('Echoes of YOUR OWN config');
    expect(impact.output).toContain('custom/no-bad-script-literals');
  });

  it('runs the real TypeScript chain — enum members stay unflagged', async () => {
    const dir = repo({
      packageJson: react({ typescript: '^5.0.0' }),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'src/services/api.ts': [
          'enum Status { Ok, Bad }',
          'export const check = (s: Status): boolean => {',
          '  try {',
          '    return s === Status.Ok;',
          '  } catch (error) {',
          '    return false;',
          '  }',
          '};',
          'const dead = 1;',
          '',
        ].join('\n'),
      },
    });

    const impact = await cli(dir, ['impact']);

    expect(impact.code).toBe(0);
    // Unused local + unused catch param — and NOT the enum members.
    expect(impact.output).toContain('@typescript-eslint/no-unused-vars');
    expect(impact.output).toContain('2 hit(s)');
  });

  it('runs the real Vue SFC chain through vue-eslint-parser', async () => {
    const dir = repo({
      packageJson: { name: 'fixture', dependencies: { vue: '^3.0.0' } },
      files: {
        'blueprint.config.mjs': configSource({
          ...reactBlueprint,
          framework: 'vue',
        }),
        'src/components/Btn.vue': [
          '<script>',
          'const wasted = 42;',
          'export default { name: \'Btn\' };',
          '</script>',
          '<template><button>go</button></template>',
          '',
        ].join('\n'),
      },
    });

    const impact = await cli(dir, ['impact']);

    expect(impact.code).toBe(0);
    expect(impact.output).toContain('no-unused-vars');
    expect(impact.output).toContain('Btn.vue');
  });
});

describe('merge survival — wired means still alive (batch 6, real eslint)', () => {
  const selfOnly: Blueprint = {
    framework: 'react',
    architecture: {
      alias: '~app',
      layers: [
        { name: 'views', does: 'pages' },
        {
          name: 'contexts',
          does: 'shared state',
          allowedImporters: [{ layer: 'views', selfOnly: true }],
        },
      ],
      module: { layout: 'flat', entry: 'index', private: [] },
    },
  };

  const spec = (eslintConfig: string): RepoSpec => ({
    packageJson: react(),
    files: {
      'blueprint.config.mjs': configSource(selfOnly),
      'jsconfig.json': JSON.stringify({
        compilerOptions: { paths: { '~app/*': ['./src/*'] } },
      }),
      'src/views/Home.jsx': 'export default 1;',
      'src/contexts/user.jsx': 'export const user = 1;',
      'eslint.config.mjs': eslintConfig,
    },
  });

  it('passes while the emitted structural rules are intact — verified, not skipped', async () => {
    const dir = repo(spec(wiredEslintConfig(selfOnly)));
    const doctor = await cli(dir, ['doctor']);

    // The skip label shares this prefix — a lazy assertion would false-pass
    // on "(skipped — could not resolve …)". Demand the verified verdict.
    expect(doctor.output).toContain('✓ emitted rules survive the merged eslint config\n');
    expect(doctor.output).not.toContain('skipped');
    expect(doctor.code).toBe(0);
  });

  it('verifies an EMPTY repo through synthetic probes — no skip, no blind spot', async () => {
    const bare = (eslintConfig: string): RepoSpec => ({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(selfOnly),
        'jsconfig.json': JSON.stringify({
          compilerOptions: { paths: { '~app/*': ['./src/*'] } },
        }),
        'eslint.config.mjs': eslintConfig,
      },
    });

    // Batch 7's irony: the anti-false-green tool used to go blind exactly
    // where nothing exists yet. Intact wiring now VERIFIES green…
    const green = await cli(repo(bare(wiredEslintConfig(selfOnly))), ['doctor']);

    expect(green.output).toContain('✓ emitted rules survive the merged eslint config\n');
    expect(green.output).not.toContain('skipped');

    // …and a gutted layer turns red with zero files on disk.
    const gutting
      = '  { "files": ["src/views/**/*.js"], '
        + '"rules": { "no-restricted-syntax": ["error", "WithStatement"] } },';

    const red = await cli(repo(bare(wiredEslintConfig(selfOnly, gutting))), ['doctor']);

    expect(red.code).toBe(1);
    expect(red.output).toContain('✗ emitted rules survive the merged eslint config');
    expect(red.output).toContain('views: no-restricted-syntax lost 1 selfOnly selector(s)');
  });

  it('turns red when a later entry silently guts one layer', async () => {
    const gutting
      = '  { "files": ["src/views/**/*.jsx"], '
        + '"rules": { "no-restricted-syntax": ["error", "WithStatement"] } },';

    const dir = repo(spec(wiredEslintConfig(selfOnly, gutting)));
    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(1);
    expect(doctor.output).toContain('✗ emitted rules survive the merged eslint config');
    expect(doctor.output).toContain('views: no-restricted-syntax lost 1 selfOnly selector(s)');
    expect(doctor.output).toContain('combine both option sets into ONE entry');
  });
});

describe('init UX honesty — re-runs and starters tell the truth (batch 10)', () => {
  it('a forced playbook on a starter leads with the early-exit verdict', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    const init = await cli(dir, ['init', '--authoring', '--no-install']);

    expect(init.code).toBe(0);

    const playbook = read(dir, 'blueprint-authoring.md') ?? '';

    // The conclusion an agent needs sits at the top, not mid-ceremony.
    expect(playbook.indexOf('Read this first')).toBeGreaterThan(-1);
    expect(playbook.indexOf('Read this first')).toBeLessThan(playbook.indexOf('## Method'));
    expect(playbook).toContain('npx blueprint init --preset');
  });

  it('second init over a wired vite starter emits no alias instructs', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        // Template-style JSONC — the comment survives init's surgery, so the
        // second run cannot JSON.parse the file it wired itself.
        'tsconfig.json': '{\n  // template comment\n  "compilerOptions": {\n    "strict": true,\n  },\n}\n',
        'vite.config.ts': 'import { defineConfig } from \'vite\'\n\nexport default defineConfig({\n  plugins: [],\n})\n',
      },
    });

    const first = await cli(dir, ['init', '--no-install']);

    expect(first.code).toBe(0);
    expect(read(dir, 'tsconfig.json')).toContain('"~app/*"');
    expect(read(dir, 'vite.config.ts')).toContain('\'~app\'');
    // The both-contracts note names the flag that avoids the second round
    // trip — the field agent never discovered --agent existed.
    expect(first.output).toContain('--agent claude|codex');

    // The scaffolded config imports the package; offline fixtures swap it for data.
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    const second = await cli(dir, ['init', '--no-install']);

    expect(second.code).toBe(0);
    // The field complaint: init #2 printed "Add the import alias to
    // tsconfig…" over a file init #1 had already wired — a false todo that
    // reads as a regression. Both alias instructs must stay silent now.
    expect(second.output).not.toContain('Add the import alias');
    expect(second.output).not.toContain('resolve.alias');
  });
});

describe('the tool answers for itself — no bundle archaeology (batch 12)', () => {
  it('rules prints the catalog, annotated with the declared tiers', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'blueprint.config.mjs': configSource(reactBlueprint) },
    });

    const rules = await cli(dir, ['rules']);

    expect(rules.code).toBe(0);
    expect(rules.output).toContain('always emitted');
    expect(rules.output).toContain('maxLines → max-lines (default 400)');
    expect(rules.output).toContain('✓ error'); // unusedVars, declared in the fixture
    expect(rules.output).toContain('deadCode'); // documentation-only, stated as such
  });
});

describe('--agent persists into the scaffold — no chicken-and-egg (field issue #5)', () => {
  it('first init with --agent claude emits one contract and declares it in the config', async () => {
    const dir = repo({ packageJson: react() });

    const init = await cli(dir, ['init', '--agent', 'claude', '--no-install']);

    expect(init.code).toBe(0);
    expect(read(dir, 'blueprint.config.mjs')).toContain('emit: { agents: [\'claude\'] }');
    expect(read(dir, 'CLAUDE.md')).toContain('<!-- BLUEPRINT:START -->');
    expect(read(dir, 'AGENTS.md')).toBeNull();
    expect(init.output).not.toContain('Wrote both');
  });
});

describe('stale contracts cannot hide behind green (field issues #2–#3)', () => {
  it('doctor flags a hand-touched contract outside emit.agents', async () => {
    // Init only instructs when the stale file carries hand-written content —
    // without this check the orphan lived on with every gate green.
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource({
          ...reactBlueprint,
          emit: { agents: ['claude'] },
        }),
        'CLAUDE.md': '<!-- BLUEPRINT:START -->\ncontract\n<!-- BLUEPRINT:END -->\n',
        'AGENTS.md': '# our own notes\n\n<!-- BLUEPRINT:START -->\nold\n<!-- BLUEPRINT:END -->\n',
      },
    });

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(1);
    expect(doctor.output).toContain('✗ no leftover reference or stale contract files');
    expect(doctor.output).toContain('AGENTS.md');
    expect(doctor.output).toContain('needs its block removed by hand');
  });
});

describe('scaffold matches the doctrine — no invented structure (batch 11)', () => {
  it('scaffolds guidance dirs only into an empty tree', async () => {
    const rooted = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    const init = await cli(rooted, ['init', '--no-install']);

    expect(init.code).toBe(0);
    // Code already lives here — an unbuilt layer's absence is its true
    // state; a .gitkeep shell would contradict "never invent a layer".
    expect(read(rooted, 'src/components/.gitkeep')).toBeNull();
    expect(read(rooted, 'src/pages/.gitkeep')).toBeNull();

    const empty = repo({ packageJson: react() });

    await cli(empty, ['init', '--no-install']);

    // A truly empty tree still gets the guidance scaffold.
    expect(read(empty, 'src/components/.gitkeep')).toBe('');
  });

  it('re-init removes the stale generated contract when emit.agents narrows', async () => {
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--no-install']);

    expect(read(dir, 'AGENTS.md')).toContain('<!-- BLUEPRINT:START -->');

    // The field workflow was config-edit → re-init → *manual rm* — the last
    // step is init's job when the file is wholly its own output.
    write(dir, 'blueprint.config.mjs', configSource({
      ...reactPreset({ name: 'fixture' }),
      emit: { agents: ['claude'] },
    }));

    const second = await cli(dir, ['init', '--no-install']);

    expect(second.code).toBe(0);
    expect(second.output).toContain('stale agent contract');
    expect(read(dir, 'AGENTS.md')).toBeNull();
    expect(read(dir, 'CLAUDE.md')).toContain('<!-- BLUEPRINT:START -->');
  });
});

describe('one story per state — the tools do not contradict each other (field run #10)', () => {
  it('doctor never claims a baseline on a truly clean repo', async () => {
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--no-install']);
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(0);
    // Clean with no ledger: inspect says "no baseline needed", so doctor
    // must not answer the same state with "covered by the baseline".
    expect(doctor.output).toContain('architecture clean');
    expect(doctor.output).not.toContain('covered by the baseline');

    const update = await cli(dir, ['inspect', '--update-baseline']);

    expect(update.code).toBe(0);
    expect(update.output).toContain('no baseline needed');
  });

  it('the CLI and the playbook give the size gate one name and one number', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    const init = await cli(dir, ['init', '--authoring', '--no-install']);

    expect(init.code).toBe(0);
    expect(init.output).toContain('below the brownfield threshold (10 source files)');
    expect(init.output).not.toContain('preset threshold');
    expect(read(dir, 'blueprint-authoring.md')).toContain('brownfield threshold (10)');
  });
});

describe('survey counts never promise what impact must measure (field issue #11)', () => {
  it('playbook and survey call the same-folder count an upper bound, not exact', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        // A same-folder alias reference inside a test file — counted by the
        // survey's textual scan, exempt in the emitted config: the exact
        // shape that made "exactly how many errors" provably false (5 ≠ 0).
        'src/services/api.ts': 'export const api = 1;',
        'src/services/client.test.ts': 'import \'~app/services/api\';',
        'tsconfig.json': JSON.stringify({
          compilerOptions: { paths: { '~app/*': ['./src/*'] } },
        }),
      },
    });

    const init = await cli(dir, ['init', '--authoring', '--no-install']);

    expect(init.code).toBe(0);

    const playbook = read(dir, 'blueprint-authoring.md') ?? '';

    expect(playbook).toContain('an upper bound on the errors');
    expect(playbook).not.toContain('exactly how many');

    const survey = await cli(dir, ['survey']);

    expect(survey.output).toContain('Same-folder imports via the alias (textual upper bound');
  });
});

describe('the emitted CI honors the ratchet it ships with (field issue #10)', () => {
  it('locked debt stays green on the workflow line — the live-verified repro', async () => {
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--no-install']);
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    // One uniform gate line: a missing ledger is an empty one, so this
    // also behaves as plain inspect on a greenfield repo.
    expect(read(dir, '.github/workflows/blueprint-ci.yml'))
      .toContain('npx blueprint inspect --baseline');

    // The field repro: create debt, lock it, then run what CI runs.
    write(dir, 'src/random/x.ts', 'export const x = 1;'); // undeclared folder → error

    expect((await cli(dir, ['inspect'])).code).toBe(1);
    expect((await cli(dir, ['inspect', '--update-baseline'])).code).toBe(0);

    const gate = await cli(dir, ['inspect', '--baseline']);

    // Before the fix the emitted workflow ran plain inspect here — red
    // forever on debt the tool itself told the adopter to lock.
    expect(gate.code).toBe(0);
    expect(gate.output).toContain('1 baselined finding(s) suppressed');
  });
});
