import { createRequire } from 'node:module';
import { afterEach, describe, expect, it } from 'vitest';

import type { Blueprint } from '../config';
// Test-only import of the full emit module — src keeps the patterns-leaf
// boundary; the fixture needs emitLint's real selectors, not a paraphrase.
import { emitLint } from '../emit/lint';
import { reactPreset } from '../presets';
import { cli, configSource, makeRepo, read, rm, wiredEslintConfig, write } from './conformance';
import type { RepoSpec } from './conformance';

/**
 * The adoption conformance suite, grouped by scenario — every scenario
 * below was once a live complaint from an agent adopting the tool on a
 * real repo (the batch numbers point into the feedback ledger). Field runs
 * should only ever find NEW scenarios.
 */

const dirs: string[] = [];

const repo = (spec: RepoSpec = {}): string => {
  const dir = makeRepo(spec);

  dirs.push(dir);

  return dir;
};

afterEach(() => {
  while (dirs.length) rm(dirs.pop() as string);
});

const react = (deps: Record<string, string> = {}) => ({
  name: 'fixture',
  dependencies: { react: '^18.0.0', ...deps },
});

const reactBlueprint: Blueprint = {
  framework: 'react',
  architecture: {
    alias: '~app',
    layers: [
      { name: 'components', does: 'render UI' },
      { name: 'services', does: 'data access' },
    ],
    module: { layout: 'flat', entry: 'index', private: [] },
  },
  rules: { unusedVars: 'error' },
};

describe('fail-loud floor', () => {
  it('a command that needs a config says so on stderr and exits 1', async () => {
    const impact = await cli(repo(), ['impact']);

    expect(impact.code).toBe(1);
    expect(impact.output).toContain('author the config first');
  });

  it('rejects the manufactured-net workaround: a layer literally named * (batch 9)', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource({
          ...reactBlueprint,
          architecture: {
            ...reactBlueprint.architecture,
            layers: [{ name: '*', does: 'root files smuggled into the net' }],
          },
        }),
      },
    });

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(1);
    expect(doctor.output).toContain('glob or path characters');
    expect(doctor.output).toContain('Root files are wiring, not a layer');
  });
});

describe('greenfield scaffold — init alone completes (batches 1 & 4)', () => {
  it('init → inspect green → doctor passes all 7 checks', async () => {
    const dir = repo({ packageJson: react() });

    const init = await cli(dir, ['init', '--no-install']);

    expect(init.code).toBe(0);
    expect(read(dir, 'blueprint.config.mjs')).toContain('reactPreset');
    expect(read(dir, 'eslint.config.mjs')).toContain('Generated by @kekkai/blueprint');
    // No tsconfig existed — init creates jsconfig so the alias resolves (B1's gap).
    expect(read(dir, 'jsconfig.json')).toContain('"~app/*"');
    expect(read(dir, 'docs/architecture-handbook.md')).toContain('# ');

    // The scaffolded config imports the package; offline fixtures have no
    // node_modules (--no-install), so swap in the equivalent preset as data.
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    const inspect = await cli(dir, ['inspect']);

    expect(inspect.code).toBe(0);
    expect(inspect.output).toContain('Coverage:');

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(0);
    expect(doctor.output).toContain('Adoption complete — all 7 checks passed');
  });
});

describe('brownfield playbook — semantics stated, nothing reverse-engineered (batches 1–3)', () => {
  it('init writes the playbook with the rules an agent used to dig from dist', async () => {
    const files = Object.fromEntries([
      ...Array.from({ length: 8 }, (_, i) => [
        `src/components/C${i}.jsx`,
        `export const c${i} = ${i};`,
      ]),
      ...Array.from({ length: 4 }, (_, i) => [
        `src/services/s${i}.js`,
        `import { c${i} } from '../components/C${i}';\nexport const s${i} = c${i};`,
      ]),
    ]);

    const dir = repo({ packageJson: react(), files });
    const init = await cli(dir, ['init', '--no-install']);

    expect(init.code).toBe(0);

    const playbook = read(dir, 'blueprint-authoring.md');

    expect(playbook).toContain('## Semantics the linter holds you to');
    expect(playbook).toContain('must not import each other'); // folder ≠ entry-only (batch 6 fix)
    expect(playbook).toContain('is a complete outcome'); // zero debt is legitimate (batch 4)
    expect(playbook).toContain('into ONE entry'); // flat-config merge trap (batches 5–6)
    expect(playbook).toContain('includes test files'); // survey/inspect count gap (batch 2)
    expect(playbook).toContain('cross-check every translated clause'); // stale intent docs (batch 2)
    expect(read(dir, '.claude/commands/blueprint-author.md')).toContain('blueprint-authoring.md');
  });
});

describe('alias wiring honesty (batches 1 & 4 + self-review)', () => {
  it('reads the commented tsconfig every Vite + TS starter ships', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'tsconfig.json': `{
          // path aliases — keep in sync with vite.config.ts
          "compilerOptions": {
            /* the "@/*" style key is itself comment-shaped */
            "paths": { "~app/*": ["./src/*"], },
          },
        }`,
      },
    });

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.output).toContain('✓ import alias wired to the toolchain');
  });

  it('rejects the vacuous "@" substring match, accepts a quoted token', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource({
          ...reactBlueprint,
          architecture: { ...reactBlueprint.architecture, alias: '@' },
        }),
        // '@' lives inside every scoped import — this is NOT wiring.
        'vite.config.js': 'import react from \'@vitejs/plugin-react\';\nexport default {};',
      },
    });

    const red = await cli(dir, ['doctor']);

    expect(red.code).toBe(1);
    expect(red.output).toContain('✗ import alias wired to the toolchain');
    expect(red.output).toContain('"@/*": ["./src/*"]');

    write(
      dir,
      'vite.config.js',
      'import react from \'@vitejs/plugin-react\';\n'
      + 'export default { resolve: { alias: { \'@\': \'/src\' } } };',
    );

    const green = await cli(dir, ['doctor']);

    expect(green.output).toContain('✓ import alias wired to the toolchain');
  });
});

describe('zero-debt honesty — notes are not debt (batch 4)', () => {
  it('names an empty suppressions ledger as ceremony (field run #1)', async () => {
    // The first live harness run: the agent obeyed `--suppress-all` on a
    // clean lint, got an empty ledger, and had to discover the asymmetry
    // with the baseline (zero debt writes no file) by itself.
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'eslint-suppressions.json': '{}',
      },
    });

    const doctor = await cli(dir, ['doctor']);
    const line = doctor.output.split('\n').find((entry) => entry.includes('ceremony'));

    expect(line).toContain('delete it (zero lint debt needs no ledger)');
  });

  it('refuses to lock info findings and retires an info-era baseline', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'blueprint.config.mjs': configSource(reactBlueprint) },
    });

    // Declared layers, nothing built yet: info notes only.
    const locked = await cli(dir, ['inspect', '--update-baseline']);

    expect(locked.code).toBe(0);
    expect(locked.output).toContain('informational note(s) are not debt');
    expect(read(dir, '.blueprint-baseline.json')).toBeNull();

    // A pre-1.13 baseline that recorded an info entry still suppresses…
    write(dir, '.blueprint-baseline.json', JSON.stringify({
      findings: [{
        rule: 'missing-layer',
        path: 'src/services',
        message: 'Declared layer "services" has no folder yet.',
      }],
    }));

    const legacy = await cli(dir, ['inspect', '--baseline']);

    expect(legacy.code).toBe(0);

    // …and the next lock retires it instead of preserving the off-label note.
    const relocked = await cli(dir, ['inspect', '--update-baseline']);

    expect(relocked.output).toContain('removed');
    expect(read(dir, '.blueprint-baseline.json')).toBeNull();
  });

  it('names the vacuous net instead of passing an empty room as green', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'src/main.jsx': 'export default 1;', // root wiring — outside every net
      },
    });

    const inspect = await cli(dir, ['inspect']);

    expect(inspect.code).toBe(0);
    expect(inspect.output).toContain('Enforcement is vacuous');

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.output).toContain('clean, but vacuous');
  });
});

describe('impact tells the truth in isolation (batch 5, real eslint)', () => {
  it('separates blueprint hits, isolation artifacts, and stale disables', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'src/components/f.jsx': 'export const f = (unused) => 1;\n',
        'src/components/legacy.jsx':
          '/* eslint-disable custom/no-bad-script-literals -- house rule lives in our config */\n'
          + 'export const legacy = 1;\n',
        'src/components/stale.jsx':
          '// eslint-disable-next-line no-console -- nothing here triggers it\n'
          + 'export const stale = 1;\n',
      },
    });

    const impact = await cli(dir, ['impact']);

    expect(impact.code).toBe(0);
    expect(impact.output).toContain('no-unused-vars');
    // The stale disable is not a parse failure — the file is fine (batch 5),
    // and it sits under the caveat heading, outside the total (batch 8).
    expect(impact.output).toContain('Isolation caveats');
    expect(impact.output).toContain('unused-disable-directive — 1 file(s)');
    expect(impact.output).not.toContain('parse-error —');
    expect(impact.output).toContain('1 hit(s)');
    // Rules from the repo's own config render apart and never count.
    expect(impact.output).toContain('Echoes of YOUR OWN config');
    expect(impact.output).toContain('custom/no-bad-script-literals');
  });

  it('runs the real TypeScript chain — enum members stay unflagged', async () => {
    const dir = repo({
      packageJson: react({ typescript: '^5.0.0' }),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'src/services/api.ts': [
          'enum Status { Ok, Bad }',
          'export const check = (s: Status): boolean => {',
          '  try {',
          '    return s === Status.Ok;',
          '  } catch (error) {',
          '    return false;',
          '  }',
          '};',
          'const dead = 1;',
          '',
        ].join('\n'),
      },
    });

    const impact = await cli(dir, ['impact']);

    expect(impact.code).toBe(0);
    // Unused local + unused catch param — and NOT the enum members.
    expect(impact.output).toContain('@typescript-eslint/no-unused-vars');
    expect(impact.output).toContain('2 hit(s)');
  });

  it('runs the real Vue SFC chain through vue-eslint-parser', async () => {
    const dir = repo({
      packageJson: { name: 'fixture', dependencies: { vue: '^3.0.0' } },
      files: {
        'blueprint.config.mjs': configSource({
          ...reactBlueprint,
          framework: 'vue',
        }),
        'src/components/Btn.vue': [
          '<script>',
          'const wasted = 42;',
          'export default { name: \'Btn\' };',
          '</script>',
          '<template><button>go</button></template>',
          '',
        ].join('\n'),
      },
    });

    const impact = await cli(dir, ['impact']);

    expect(impact.code).toBe(0);
    expect(impact.output).toContain('no-unused-vars');
    expect(impact.output).toContain('Btn.vue');
  });
});

describe('merge survival — wired means still alive (batch 6, real eslint)', () => {
  const selfOnly: Blueprint = {
    framework: 'react',
    architecture: {
      alias: '~app',
      layers: [
        { name: 'views', does: 'pages' },
        {
          name: 'contexts',
          does: 'shared state',
          allowedImporters: [{ layer: 'views', selfOnly: true }],
        },
      ],
      module: { layout: 'flat', entry: 'index', private: [] },
    },
  };

  const spec = (eslintConfig: string): RepoSpec => ({
    packageJson: react(),
    files: {
      'blueprint.config.mjs': configSource(selfOnly),
      'jsconfig.json': JSON.stringify({
        compilerOptions: { paths: { '~app/*': ['./src/*'] } },
      }),
      'src/views/Home.jsx': 'export default 1;',
      'src/contexts/user.jsx': 'export const user = 1;',
      'eslint.config.mjs': eslintConfig,
    },
  });

  it('passes while the emitted structural rules are intact — verified, not skipped', async () => {
    const dir = repo(spec(wiredEslintConfig(selfOnly)));
    const doctor = await cli(dir, ['doctor']);

    // The skip label shares this prefix — a lazy assertion would false-pass
    // on "(skipped — could not resolve …)". Demand the verified verdict.
    expect(doctor.output).toContain('✓ emitted rules survive the merged eslint config\n');
    expect(doctor.output).not.toContain('skipped');
    expect(doctor.code).toBe(0);
  });

  it('verifies an EMPTY repo through synthetic probes — no skip, no blind spot', async () => {
    const bare = (eslintConfig: string): RepoSpec => ({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(selfOnly),
        'jsconfig.json': JSON.stringify({
          compilerOptions: { paths: { '~app/*': ['./src/*'] } },
        }),
        'eslint.config.mjs': eslintConfig,
      },
    });

    // Batch 7's irony: the anti-false-green tool used to go blind exactly
    // where nothing exists yet. Intact wiring now VERIFIES green…
    const green = await cli(repo(bare(wiredEslintConfig(selfOnly))), ['doctor']);

    expect(green.output).toContain('✓ emitted rules survive the merged eslint config\n');
    expect(green.output).not.toContain('skipped');

    // …and a gutted layer turns red with zero files on disk.
    const gutting
      = '  { "files": ["src/views/**/*.js"], '
        + '"rules": { "no-restricted-syntax": ["error", "WithStatement"] } },';

    const red = await cli(repo(bare(wiredEslintConfig(selfOnly, gutting))), ['doctor']);

    expect(red.code).toBe(1);
    expect(red.output).toContain('✗ emitted rules survive the merged eslint config');
    expect(red.output).toContain('views: no-restricted-syntax lost 1 selfOnly selector(s)');
  });

  it('turns red when a later entry silently guts one layer', async () => {
    const gutting
      = '  { "files": ["src/views/**/*.jsx"], '
        + '"rules": { "no-restricted-syntax": ["error", "WithStatement"] } },';

    const dir = repo(spec(wiredEslintConfig(selfOnly, gutting)));
    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(1);
    expect(doctor.output).toContain('✗ emitted rules survive the merged eslint config');
    expect(doctor.output).toContain('views: no-restricted-syntax lost 1 selfOnly selector(s)');
    expect(doctor.output).toContain('combine both option sets into ONE entry');
  });
});

describe('init UX honesty — re-runs and starters tell the truth (batch 10)', () => {
  it('a forced playbook on a starter leads with the early-exit verdict', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    const init = await cli(dir, ['init', '--authoring', '--no-install']);

    expect(init.code).toBe(0);

    const playbook = read(dir, 'blueprint-authoring.md') ?? '';

    // The conclusion an agent needs sits at the top, not mid-ceremony.
    expect(playbook.indexOf('Read this first')).toBeGreaterThan(-1);
    expect(playbook.indexOf('Read this first')).toBeLessThan(playbook.indexOf('## Method'));
    expect(playbook).toContain('npx blueprint init --preset');
  });

  it('second init over a wired vite starter emits no alias instructs', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        // Template-style JSONC — the comment survives init's surgery, so the
        // second run cannot JSON.parse the file it wired itself.
        'tsconfig.json': '{\n  // template comment\n  "compilerOptions": {\n    "strict": true,\n  },\n}\n',
        'vite.config.ts': 'import { defineConfig } from \'vite\'\n\nexport default defineConfig({\n  plugins: [],\n})\n',
      },
    });

    const first = await cli(dir, ['init', '--no-install']);

    expect(first.code).toBe(0);
    expect(read(dir, 'tsconfig.json')).toContain('"~app/*"');
    expect(read(dir, 'vite.config.ts')).toContain('\'~app\'');
    // The both-contracts note names the flag that avoids the second round
    // trip — the field agent never discovered --agent existed.
    expect(first.output).toContain('--agent claude|codex');

    // The scaffolded config imports the package; offline fixtures swap it for data.
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    const second = await cli(dir, ['init', '--no-install']);

    expect(second.code).toBe(0);
    // The field complaint: init #2 printed "Add the import alias to
    // tsconfig…" over a file init #1 had already wired — a false todo that
    // reads as a regression. Both alias instructs must stay silent now.
    expect(second.output).not.toContain('Add the import alias');
    expect(second.output).not.toContain('resolve.alias');
  });
});

describe('the tool answers for itself — no bundle archaeology (batch 12)', () => {
  it('rules prints the catalog, annotated with the declared tiers', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'blueprint.config.mjs': configSource(reactBlueprint) },
    });

    const rules = await cli(dir, ['rules']);

    expect(rules.code).toBe(0);
    expect(rules.output).toContain('Structural — dependency flow & ownership');
    expect(rules.output).toContain('maxLines → max-lines (default 400)');
    expect(rules.output).toContain('✓ error'); // unusedVars, declared in the fixture
    expect(rules.output).toContain('deadCode'); // documentation-only, stated as such
  });
});

describe('--agent persists into the scaffold — no chicken-and-egg (field issue #5)', () => {
  it('first init with --agent claude emits one contract and declares it in the config', async () => {
    const dir = repo({ packageJson: react() });

    const init = await cli(dir, ['init', '--agent', 'claude', '--no-install']);

    expect(init.code).toBe(0);
    expect(read(dir, 'blueprint.config.mjs')).toContain('emit: { agents: [\'claude\'] }');
    expect(read(dir, 'CLAUDE.md')).toContain('<!-- BLUEPRINT:START -->');
    expect(read(dir, 'AGENTS.md')).toBeNull();
    expect(init.output).not.toContain('Wrote both');
  });
});

describe('stale contracts cannot hide behind green (field issues #2–#3)', () => {
  it('doctor flags a hand-touched contract outside emit.agents', async () => {
    // Init only instructs when the stale file carries hand-written content —
    // without this check the orphan lived on with every gate green.
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource({
          ...reactBlueprint,
          emit: { agents: ['claude'] },
        }),
        'CLAUDE.md': '<!-- BLUEPRINT:START -->\ncontract\n<!-- BLUEPRINT:END -->\n',
        'AGENTS.md': '# our own notes\n\n<!-- BLUEPRINT:START -->\nold\n<!-- BLUEPRINT:END -->\n',
      },
    });

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(1);
    expect(doctor.output).toContain('✗ no leftover reference, authoring, or stale contract files');
    expect(doctor.output).toContain('AGENTS.md');
    expect(doctor.output).toContain('needs its block removed by hand');
  });
});

describe('scaffold matches the doctrine — no invented structure (batch 11)', () => {
  it('scaffolds guidance dirs only into an empty tree', async () => {
    const rooted = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    const init = await cli(rooted, ['init', '--no-install']);

    expect(init.code).toBe(0);
    // Code already lives here — an unbuilt layer's absence is its true
    // state; a .gitkeep shell would contradict "never invent a layer".
    expect(read(rooted, 'src/components/.gitkeep')).toBeNull();
    expect(read(rooted, 'src/pages/.gitkeep')).toBeNull();

    const empty = repo({ packageJson: react() });

    await cli(empty, ['init', '--no-install']);

    // A truly empty tree still gets the guidance scaffold.
    expect(read(empty, 'src/components/.gitkeep')).toBe('');
  });

  it('re-init removes the stale generated contract when emit.agents narrows', async () => {
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--no-install']);

    expect(read(dir, 'AGENTS.md')).toContain('<!-- BLUEPRINT:START -->');

    // The field workflow was config-edit → re-init → *manual rm* — the last
    // step is init's job when the file is wholly its own output.
    write(dir, 'blueprint.config.mjs', configSource({
      ...reactPreset({ name: 'fixture' }),
      emit: { agents: ['claude'] },
    }));

    const second = await cli(dir, ['init', '--no-install']);

    expect(second.code).toBe(0);
    expect(second.output).toContain('stale agent contract');
    expect(read(dir, 'AGENTS.md')).toBeNull();
    expect(read(dir, 'CLAUDE.md')).toContain('<!-- BLUEPRINT:START -->');
  });
});

describe('one story per state — the tools do not contradict each other (field run #10)', () => {
  it('doctor never claims a baseline on a truly clean repo', async () => {
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--no-install']);
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.code).toBe(0);
    // Clean with no ledger: inspect says "no baseline needed", so doctor
    // must not answer the same state with "covered by the baseline".
    expect(doctor.output).toContain('architecture clean');
    expect(doctor.output).not.toContain('covered by the baseline');

    const update = await cli(dir, ['inspect', '--update-baseline']);

    expect(update.code).toBe(0);
    expect(update.output).toContain('no baseline needed');
  });

  it('the CLI and the playbook give the size gate one name and one number', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    const init = await cli(dir, ['init', '--authoring', '--no-install']);

    expect(init.code).toBe(0);
    expect(init.output).toContain('below the brownfield threshold (10 source files)');
    expect(init.output).not.toContain('preset threshold');
    expect(read(dir, 'blueprint-authoring.md')).toContain('brownfield threshold (10)');
  });
});

describe('survey counts never promise what impact must measure (field issue #11)', () => {
  it('playbook and survey call the same-folder count an upper bound, not exact', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        // A same-folder alias reference inside a test file — counted by the
        // survey's textual scan, exempt in the emitted config: the exact
        // shape that made "exactly how many errors" provably false (5 ≠ 0).
        'src/services/api.ts': 'export const api = 1;',
        'src/services/client.test.ts': 'import \'~app/services/api\';',
        'tsconfig.json': JSON.stringify({
          compilerOptions: { paths: { '~app/*': ['./src/*'] } },
        }),
      },
    });

    const init = await cli(dir, ['init', '--authoring', '--no-install']);

    expect(init.code).toBe(0);

    const playbook = read(dir, 'blueprint-authoring.md') ?? '';

    expect(playbook).toContain('an upper bound on the errors');
    expect(playbook).not.toContain('exactly how many');

    const survey = await cli(dir, ['survey']);

    expect(survey.output).toContain('Same-folder imports via the alias (textual upper bound');
  });

  it('a draft config that never mentions module.private validates and runs', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'src/components/Button.tsx': 'export const Button = 1;',
        // Hand-written draft-first config — the field shape that tripped on
        // "private is required": omitting it now means none.
        'blueprint.config.mjs': [
          'export default {',
          '  framework: \'react\',',
          '  architecture: {',
          '    alias: \'~app\',',
          '    layers: [{ name: \'components\', does: \'render UI\' }],',
          '    module: { layout: \'flat\', entry: \'index\' },',
          '  },',
          '  rules: {},',
          '};',
          '',
        ].join('\n'),
      },
    });

    const inspect = await cli(dir, ['inspect']);

    expect(inspect.code).toBe(0);
    expect(inspect.output).not.toContain('module.private');
  });
});

describe('a misplaced key fails loud instead of dying silently (field issue #14)', () => {
  it('layer-level selfOnly errors with the pointed fix — the field config verbatim', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        // The 489-file field repo's shape: selfOnly on the layer object,
        // where nothing reads it — the intended re-export ban silently
        // never existed and every gate stayed green.
        'blueprint.config.mjs': [
          'export default {',
          '  framework: \'react\',',
          '  architecture: {',
          '    alias: \'~app\',',
          '    layers: [',
          '      { name: \'views\', does: \'pages\' },',
          '      { name: \'contexts\', does: \'seam\', selfOnly: true, allowedImporters: [\'views\'] },',
          '    ],',
          '    module: { layout: \'flat\', entry: \'index\' },',
          '  },',
          '  rules: {},',
          '};',
          '',
        ].join('\n'),
        'src/views/home.tsx': 'export const home = 1;',
      },
    });

    const inspect = await cli(dir, ['inspect']);

    expect(inspect.code).toBe(1);
    expect(inspect.output).toContain('Unknown key "selfOnly"');
    expect(inspect.output).toContain('allowedImporters ENTRY');
  });

  it('rules states whether THIS config emits each structural rule', async () => {
    // reactBlueprint declares no selfOnly importer — the catalog must say
    // its no-restricted-syntax is not emitted, instead of listing it
    // statically while emitLint disagrees.
    const dir = repo({
      packageJson: react(),
      files: { 'blueprint.config.mjs': configSource(reactBlueprint) },
    });

    const rules = await cli(dir, ['rules']);

    expect(rules.code).toBe(0);
    expect(rules.output).toContain('· not emitted');
    expect(rules.output).toContain('✓ emits');

    const json = await cli(dir, ['rules', '--json']);
    const parsed = JSON.parse(json.output) as { structural: { rule: string; active: boolean }[] };

    expect(parsed.structural.find((row) => row.rule === 'no-restricted-syntax')?.active).toBe(false);
    expect(parsed.structural.find((row) => row.rule === 'no-restricted-imports')?.active).toBe(true);
  });
});

describe('doctor and the playbook define "done" identically (field issue #13)', () => {
  it('doctor stays red while authoring artifacts remain, green once deleted', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    // The early-exit route: playbook written, preset scaffolded over it.
    await cli(dir, ['init', '--authoring', '--no-install']);
    await cli(dir, ['init', '--preset', '--no-install']);
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    // Wiring is complete but the playbook still sits on disk — the state
    // where doctor used to say "Adoption complete" and a careless agent
    // stopped, leaving blueprint-authoring.md in the repo forever.
    const mid = await cli(dir, ['doctor']);

    expect(mid.code).toBe(1);
    expect(mid.output).toContain('blueprint-authoring.md');
    expect(mid.output).toContain('the playbook\'s final step deletes them');

    rm(`${dir}/blueprint-authoring.md`);
    rm(`${dir}/.claude/commands/blueprint-author.md`);

    const done = await cli(dir, ['doctor']);

    expect(done.code).toBe(0);
    expect(done.output).toContain('Adoption complete — all 7 checks passed');
  });

  it('the missing-layer note reads as runway, never as a todo', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'blueprint.config.mjs': configSource(reactBlueprint) },
    });

    const inspect = await cli(dir, ['inspect']);

    expect(inspect.code).toBe(0);
    // Six of these once sent an agent toward deleting the preset skeleton —
    // the note itself now carries the keep-is-default verdict.
    expect(inspect.output).toContain('runway, not a todo');
    expect(inspect.output).toContain('slimming is the owner\'s call');
  });
});

describe('one output, one story — no snippet contradicts its own prose (field issue #12)', () => {
  it('impact names a vacuous zero instead of a reassuring one', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        // Source exists, but nothing under a declared layer — the state
        // inspect already warns about; impact must tell the same story.
        'src/App.jsx': 'export const App = () => null;',
      },
    });

    const impact = await cli(dir, ['impact']);

    expect(impact.code).toBe(0);
    expect(impact.output).toContain('0 hits — vacuous: the layer globs match no files');
    // "No red" is an emitLint claim — the anti-bypass guard is outside
    // impact's scope, and a field agent nearly shipped on the headline
    // alone (field issue #17): the zero line states its own reach.
    expect(impact.output).toContain('scope: emitLint only');
  });

  it('the wiring snippet on a TS repo is the TS version, not prose-corrected JS', async () => {
    const dir = repo({
      packageJson: {
        name: 'fixture',
        dependencies: { react: '^18.0.0' },
        devDependencies: { typescript: '^5.0.0' },
      },
      files: {
        'eslint.config.mjs': 'export default [];',
        'src/App.tsx': 'export const App = () => null;',
      },
    });

    const init = await cli(dir, ['init', '--preset', '--no-install']);

    expect(init.code).toBe(0);
    expect(init.output).toContain('...emitLint(blueprint, { typescript: tseslint.plugin }) ];');
    expect(init.output).not.toContain('On a TypeScript');
  });

  it('the authoring hand-off promises a baseline only if debt exists', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    const init = await cli(dir, ['init', '--authoring', '--no-install']);

    expect(init.code).toBe(0);
    expect(init.output).toContain('locking a baseline only when debt exists');
    expect(init.output).not.toContain('and locking a baseline):');
  });
});

describe('selfOnly survives every esquery, and the fold gets its selectors (batch 13)', () => {
  const selfOnly: Blueprint = {
    framework: 'react',
    architecture: {
      alias: '~app',
      layers: [
        { name: 'views', does: 'pages' },
        {
          name: 'contexts',
          does: 'shared state',
          allowedImporters: [{ layer: 'views', selfOnly: true }],
        },
      ],
      module: { layout: 'flat', entry: 'index', private: [] },
    },
  };

  const emittedSelectors = () =>
    emitLint(selfOnly)
      .flatMap((entry) =>
        (entry.rules?.['no-restricted-syntax'] as unknown[] | undefined)?.slice(1) ?? [])
      .map((item) => (item as { selector: string }).selector);

  it('the emitted selector parses and matches on esquery 1.6 — the crash line', () => {
    // esquery below 1.7 has no `\/` escape in its regex literal: the old
    // selector truncated to `^~app\` and threw "Invalid regular expression"
    // on EVERY file of the layer — killing the project's own `eslint .` and
    // `blueprint impact` alike (field issue #19). The pinned legacy version
    // is the regression guard; this repo's own esquery is too new to crash.
    const legacy = createRequire(import.meta.url)('esquery-legacy') as {
      parse: (selector: string) => unknown;
      matches: (node: object, ast: unknown) => boolean;
    };

    const selectors = emittedSelectors();

    expect(selectors).toHaveLength(1);

    for (const selector of selectors) {
      const ast = legacy.parse(selector);

      const ban = (value: string) =>
        legacy.matches({ type: 'ExportAllDeclaration', source: { type: 'Literal', value } }, ast);

      expect(ban('~app/contexts/user')).toBe(true);
      expect(ban('~app/hooks/useX')).toBe(false);
    }
  });

  it('impact reports the re-export instead of crashing', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(selfOnly),
        'jsconfig.json': JSON.stringify({
          compilerOptions: { paths: { '~app/*': ['./src/*'] } },
        }),
        'src/contexts/user.jsx': 'export const user = 1;',
        'src/views/Home.jsx': 'export { user } from \'~app/contexts/user\';\n',
      },
    });

    const impact = await cli(dir, ['impact']);

    expect(impact.code).toBe(0);
    expect(impact.output).toContain('no-restricted-syntax');
    expect(impact.output).toContain('Home.jsx');
  });

  it('rules carries the selectors a fold needs — no emitLint dump (field issue #20)', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'blueprint.config.mjs': configSource(selfOnly) },
    });

    const json = await cli(dir, ['rules', '--json']);

    const parsed = JSON.parse(json.output) as {
      bans: { layer: string; selfOnly: { target: string; selectors: string[] }[] }[];
    };

    const views = parsed.bans.find((entry) => entry.layer === 'views');

    expect(views?.selfOnly).toEqual([{ target: 'contexts', selectors: emittedSelectors() }]);

    // The text catalog prints the same strings — an agent without --json
    // still never needs to dump emitLint.
    const text = await cli(dir, ['rules']);

    expect(text.output).toContain('Copy these selectors verbatim');
    expect(text.output).toContain(emittedSelectors()[0]);
  });
});

describe('merge caveats meet the agent at the point of need (batch 14)', () => {
  it('init names TS7016 and its remedies when the existing config is eslint.config.ts', async () => {
    // The field repo's eslint.config.ts sat in a tsconfig without allowJs:
    // importing ./blueprint.config.mjs turned the repo's own tsc gate red,
    // and the fix was the agent's invention — init knew the stack and the
    // config shape but never said it (field issue #22).
    const dir = repo({
      packageJson: {
        name: 'fixture',
        dependencies: { react: '^18.0.0' },
        devDependencies: { typescript: '^5.0.0' },
      },
      files: {
        'eslint.config.ts': 'export default [];',
        'src/App.tsx': 'export const App = () => null;',
      },
    });

    const init = await cli(dir, ['init', '--preset', '--no-install']);

    expect(init.code).toBe(0);
    expect(init.output).toContain('TS7016');
    expect(init.output).toContain('allowJs');
    expect(init.output).toContain('blueprint.config.d.mts');
  });

  it('the early-exit checklist orders a real lint run and a real build run', async () => {
    // Two runs in the same batch added the build check by hand: init edits
    // tsconfig/vite for the alias, and doctor's alias check reads wiring as
    // text — the "only a real run proves it" logic has to cover both edits
    // (field issues #21–#22).
    const dir = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    await cli(dir, ['init', '--authoring', '--no-install']);

    const playbook = read(dir, 'blueprint-authoring.md') ?? '';

    expect(playbook).toContain('only a real run proves the config loads');
    expect(playbook).toContain('build once too');
    expect(playbook).toContain('never as a compile');
  });
});

describe('the flat default is real — module is optional (batch 15)', () => {
  it('a config that never mentions module validates and inspects clean', async () => {
    // The field shape verbatim: Method step 5 said "plain files → the flat
    // default", validation demanded module.entry — two edit-run cycles plus
    // a deliberate repro before the agent could prove the tool contradicted
    // itself (field issue #23).
    const noModule: Blueprint = {
      framework: 'react',
      architecture: {
        alias: '~app',
        layers: [{ name: 'components', does: 'render UI' }],
      },
    };

    const bare = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(noModule),
        'src/components/Button.jsx': 'export const Button = 1;',
      },
    });

    const inspect = await cli(bare, ['inspect']);

    expect(inspect.code).toBe(0);
    expect(inspect.output).not.toContain('module.entry');

    // Partial declaration — the exact second repro from the field.
    const layoutOnly = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource({
          ...noModule,
          architecture: { ...noModule.architecture, module: { layout: 'flat' } },
        }),
        'src/components/Button.jsx': 'export const Button = 1;',
      },
    });

    expect((await cli(layoutOnly, ['inspect'])).code).toBe(0);
  });

  it('an empty entry still fails loud, now naming the default as the way out', async () => {
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource({
          framework: 'react',
          architecture: {
            alias: '~app',
            layers: [{ name: 'components', does: 'render UI' }],
            module: { layout: 'flat', entry: '' },
          },
        }),
      },
    });

    const inspect = await cli(dir, ['inspect']);

    expect(inspect.code).toBe(1);
    expect(inspect.output).toContain('omit it for the');
  });

  it('the playbook sketch says the module block is optional', async () => {
    const dir = repo({
      packageJson: react(),
      files: { 'src/App.jsx': 'export const App = () => null;' },
    });

    await cli(dir, ['init', '--authoring', '--no-install']);

    const playbook = read(dir, 'blueprint-authoring.md') ?? '';

    expect(playbook).toContain('omit `module` entirely');
    expect(playbook).toContain('Optional — omitting module');
  });
});

describe('init and doctor tell one alias story; integrated contracts stay fresh (batch 16)', () => {
  it('a tsconfig-paths bridge plugin silences the vite instruct — init agrees with doctor (field #25)', async () => {
    // The field repo: alias in tsconfig paths, vite-tsconfig-paths bridging
    // it — init still said "add resolve.alias" while doctor passed the same
    // state untouched. Two authorities, two verdicts, minutes of probing.
    const dir = repo({
      packageJson: react(),
      files: {
        'blueprint.config.mjs': configSource(reactBlueprint),
        'tsconfig.json': JSON.stringify({
          compilerOptions: { paths: { '~app/*': ['./src/*'] } },
        }),
        'vite.config.ts': 'import tsconfigPaths from \'vite-tsconfig-paths\';\n'
          + 'export default { plugins: [tsconfigPaths()] };\n',
        'src/components/Button.jsx': 'export const Button = 1;',
      },
    });

    const init = await cli(dir, ['init', '--no-install']);

    expect(init.code).toBe(0);
    expect(init.output).not.toContain('resolve.alias');

    const doctor = await cli(dir, ['doctor']);

    expect(doctor.output).toContain('✓ import alias wired to the toolchain');
  });

  it('a marker-integrated CLAUDE.md is refreshed by the next init (field #26)', async () => {
    // The field repro inverted: the reference now ships WITH its markers, so
    // a verbatim integration keeps the block refreshable — the run that
    // integrated by guesswork ended with a permanently stale layer flow.
    // (First init scaffolds the config instead of loading one: an in-process
    // ESM import of blueprint.config.mjs would be cached across cli() calls,
    // which real per-process runs never hit.)
    const dir = repo({
      packageJson: react(),
      files: {
        'CLAUDE.md': '# My app\n\nhand-written notes\n',
        'src/components/Button.jsx': 'export const Button = 1;',
      },
    });

    const init = await cli(dir, ['init', '--no-install']);

    expect(init.code).toBe(0);
    expect(init.output).toContain('KEEP the');

    const reference = read(dir, 'CLAUDE.blueprint.md') ?? '';

    expect(reference.startsWith('<!-- BLUEPRINT:START -->')).toBe(true);

    // Integrate verbatim (markers included), delete the reference, then
    // change the config — the exact sequence that went stale in the field.
    write(dir, 'CLAUDE.md', `# My app\n\nhand-written notes\n\n${reference}`);
    rm(`${dir}/CLAUDE.blueprint.md`);

    write(dir, 'blueprint.config.mjs', configSource({
      ...reactBlueprint,
      architecture: {
        ...reactBlueprint.architecture,
        layers: [
          { name: 'components', does: 'render UI' },
          { name: 'api', does: 'data access' },
        ],
      },
    }));

    const second = await cli(dir, ['init', '--no-install']);

    expect(second.code).toBe(0);

    const merged = read(dir, 'CLAUDE.md') ?? '';

    expect(merged).toContain('hand-written notes'); // outside the markers — untouched
    expect(merged).toContain('`api`'); // inside the markers — refreshed
    expect(merged).not.toContain('`containers`'); // the scaffold-era flow is gone
  });
});

describe('an offset additional alias really joins the bans (batch 19)', () => {
  // Field issue #29: additionalAliases: { '~root': '.' } emitted
  // `~root/<layer>` patterns no real import ever used — the whole ~root
  // leg of every structural ban was a silent no-op, inspect was equally
  // blind, and the closing report almost claimed a protection that did
  // not exist.
  const rooted: Blueprint = {
    framework: 'react',
    architecture: {
      alias: '~app',
      additionalAliases: { '~root': '.' },
      layers: [
        { name: 'views', does: 'pages' },
        {
          name: 'contexts',
          does: 'shared state',
          allowedImporters: [{ layer: 'views', selfOnly: true }],
        },
      ],
    },
  };

  const spec = (): RepoSpec => ({
    packageJson: react(),
    files: {
      'blueprint.config.mjs': configSource(rooted),
      'jsconfig.json': JSON.stringify({
        compilerOptions: { paths: { '~app/*': ['./src/*'], '~root/*': ['./*'] } },
      }),
      'src/contexts/user.jsx': 'export const user = 1;',
      'src/views/Home.jsx': 'export { user } from \'~root/src/contexts/user\';\n',
    },
  });

  it('impact and inspect both flag the ~root/src re-export', async () => {
    const impact = await cli(repo(spec()), ['impact']);

    expect(impact.code).toBe(0);
    expect(impact.output).toContain('no-restricted-syntax');
    expect(impact.output).toContain('Home.jsx');

    const inspect = await cli(repo(spec()), ['inspect']);

    expect(inspect.code).toBe(1);
    expect(inspect.output).toContain('selfonly-reexport');
  });

  it('rules prints the offset selectors a fold would copy', async () => {
    const json = await cli(repo(spec()), ['rules', '--json']);

    const parsed = JSON.parse(json.output) as {
      bans: { layer: string; selfOnly: { selectors: string[] }[] }[];
    };

    const selectors = parsed.bans
      .find((entry) => entry.layer === 'views')?.selfOnly[0]?.selectors ?? [];

    expect(selectors.some((selector) => selector.includes('~root\\u002Fsrc\\u002Fcontexts'))).toBe(true);
  });
});

describe('locked debt stays green under the baseline ratchet (field issue #10)', () => {
  it('inspect --baseline suppresses locked debt — the live-verified repro', async () => {
    const dir = repo({ packageJson: react() });

    await cli(dir, ['init', '--no-install']);
    write(dir, 'blueprint.config.mjs', configSource(reactPreset({ name: 'fixture' })));

    // The field repro: create debt, lock it, then run the gate line.
    write(dir, 'src/random/x.ts', 'export const x = 1;'); // undeclared folder → error

    expect((await cli(dir, ['inspect'])).code).toBe(1);
    expect((await cli(dir, ['inspect', '--update-baseline'])).code).toBe(0);

    const gate = await cli(dir, ['inspect', '--baseline']);

    // Plain inspect stays red forever on debt the tool itself told the adopter
    // to lock; --baseline is the one uniform gate line that treats a missing
    // ledger as empty and locked debt as suppressed.
    expect(gate.code).toBe(0);
    expect(gate.output).toContain('1 baselined finding(s) suppressed');
  });
});
