import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { runRemove } from './remove';

let root: string;
let lines: string[];

beforeEach(() => {
  root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'bp-remove-legacy-')));
  lines = [];
});

afterEach(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

function write(rel: string, content: string): void {
  fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true });
  fs.writeFileSync(path.join(root, rel), content);
}

const read = (rel: string) => fs.readFileSync(path.join(root, rel), 'utf-8');
const exists = (rel: string) => fs.existsSync(path.join(root, rel));

const SECTION = '<!-- BLUEPRINT:START -->\n## Architecture contract (generated from blueprint)\n'
  + '<!-- BLUEPRINT:END -->\n';

const BACKUP = `blueprint.config.mjs.pre-v4-${'c'.repeat(64)}`;

function adoptBeforeLifecycle(): void {
  write('package.json', JSON.stringify({
    scripts: { lint: 'eslint src' },
    devDependencies: { '@kekkai/blueprint': '4.0.0', eslint: '^9', 'typescript-eslint': '^8' },
  }));

  write('node_modules/@kekkai/blueprint/package.json', JSON.stringify({
    name: '@kekkai/blueprint', version: '4.0.0',
  }));

  write('blueprint.config.mjs', 'export default {};\n');
  write(BACKUP, 'export default {};\n');
  write('.blueprint-baseline.json', '[]');

  write(
    'eslint.config.mjs',
    '// Generated by @kekkai/blueprint init — regenerated on every init.\nexport default [];\n',
  );

  write(
    'docs/architecture-handbook.md',
    '# x\n\n> Generated from `blueprint.config` by `@kekkai/blueprint` — edit the blueprint, '
    + 'not this file.\n',
  );

  write('docs/decisions.md', '# Ours\n');
  write('CLAUDE.md', SECTION);
  write('AGENTS.md', `# House rules\n\nBe kind.\n\n${SECTION}`);
  write('AGENTS.blueprint.md', SECTION);
  write('.cursor/rules/blueprint.mdc', '---\n---\n');

  write(
    '.gitignore',
    'node_modules\n\n# @kekkai/blueprint artifacts — the agent contract links to these; '
    + 'keep them tracked\n!docs/architecture-handbook.md\n',
  );

  write('tsconfig.json', '{ "compilerOptions": { "paths": { "~app/*": ["./src/*"] } } }\n');
  write('src/pages/.gitkeep', '');
}

describe('runRemove · pre-lifecycle adoption', () => {
  it('removes provable artifacts and reports what it cannot prove', async () => {
    adoptBeforeLifecycle();

    const commands: string[] = [];

    expect(await runRemove(root, {
      log: (line) => void lines.push(line),
      loadConfig: async () => ({
        framework: 'react',
        architecture: { alias: '~app', layers: [{ name: 'pages', does: 'x' }] },
      }),
      exec: (command) => {
        commands.push(command);

        write('package.json', JSON.stringify({
          scripts: { lint: 'eslint src' },
          devDependencies: { eslint: '^9', 'typescript-eslint': '^8' },
        }));
      },
    })).toBe(0);

    for (const file of [
      'blueprint.config.mjs', BACKUP, '.blueprint-baseline.json', 'eslint.config.mjs',
      'docs/architecture-handbook.md', 'CLAUDE.md', 'AGENTS.blueprint.md', '.cursor',
    ]) {
      expect(exists(file), file).toBe(false);
    }

    expect(read('AGENTS.md')).toBe('# House rules\n\nBe kind.\n');
    expect(read('docs/decisions.md')).toBe('# Ours\n');
    expect(read('.gitignore')).toBe('node_modules\n');
    expect(read('tsconfig.json')).toContain('~app/*');
    expect(exists('src/pages/.gitkeep')).toBe(true);
    expect(commands).toEqual(['npm uninstall @kekkai/blueprint']);

    const output = lines.join('\n');

    for (const text of [
      'Ownership evidence: no lifecycle records, so only name- or content-proven Blueprint '
      + 'artifacts are removed',
      '· tsconfig.json: may still carry Blueprint\'s import-alias wiring; it predates lifecycle '
      + 'records',
      '· package.json: may still carry Blueprint\'s eslint leg in the lint script',
      '· eslint in .: Blueprint may have installed it, but no record proves that',
      '− rewrite .gitignore (removes Blueprint\'s marked ignore exceptions)',
      '− delete .blueprint-baseline.json (Blueprint inspect baseline)',
      '− delete ' + BACKUP + ' (Blueprint 3.2 config backup)',
    ]) {
      expect(output).toContain(text);
    }
  });

  it('reports partial lifecycle records the same way and keeps a changed created '
    + 'file', async () => {
    adoptBeforeLifecycle();
    write('jsconfig.json', '{"compilerOptions":{"paths":{"~app/*":["./src/*"]}},"extra":true}\n');

    write('.blueprint-lifecycle.json', JSON.stringify({
      schema: 1, blueprint: '4.1.0', provenance: 'partial', operations: [], pending: null,
      applications: {
        '.': { provenance: [{ kind: 'created', path: 'jsconfig.json', sha256: 'old' }] },
      },
    }));

    expect(await runRemove(root, {
      log: (line) => void lines.push(line),
      dryRun: true,
      loadConfig: async () => ({
        framework: 'react',
        architecture: { alias: '~app', layers: [{ name: 'pages', does: 'x' }] },
      }),
    })).toBe(0);

    const output = lines.join('\n');

    expect(output).toContain('Ownership evidence: lifecycle records started after adoption');
    expect(output).toContain('· jsconfig.json: Blueprint created it, but it changed since');
    expect(output).not.toContain('· jsconfig.json: may still carry');
  });
});
