import fs from 'node:fs';
import path from 'node:path';

import type { Framework } from '../config';
import { directoriesToBoundary, resolveProjectContext, sameFilesystemPath } from './context';
import { REQUIRED_DEPS, STACK_DEPS } from './install';
import type { ProjectState } from './types';

export const CONFIG_FILE = 'blueprint.config.mjs';

export const GENERATED_ESLINT_BANNER
  = '// Generated by @kekkai/blueprint init — regenerated on every init.';

export const AUTHORING_FILE = 'blueprint-authoring.md';
export const COMMAND_FILE = '.claude/commands/blueprint-author.md';

export const ESLINT_FILES = [
  'eslint.config.js',
  'eslint.config.mjs',
  'eslint.config.cjs',
  'eslint.config.ts',
];

const LEGACY_ESLINT_FILES = [
  '.eslintrc.js',
  '.eslintrc.cjs',
  '.eslintrc.json',
  '.eslintrc.yml',
  '.eslintrc.yaml',
  '.eslintrc',
];

const TSCONFIG_FILES = ['tsconfig.json', 'tsconfig.app.json', 'jsconfig.json'];

export const VITE_FILES = [
  'vite.config.js',
  'vite.config.ts',
  'vite.config.mjs',
  'vite.config.mts',
];

function readViteConfig(
  root: string,
  file: string | undefined,
): { file: string; text: string } | undefined {
  if (file === undefined) {
    return undefined;
  }

  const text = readText(path.join(root, file));

  return text === null ? undefined : { file, text };
}

export function readText(file: string): string | null {
  try {
    return fs.readFileSync(file, 'utf-8');
  } catch {
    return null;
  }
}

export function readTexts(root: string, paths: string[]): Record<string, string | null> {
  return Object.fromEntries(paths.map((file) => [file, readText(path.join(root, file))]));
}

function detectFramework(deps: string[]): Framework | null {
  const hasVue = deps.includes('vue');
  const hasReact = deps.includes('react');

  if (hasVue === hasReact) {
    return null;
  }

  return hasVue ? 'vue' : 'react';
}

function detectNext(
  root: string,
  hasNext: boolean,
): { nextRouter: 'app' | 'pages' | 'both' | null; nextSrcDir: boolean } {
  if (!hasNext) {
    return { nextRouter: null, nextSrcDir: false };
  }

  const has = (rel: string) => fs.existsSync(path.join(root, rel));
  const app = has('src/app') || has('app');
  const pages = has('src/pages') || has('pages');

  return {
    nextRouter: app && pages ? 'both' : app ? 'app' : pages ? 'pages' : null,
    nextSrcDir: has('src/app') || has('src/pages'),
  };
}

export function listSourceDirs(root: string, sourceRoot = 'src'): string[] {
  try {
    return fs
      .readdirSync(path.join(root, sourceRoot), { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name);
  } catch {
    return [];
  }
}

function detectEslint(root: string, boundary: string): {
  file: string | undefined;
  configRoot: string | undefined;
  basePath: string | undefined;
  shadowed: string | undefined;
  owned: string | undefined;
  wired: boolean;
  legacy: string | undefined;
  shape: ProjectState['eslintConfigShape'];
} {
  const directories = directoriesToBoundary(root, boundary);
  const flatConfigs = findEslintConfigs(directories, ESLINT_FILES);
  const shadowed = generatedLocalShadow(root, flatConfigs);
  const flat = shadowed === undefined ? flatConfigs[0] : flatConfigs[1];

  const legacyConfig = flat === undefined
    ? findEslintConfig(directories, LEGACY_ESLINT_FILES)
    : undefined;

  const owner = flat ?? legacyConfig;
  const file = relativeConfigPath(root, flat);
  const legacy = relativeConfigPath(root, legacyConfig);
  const ownerRoot = owner?.root;
  const basePath = ownerRoot === undefined ? undefined : relativeProjectPath(ownerRoot, root);
  const owned = ownedConfig(root, flat);

  return {
    file,
    configRoot: ownerRoot,
    basePath: basePath === '.' ? undefined : basePath,
    shadowed,
    owned,
    wired: owned === undefined && wiredConfig(flat?.text, basePath),
    legacy,
    shape: configShape(flat?.text, flat !== undefined, legacyConfig !== undefined),
  };
}

interface EslintConfig {
  root: string;
  file: string;
  text: string | null;
}

function findEslintConfig(directories: string[], files: string[]): EslintConfig | undefined {
  return findEslintConfigs(directories, files)[0];
}

function findEslintConfigs(directories: string[], files: string[]): EslintConfig[] {
  const configs: EslintConfig[] = [];

  for (const root of directories) {
    const file = files.find((candidate) => fs.existsSync(path.join(root, candidate)));

    if (file !== undefined) {
      configs.push({ root, file, text: readText(path.join(root, file)) });
    }
  }

  return configs;
}

function generatedLocalShadow(root: string, configs: EslintConfig[]): string | undefined {
  const [local, ancestor] = configs;

  // Stryker disable next-line ConditionalExpression: an ancestor requires a first array entry
  return local !== undefined
    && ancestor !== undefined
    && sameFilesystemPath(local.root, root)
    && local.text?.startsWith(GENERATED_ESLINT_BANNER)
    ? local.file
    : undefined;
}

function relativeConfigPath(root: string, config?: EslintConfig): string | undefined {
  return config === undefined
    ? undefined
    : relativeProjectPath(root, path.join(config.root, config.file));
}

function ownedConfig(root: string, config?: EslintConfig): string | undefined {
  return config !== undefined
    && sameFilesystemPath(config.root, root)
    && config.text?.startsWith(GENERATED_ESLINT_BANNER)
    ? config.file
    : undefined;
}

function wiredConfig(text: string | null | undefined, basePath?: string): boolean {
  if (text === null || text === undefined || !text.includes('@kekkai/blueprint')) {
    return false;
  }

  // Stryker disable next-line ConditionalExpression: absent owners cannot be wired by text
  return basePath === undefined || basePath === '.' || scopedWiring(text, basePath);
}

function scopedWiring(text: string, basePath: string): boolean {
  const escaped = basePath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const origin = `new URL\\(\\s*['"\`]\\.?/?${escaped}/['"\`]`;

  if (new RegExp(`basePath:[^,;}\\n]*${origin}`).test(text)) {
    return true;
  }

  return [...text.matchAll(/basePath:\s*([A-Za-z_$][\w$]*)/g)].some((match) =>
    new RegExp(`(?:const|let|var)\\s+${match[1]}\\s*=[^;]*${origin}`).test(text));
}

function configShape(
  text: string | null | undefined,
  flat: boolean,
  legacy: boolean,
): ProjectState['eslintConfigShape'] {
  return legacy
    ? 'legacy'
    : text?.includes('tseslint.config(')
      ? 'tseslint'
      : flat ? 'flat-array' : undefined;
}

function relativeProjectPath(from: string, to: string): string {
  return path.relative(from, to).split(path.sep).join('/') || '.';
}

export function detect(root: string): ProjectState {
  const context = resolveProjectContext(root);
  const deps = context.localPackage.dependencies;

  const framework = detectFramework(deps);
  const hasTypescript = context.hasTypescript;
  const hasNext = deps.includes('next');
  const hasNuxt = deps.includes('nuxt');
  const { nextRouter, nextSrcDir } = detectNext(root, hasNext);

  const required = [
    ...REQUIRED_DEPS,
    ...(framework === 'vue' ? [STACK_DEPS.vue] : []),
    ...(hasTypescript ? [STACK_DEPS.typescript] : []),
  ];

  const eslint = detectEslint(root, context.repositoryRoot ?? context.toolchainRoot);
  const viteFile = VITE_FILES.find((file) => fs.existsSync(path.join(root, file)));
  const viteConfig = readViteConfig(root, viteFile);

  const availableDependencies = new Set([
    ...deps,
    ...context.toolchainPackage.dependencies,
  ]);

  return {
    root,
    applicationRoot: context.applicationRoot,
    repositoryRoot: context.repositoryRoot,
    toolchainRoot: context.toolchainRoot,
    localPackage: context.localPackage,
    toolchainPackage: context.toolchainPackage,
    framework,
    packageManager: context.packageManager,
    projectName: context.localPackage.name,
    hasConfig: fs.existsSync(path.join(root, CONFIG_FILE)),
    hasEslintConfig: eslint.file !== undefined,
    eslintConfigFile: eslint.file,
    eslintConfigRoot: eslint.configRoot,
    eslintBasePath: eslint.basePath,
    shadowedEslintConfig: eslint.shadowed,
    hasNext,
    hasNuxt,
    nextRouter,
    nextSrcDir,
    ownedEslintConfig: eslint.owned,
    wiredEslintConfig: eslint.wired,
    legacyEslintConfig: eslint.legacy,
    eslintConfigShape: eslint.shape,
    viteConfig,

    hasViteConfig: viteFile !== undefined,
    hasTypescript,
    tsconfigs: readTexts(root, TSCONFIG_FILES),
    existingSrcDirs: listSourceDirs(root),
    missingDeps: required.filter((dep) => !availableDependencies.has(dep)),
    dependencies: deps,
  };
}

export function quotedIn(text: string, name: string): boolean {
  return new RegExp(
    `['"\`]${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}['"\`]`,
  ).test(text);
}

export interface ClaudeDirState {

  hadDir: boolean;

  otherCommands: number;
}

export function claudeDirState(root: string): ClaudeDirState {
  const dir = path.join(root, '.claude');
  const commands = path.join(dir, 'commands');
  const own = path.basename(COMMAND_FILE);

  return {
    hadDir: fs.existsSync(dir),
    otherCommands: readDir(commands).filter((entry) => entry !== own).length,
  };
}

function readDir(dir: string): string[] {
  try {
    return fs.readdirSync(dir);
  } catch {
    return [];
  }
}
