import fs from 'node:fs';
import path from 'node:path';

import type { Framework } from '../config';
import type { PackageManager, ProjectState } from './types';

export const CONFIG_FILE = 'blueprint.config.mjs';

/**
 * First line of every eslint config init generates. Its presence marks the
 * file as blueprint-owned, so a re-run regenerates it in place instead of
 * mistaking its own output for a hand-maintained config.
 */
export const GENERATED_ESLINT_BANNER
  = '// Generated by @kekkai/blueprint init — regenerated on every init.';

const ESLINT_FILES = [
  'eslint.config.js',
  'eslint.config.mjs',
  'eslint.config.cjs',
  'eslint.config.ts',
];

const LEGACY_ESLINT_FILES = [
  '.eslintrc.js',
  '.eslintrc.cjs',
  '.eslintrc.json',
  '.eslintrc.yml',
  '.eslintrc.yaml',
  '.eslintrc',
];

const TSCONFIG_FILES = ['tsconfig.json', 'tsconfig.app.json', 'jsconfig.json'];

const VITE_FILES = ['vite.config.js', 'vite.config.ts', 'vite.config.mjs', 'vite.config.mts'];

const REQUIRED_DEPS = [
  'eslint',
  '@kekkai/blueprint',
  '@eslint-community/eslint-plugin-eslint-comments',
];

function readJson(file: string): Record<string, unknown> | null {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf-8'));
  } catch {
    return null;
  }
}

function readText(file: string): string | null {
  try {
    return fs.readFileSync(file, 'utf-8');
  } catch {
    return null;
  }
}

/** Read a set of project-relative files; each value is the content, or null if absent. */
export function readTexts(root: string, paths: string[]): Record<string, string | null> {
  return Object.fromEntries(paths.map((file) => [file, readText(path.join(root, file))]));
}

function detectFramework(deps: Record<string, unknown>): Framework | null {
  const hasVue = 'vue' in deps;
  const hasReact = 'react' in deps;

  if (hasVue === hasReact) return null; // both or neither → ambiguous

  return hasVue ? 'vue' : 'react';
}

/**
 * Walk from `root` upward until a package-manager marker is found. In a
 * workspace (pnpm / turbo monorepo) the lockfile lives at the workspace
 * root, not in the package being initialized — looking only at the cwd
 * would misdetect npm and generate the wrong install commands.
 */
function detectPackageManager(root: string): PackageManager {
  let dir = path.resolve(root);

  for (;;) {
    if (
      fs.existsSync(path.join(dir, 'pnpm-lock.yaml'))
      || fs.existsSync(path.join(dir, 'pnpm-workspace.yaml'))
    ) {
      return 'pnpm';
    }

    if (fs.existsSync(path.join(dir, 'yarn.lock'))) return 'yarn';
    if (fs.existsSync(path.join(dir, 'package-lock.json'))) return 'npm';

    const parent = path.dirname(dir);

    if (parent === dir) return 'npm';

    dir = parent;
  }
}

/**
 * Detect the Next.js route tree: which router (`app` / `pages` / both, for a
 * migration) and whether it sits under `src/`. Drives the Next preset shape
 * so a fresh `create-next-app` adopts in one command.
 */
function detectNext(
  root: string,
  hasNext: boolean,
): { nextRouter: 'app' | 'pages' | 'both' | null; nextSrcDir: boolean } {
  if (!hasNext) return { nextRouter: null, nextSrcDir: false };

  const has = (rel: string) => fs.existsSync(path.join(root, rel));
  const app = has('src/app') || has('app');
  const pages = has('src/pages') || has('pages');

  return {
    nextRouter: app && pages ? 'both' : app ? 'app' : pages ? 'pages' : null,
    nextSrcDir: has('src/app') || has('src/pages'),
  };
}

function listSrcDirs(root: string): string[] {
  try {
    return fs
      .readdirSync(path.join(root, 'src'), { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name);
  } catch {
    return [];
  }
}

/** Read the target project into a {@link ProjectState}. */
export function detect(root: string): ProjectState {
  const pkg = readJson(path.join(root, 'package.json')) ?? {};

  const deps = {
    ...((pkg.dependencies as Record<string, unknown>) ?? {}),
    ...((pkg.devDependencies as Record<string, unknown>) ?? {}),
  };

  const framework = detectFramework(deps);
  const hasTypescript = 'typescript' in deps;
  const hasNext = 'next' in deps;
  const hasNuxt = 'nuxt' in deps;
  const { nextRouter, nextSrcDir } = detectNext(root, hasNext);

  // The generated eslint config wires parsers for the detected stack — the
  // packages backing them join the install set.
  const required = [
    ...REQUIRED_DEPS,
    ...(framework === 'vue' ? ['vue-eslint-parser'] : []),
    ...(hasTypescript ? ['typescript-eslint'] : []),
  ];

  const eslintFile = ESLINT_FILES.find((file) => fs.existsSync(path.join(root, file)));
  const eslintText = eslintFile === undefined ? null : readText(path.join(root, eslintFile));

  const ownedEslintConfig = eslintText?.startsWith(GENERATED_ESLINT_BANNER)
    ? eslintFile
    : undefined;

  // A hand-maintained config that already imports the package has been wired
  // by its owner — emitting a reference next to it would be nagging.
  const wiredEslintConfig
    = ownedEslintConfig === undefined && (eslintText?.includes('@kekkai/blueprint') ?? false);

  // A legacy `.eslintrc*` is NOT a flat config — writing a fresh
  // `eslint.config.mjs` next to it produces two configs / two ledgers. Detect
  // it so the merge instruction routes to the flat-config migration instead.
  const legacyEslintConfig = eslintFile === undefined
    ? LEGACY_ESLINT_FILES.find((file) => fs.existsSync(path.join(root, file)))
    : undefined;

  // The existing config's shape, so the merge instruction can be specific
  // rather than a generic snippet the user must adapt.
  const eslintConfigShape = legacyEslintConfig
    ? 'legacy'
    : eslintText?.includes('tseslint.config(')
      ? 'tseslint'
      : eslintFile !== undefined
        ? 'flat-array'
        : undefined;

  const viteFile = VITE_FILES.find((file) => fs.existsSync(path.join(root, file)));
  const viteText = viteFile === undefined ? null : readText(path.join(root, viteFile));

  return {
    root,
    framework,
    packageManager: detectPackageManager(root),
    projectName: typeof pkg.name === 'string' ? pkg.name : undefined,
    hasConfig: fs.existsSync(path.join(root, CONFIG_FILE)),
    hasEslintConfig: eslintFile !== undefined,
    hasNext,
    hasNuxt,
    nextRouter,
    nextSrcDir,
    ownedEslintConfig,
    wiredEslintConfig,
    legacyEslintConfig,
    eslintConfigShape,
    viteConfig: viteFile !== undefined && viteText !== null
      ? { file: viteFile, text: viteText }
      : undefined,
    hasViteConfig: viteFile !== undefined,
    hasTypescript,
    tsconfigs: readTexts(root, TSCONFIG_FILES),
    existingSrcDirs: listSrcDirs(root),
    missingDeps: required.filter((dep) => !(dep in deps)),
  };
}

/**
 * Copy a string literal verbatim (honoring escapes) from `text[i]` into
 * `out`, returning the index after the closing quote. Both JSONC passes
 * need this: a tsconfig's own data contains `/*` (every `"@/*"` paths key),
 * so nothing may be stripped inside a string.
 */
function copyString(text: string, i: number, out: string[]): number {
  out.push(text[i]);
  i++;

  while (i < text.length && text[i] !== '"') {
    out.push(text[i]);

    if (text[i] === '\\' && i + 1 < text.length) {
      out.push(text[i + 1]);
      i++;
    }

    i++;
  }

  if (i < text.length) out.push(text[i]);

  return i + 1;
}

/**
 * Tolerant JSONC parse for the tsconfig family: strips line and block
 * comments plus trailing commas — outside string literals only — then
 * `JSON.parse`. Vite + TS starters ship tsconfigs *with comments* by
 * default, so treating JSONC as unreadable would false-red the doctor's
 * alias check on the mainstream path. Returns null when the text still is
 * not JSON after stripping.
 */
export function parseJsonc(text: string): unknown {
  const stripped: string[] = [];

  for (let i = 0; i < text.length;) {
    if (text[i] === '"') {
      i = copyString(text, i, stripped);
    } else if (text[i] === '/' && text[i + 1] === '/') {
      while (i < text.length && text[i] !== '\n') i++;
    } else if (text[i] === '/' && text[i + 1] === '*') {
      i += 2;

      while (i < text.length && !(text[i] === '*' && text[i + 1] === '/')) i++;

      i += 2;
    } else {
      stripped.push(text[i]);
      i++;
    }
  }

  // Second pass, comment-free: drop a comma whose next non-space is `}`/`]`.
  const clean: string[] = [];
  const commentFree = stripped.join('');

  for (let i = 0; i < commentFree.length;) {
    if (commentFree[i] === '"') {
      i = copyString(commentFree, i, clean);
    } else if (commentFree[i] === ',') {
      let next = i + 1;

      while (next < commentFree.length && /\s/.test(commentFree[next])) next++;

      if (commentFree[next] !== '}' && commentFree[next] !== ']') clean.push(',');

      i++;
    } else {
      clean.push(commentFree[i]);
      i++;
    }
  }

  try {
    return JSON.parse(clean.join(''));
  } catch {
    return null; // Still broken after stripping — the --alias flag covers this honestly.
  }
}

/** Visit every `compilerOptions.paths` entry across the given tsconfig texts. */
function eachPathAlias(
  tsconfigs: Record<string, string | null>,
  visit: (alias: string, dir: string | null) => void,
): void {
  for (const text of Object.values(tsconfigs)) {
    if (text == null) continue;

    const parsed = parseJsonc(text);

    if (parsed == null) continue;

    const options = (parsed as { compilerOptions?: { paths?: unknown } })?.compilerOptions;
    const paths = options?.paths;

    if (typeof paths !== 'object' || paths === null) continue;

    for (const [key, targets] of Object.entries(paths)) {
      const alias = key.replace(/\/\*$/, '');

      if (!alias) continue;

      const target = Array.isArray(targets) && typeof targets[0] === 'string' ? targets[0] : null;

      visit(alias, target?.replace(/^\.\//, '').replace(/\/\*$/, '') ?? null);
    }
  }
}

/** Aliases in tsconfig/jsconfig `paths` that map onto `src/`, e.g. `@/* → ./src/*`. */
export function detectAliases(tsconfigs: Record<string, string | null>): Record<string, string> {
  const found: Record<string, string> = {};

  eachPathAlias(tsconfigs, (alias, dir) => {
    if (dir === 'src' && !(alias in found)) found[alias] = 'src';
  });

  return found;
}

/** Every alias declared in `paths`, whatever its target — "can TS resolve this prefix?". */
export function pathAliasKeys(tsconfigs: Record<string, string | null>): Set<string> {
  const keys = new Set<string>();

  eachPathAlias(tsconfigs, (alias) => keys.add(alias));

  return keys;
}

/**
 * Whether a JS config's text carries `name` as a quoted token (`'@': …`,
 * `find: '@'`, `.set('@', …)`). The shared wiredness standard for bundler
 * configs: doctor's alias check and init's alias instructs must agree, or
 * init nags about wiring doctor already accepts. A bare substring test would
 * be vacuous for short aliases — `'@'` is inside every `'@vitejs/plugin-…'`.
 */
export function quotedIn(text: string, name: string): boolean {
  return new RegExp(
    `['"\`]${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}['"\`]`,
  ).test(text);
}
