import fs from 'node:fs';
import path from 'node:path';

import type { Framework } from '../config';
import type { PackageManager, ProjectState } from './types';

export const CONFIG_FILE = 'blueprint.config.mjs';

/**
 * First line of every eslint config init generates. Its presence marks the
 * file as blueprint-owned, so a re-run regenerates it in place instead of
 * mistaking its own output for a hand-maintained config.
 */
export const GENERATED_ESLINT_BANNER
  = '// Generated by @kekkai/blueprint init — regenerated on every init.';

/**
 * The authoring artifacts `init --authoring` writes and the playbook's final
 * step deletes. They live here (not in bootstrap) because doctor — a lower
 * layer — treats them as leftovers: adoption is not done mid-ceremony.
 */
export const AUTHORING_FILE = 'blueprint-authoring.md';
export const COMMAND_FILE = '.claude/commands/blueprint-author.md';

const ESLINT_FILES = [
  'eslint.config.js',
  'eslint.config.mjs',
  'eslint.config.cjs',
  'eslint.config.ts',
];

// The tells that an eslint config reaches the emitted rules. Both, because
// neither covers the other: a config reaching `emitLint` through a shared
// config package (a monorepo's `@acme/eslint-config` re-exporting it) never
// names this package, and one that renames the import on the way in
// (`import { emitLint as lint }`) never spells the call.
const ESLINT_WIRED_TOKENS = ['emitLint(', '@kekkai/blueprint'];

const LEGACY_ESLINT_FILES = [
  '.eslintrc.js',
  '.eslintrc.cjs',
  '.eslintrc.json',
  '.eslintrc.yml',
  '.eslintrc.yaml',
  '.eslintrc',
];

const TSCONFIG_FILES = ['tsconfig.json', 'tsconfig.app.json', 'jsconfig.json'];

const VITE_FILES = ['vite.config.js', 'vite.config.ts', 'vite.config.mjs', 'vite.config.mts'];

/**
 * The ESLint majors an adopting project may be on. Every package in
 * {@link REQUIRED_DEPS} must declare a peer range admitting all of them:
 * `npm install` resolves the whole list or none of it, so one package that
 * caps below the project's ESLint fails the entire install — and `init` is
 * left with a half-applied plan (field issue #37).
 */
export const SUPPORTED_ESLINT_MAJORS = [9, 10];

export const REQUIRED_DEPS = [
  'eslint',
  '@kekkai/blueprint',
  '@eslint-community/eslint-plugin-eslint-comments',
  // Carriers the generated config injects — the adopter's deps, not blueprint's.
  // import-x over import: the eslint peer cap (field issue #37) and the resolver
  // peer that broke installs (field issue #41).
  '@stylistic/eslint-plugin',
  'eslint-plugin-import-x',
];

/** Carriers added only when the detected stack needs their parser. */
export const STACK_DEPS = {
  vue: 'vue-eslint-parser',
  typescript: 'typescript-eslint',
} as const;

/**
 * Non-`eslint` peers a carrier is allowed to declare, by package. A peer on
 * something the ADOPTER owns is a version constraint blueprint imposes on
 * their repo from the outside — npm enforces it whenever the package is
 * present, and no nested copy can satisfy it, so the install fails as a whole
 * (field issue #41). `typescript-eslint` ↔ `typescript` is inherent and wide;
 * anything new belongs in a review, not in someone's adoption.
 */
export const ALLOWED_CARRIER_PEERS: Record<string, string[]> = {
  'typescript-eslint': ['typescript'],
  // The resolver stack, and with it the whole-graph rules a resolver-free plugin
  // cannot express. Held by the conformance stack fixtures, not by the argument:
  // if one fails to install, this entry is wrong and the carrier choice reopens.
  'eslint-plugin-import-x': ['@typescript-eslint/utils', 'eslint-import-resolver-node'],
};

function readJson(file: string): Record<string, unknown> | null {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf-8'));
  } catch {
    // Undecidable: an empty catch returns `undefined`, and every caller reads both as
    // "no readable JSON". Making the difference visible would mean a caller that
    // cares which flavour of absent it got, which is worse code than this note.
    return null;
  }
}

/** The vite config's text, when there is one and it can be read. */
function readViteConfig(
  root: string,
  file: string | undefined,
): { file: string; text: string } | undefined {
  if (file === undefined) {
    return undefined;
  }

  const text = readText(path.join(root, file));

  return text === null ? undefined : { file, text };
}

function readText(file: string): string | null {
  try {
    return fs.readFileSync(file, 'utf-8');
  } catch {
    return null;
  }
}

/** Read a set of project-relative files; each value is the content, or null if absent. */
export function readTexts(root: string, paths: string[]): Record<string, string | null> {
  return Object.fromEntries(paths.map((file) => [file, readText(path.join(root, file))]));
}

function detectFramework(deps: Record<string, unknown>): Framework | null {
  const hasVue = 'vue' in deps;
  const hasReact = 'react' in deps;

  // both or neither → ambiguous
  if (hasVue === hasReact) {
    return null;
  }

  return hasVue ? 'vue' : 'react';
}

/** Walk upward to the package-manager marker — in a workspace it is above `root`. */
function detectPackageManager(root: string): PackageManager {
  let dir = path.resolve(root);

  for (;;) {
    if (
      fs.existsSync(path.join(dir, 'pnpm-lock.yaml'))
      || fs.existsSync(path.join(dir, 'pnpm-workspace.yaml'))
    ) {
      return 'pnpm';
    }

    if (fs.existsSync(path.join(dir, 'yarn.lock'))) {
      return 'yarn';
    }

    if (fs.existsSync(path.join(dir, 'package-lock.json'))) {
      return 'npm';
    }

    const parent = path.dirname(dir);

    if (parent === dir) {
      return 'npm';
    }

    dir = parent;
  }
}

/** The Next route tree — which router, and whether it sits under `src/`. */
function detectNext(
  root: string,
  hasNext: boolean,
): { nextRouter: 'app' | 'pages' | 'both' | null; nextSrcDir: boolean } {
  if (!hasNext) {
    return { nextRouter: null, nextSrcDir: false };
  }

  const has = (rel: string) => fs.existsSync(path.join(root, rel));
  const app = has('src/app') || has('app');
  const pages = has('src/pages') || has('pages');

  return {
    nextRouter: app && pages ? 'both' : app ? 'app' : pages ? 'pages' : null,
    nextSrcDir: has('src/app') || has('src/pages'),
  };
}

function listSrcDirs(root: string): string[] {
  try {
    return fs
      .readdirSync(path.join(root, 'src'), { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name);
  } catch {
    return [];
  }
}

/** Read the target project into a {@link ProjectState}. */
export function detect(root: string): ProjectState {
  const pkg = readJson(path.join(root, 'package.json')) ?? {};

  const deps = {
    ...((pkg.dependencies as Record<string, unknown>) ?? {}),
    ...((pkg.devDependencies as Record<string, unknown>) ?? {}),
  };

  const framework = detectFramework(deps);
  const hasTypescript = 'typescript' in deps;
  const hasNext = 'next' in deps;
  const hasNuxt = 'nuxt' in deps;
  const { nextRouter, nextSrcDir } = detectNext(root, hasNext);

  // The generated eslint config wires parsers for the detected stack — the
  // packages backing them join the install set.
  const required = [
    ...REQUIRED_DEPS,
    ...(framework === 'vue' ? [STACK_DEPS.vue] : []),
    ...(hasTypescript ? [STACK_DEPS.typescript] : []),
  ];

  const eslintFile = ESLINT_FILES.find((file) => fs.existsSync(path.join(root, file)));
  const eslintText = eslintFile === undefined ? null : readText(path.join(root, eslintFile));

  const ownedEslintConfig = eslintText?.startsWith(GENERATED_ESLINT_BANNER)
    ? eslintFile
    : undefined;

  // A hand-maintained config carrying either tell has been wired by its owner
  // — emitting a reference next to it would be nagging. Text only, comments
  // included: the "emitted rules survive the merged eslint config" check is
  // what proves the rules are alive in the config eslint actually resolves.
  const wiredEslintConfig
    = ownedEslintConfig === undefined
      && ESLINT_WIRED_TOKENS.some((token) => eslintText?.includes(token) ?? false);

  // A legacy `.eslintrc*` is NOT a flat config — writing a fresh
  // `eslint.config.mjs` next to it produces two configs / two ledgers. Detect
  // it so the merge instruction routes to the flat-config migration instead.
  const legacyEslintConfig = eslintFile === undefined
    ? LEGACY_ESLINT_FILES.find((file) => fs.existsSync(path.join(root, file)))
    : undefined;

  // The existing config's shape, so the merge instruction can be specific
  // rather than a generic snippet the user must adapt.
  const eslintConfigShape = legacyEslintConfig
    ? 'legacy'
    : eslintText?.includes('tseslint.config(')
      ? 'tseslint'
      : eslintFile !== undefined
        ? 'flat-array'
        : undefined;

  const viteFile = VITE_FILES.find((file) => fs.existsSync(path.join(root, file)));
  const viteConfig = readViteConfig(root, viteFile);

  return {
    root,
    framework,
    packageManager: detectPackageManager(root),
    projectName: typeof pkg.name === 'string' ? pkg.name : undefined,
    hasConfig: fs.existsSync(path.join(root, CONFIG_FILE)),
    hasEslintConfig: eslintFile !== undefined,
    eslintConfigFile: eslintFile,
    hasNext,
    hasNuxt,
    nextRouter,
    nextSrcDir,
    ownedEslintConfig,
    wiredEslintConfig,
    legacyEslintConfig,
    eslintConfigShape,
    viteConfig,
    // Separate on purpose: `hasViteConfig` is "a vite config is there", and an
    // unreadable one is still there. `viteConfig` is "and this is what it says".
    hasViteConfig: viteFile !== undefined,
    hasTypescript,
    tsconfigs: readTexts(root, TSCONFIG_FILES),
    existingSrcDirs: listSrcDirs(root),
    missingDeps: required.filter((dep) => !(dep in deps)),
    dependencies: Object.keys(deps),
  };
}

/** A literal that closed, or the offset the scan gave up at — never both. */
interface ClosedString {
  closed: true;
  copied: string;
  next: number;
}

type CopiedString = ClosedString | { closed: false; stoppedAt: number };

/** Copy a literal verbatim from `text[i]` — a tsconfig's own data contains `/*`. */
function copyString(text: string, i: number): CopiedString {
  let copied = text[i];

  i++;

  while (i < text.length && text[i] !== '"') {
    copied += text[i];

    if (text[i] === '\\' && i + 1 < text.length) {
      copied += text[i + 1];
      i++;
    }

    i++;
  }

  // Ran out of text before the closing quote: report where it came to rest, which
  // is what makes every bound above answerable — a scan one character too far
  // changes the number a reader is shown.
  if (i >= text.length) {
    return { closed: false, stoppedAt: i };
  }

  return { closed: true, copied: copied + text[i], next: i + 1 };
}

/**
 * Why a JSONC document could not be read, and the character offset the scan gave
 * up at. Reported rather than folded into one null: "I cannot read your tsconfig"
 * is not something an adopter can act on — and a failure with no position leaves
 * every bound in the scanner unanswerable, since running one character too far
 * produced the same bare null.
 */
export interface JsoncFailure {
  reason: 'unterminated-string' | 'unclosed-comment' | 'not-json';
  /**
   * Character offset the scan came to rest at. Absent — not zero — for `not-json`,
   * since offset 0 is a legitimate position and would read as one.
   */
  at?: number;
}

export type JsoncResult = { ok: true; value: unknown } | ({ ok: false } & JsoncFailure);

/**
 * Tolerant JSONC parse for the tsconfig family: strips line and block comments
 * plus trailing commas — outside string literals only — then `JSON.parse`. Vite
 * + TS starters ship tsconfigs *with comments* by default, so treating JSONC as
 * unreadable would false-red the doctor's alias check on the mainstream path.
 */
export function parseJsonc(text: string): JsoncResult {
  // A STRING, not an array joined at the end: `'' + undefined` shows an overrun
  // where `[undefined].join('')` hides it, and the bounds are this scanner's whole
  // correctness argument.
  let commentFree = '';

  for (let i = 0; i < text.length;) {
    if (text[i] === '"') {
      const literal = copyString(text, i);

      if (!literal.closed) {
        return { ok: false, reason: 'unterminated-string', at: literal.stoppedAt };
      }

      commentFree += literal.copied;
      i = literal.next;
    } else if (text[i] === '/' && text[i + 1] === '/') {
      // `indexOf` answers with the position, so there is no bound to walk past.
      const newline = text.indexOf('\n', i);

      i = newline === -1 ? text.length : newline;
    } else if (text[i] === '/' && text[i + 1] === '*') {
      // From AFTER the opener, or `/*/` reads as a closed comment: the `*/` the
      // search finds would be the opener's own `*` with the next `/`.
      const close = text.indexOf('*/', i + 2);

      if (close === -1) {
        return { ok: false, reason: 'unclosed-comment', at: text.length };
      }

      i = close + 2;
    } else {
      commentFree += text[i];
      i++;
    }
  }

  // Second pass, comment-free: drop a comma whose next non-space is `}`/`]`.
  let clean = '';

  for (let i = 0; i < commentFree.length;) {
    if (commentFree[i] === '"') {
      // Proven closed by the first pass. A cast, not a check: the check would be a
      // branch no input can take, which reads as a case somebody handled.
      const literal = copyString(commentFree, i) as ClosedString;

      clean += literal.copied;
      i = literal.next;
    } else if (commentFree[i] === ',') {
      // undecidable: a hand-walked index past the end yields `undefined`, neither
      // `}` nor `]`, so overrunning keeps the comma exactly as stopping would.
      const after = /\S/.exec(commentFree.slice(i + 1));
      const nextChar = after?.[0];

      if (nextChar !== '}' && nextChar !== ']') {
        clean += ',';
      }

      i++;
    } else {
      clean += commentFree[i];
      i++;
    }
  }

  try {
    return { ok: true, value: JSON.parse(clean) };
  } catch {
    // No offset: JSON.parse's position refers to the stripped text, not the file
    // the reader has open.
    return { ok: false, reason: 'not-json' };
  }
}

/** A tsconfig the JSONC reader gave up on, named so a caller can say which. */
export interface UnreadableConfig extends JsoncFailure {
  file: string;
}

const JSONC_REASON: Record<JsoncFailure['reason'], string> = {
  'unterminated-string': 'a string literal never closes',
  'unclosed-comment': 'a block comment never closes',
  'not-json': 'it is not valid JSON once the comments are stripped',
};

/**
 * The tsconfig/jsconfig files that are present but unparseable.
 *
 * Every reader of `paths` skips these, and skipping *silently* is the trap:
 * an alias declared inside an unreadable tsconfig is invisible, so doctor tells
 * an adopter to declare what is already there, and init calls a preset's alias
 * the repo's first. Both mislead in the same direction — they blame the alias for
 * a broken file. Callers name the file and the offset instead.
 */
export function unreadableTsconfigs(
  tsconfigs: Record<string, string | null>,
): UnreadableConfig[] {
  const failures: UnreadableConfig[] = [];

  for (const [file, text] of Object.entries(tsconfigs)) {
    if (text === null) {
      continue;
    }

    const result = parseJsonc(text);

    if (!result.ok) {
      failures.push({ file, reason: result.reason, at: result.at });
    }
  }

  return failures;
}

/**
 * One clause per unreadable config: which file, what is wrong, where to look.
 * Shared so doctor and init say it the same way — the same reason `quotedIn` is
 * the one wiredness standard both of them read.
 */
export function describeUnreadable(failures: UnreadableConfig[]): string {
  return failures
    .map(({ file, reason, at }) => {
      const where = at === undefined ? '' : ` at character ${at}`;

      return `${file} could not be read (${JSONC_REASON[reason]}${where})`;
    })
    .join('; ');
}

/** Visit every `compilerOptions.paths` entry across the given tsconfig texts. */
function eachPathAlias(
  tsconfigs: Record<string, string | null>,
  visit: (alias: string, dir: string | null) => void,
): void {
  for (const text of Object.values(tsconfigs)) {
    if (text == null) {
      continue;
    }

    const result = parseJsonc(text);

    // undecidable against the `?.` below, which yields no options on a failure
    // anyway; that `?.` is separately pinned by a tsconfig whose content is `null`.
    if (!result.ok) {
      continue;
    }

    const options = (result.value as { compilerOptions?: { paths?: unknown } })?.compilerOptions;
    const paths = options?.paths;

    if (typeof paths !== 'object' || paths === null) {
      continue;
    }

    for (const [key, targets] of Object.entries(paths)) {
      const alias = key.replace(/\/\*$/, '');

      if (!alias) {
        continue;
      }

      const target = Array.isArray(targets) && typeof targets[0] === 'string' ? targets[0] : null;

      visit(alias, target?.replace(/^\.\//, '').replace(/\/\*$/, '') ?? null);
    }
  }
}

/** Aliases in tsconfig/jsconfig `paths` that map onto `src/`, e.g. `@/* → ./src/*`. */
export function detectAliases(tsconfigs: Record<string, string | null>): Record<string, string> {
  const found: Record<string, string> = {};

  eachPathAlias(tsconfigs, (alias, dir) => {
    if (dir === 'src' && !(alias in found)) {
      found[alias] = 'src';
    }
  });

  return found;
}

/** Every alias declared in `paths`, whatever its target — "can TS resolve this prefix?". */
export function pathAliasKeys(tsconfigs: Record<string, string | null>): Set<string> {
  const keys = new Set<string>();

  eachPathAlias(tsconfigs, (alias) => keys.add(alias));

  return keys;
}

/**
 * Whether a JS config's text carries `name` as a quoted token (`'@': …`,
 * `find: '@'`, `.set('@', …)`). The shared wiredness standard for bundler
 * configs: doctor's alias check and init's alias instructs must agree, or
 * init nags about wiring doctor already accepts. A bare substring test would
 * be vacuous for short aliases — `'@'` is inside every `'@vitejs/plugin-…'`.
 */
export function quotedIn(text: string, name: string): boolean {
  return new RegExp(
    `['"\`]${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}['"\`]`,
  ).test(text);
}

// Local, not shared: the twin in `bootstrap/alias.ts` sits ABOVE this module, so
// importing it would run the one-way rule backwards for a one-line predicate.
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

export interface ViteTsCoverage {
  /** `covered`: some project lists it. `outside`: projects exist, none does. */
  verdict: 'covered' | 'outside';
  /** The vite config, relative to root. */
  viteFile: string;
  /** The tsconfig that covers it, or the root one consulted when none does. */
  tsconfig: string;
}

/**
 * Whether `tsc -b` reads this repo's vite config. `null` = could not tell, never a
 * guess: the report must not claim a build verified an edit it never read.
 */
export function viteTsCoverage(root: string): ViteTsCoverage | null {
  const viteFile = VITE_FILES.find((file) => fs.existsSync(path.join(root, file)));

  // No vite config, or a JS project with no tsconfig at all: there is no
  // question to answer, and the build clause has nothing to specialise.
  if (viteFile === undefined) {
    return null;
  }

  const rootConfig = 'tsconfig.json';
  const rootText = readText(path.join(root, rootConfig));

  if (rootText === null) {
    return null;
  }

  const projects = tsProjectGraph(root, rootConfig, rootText);

  if (projects === null) {
    return null;
  }

  for (const project of projects) {
    const covers = projectCovers(project, viteFile);

    // A single undecidable project poisons the whole answer: "none of them
    // covers it" cannot be claimed while one of them is unread.
    if (covers === null) {
      return null;
    }

    if (covers) {
      return { verdict: 'covered', viteFile, tsconfig: project.file };
    }
  }

  return { verdict: 'outside', viteFile, tsconfig: rootConfig };
}

export interface ClaudeDirState {
  /** `.claude/` existed before this run, so it is the owner's whatever ends up in it. */
  hadDir: boolean;
  /** Command files in `.claude/commands/` other than the one init writes. */
  otherCommands: number;
}

/**
 * What `.claude/` looked like before this run — read before init writes anything,
 * because afterwards the tool cannot tell its own directory from the owner's.
 */
export function claudeDirState(root: string): ClaudeDirState {
  const dir = path.join(root, '.claude');
  const commands = path.join(dir, 'commands');
  const own = path.basename(COMMAND_FILE);

  return {
    hadDir: fs.existsSync(dir),
    otherCommands: readDir(commands).filter((entry) => entry !== own).length,
  };
}

/** Directory entries, or none when the directory is absent or unreadable. */
function readDir(dir: string): string[] {
  try {
    return fs.readdirSync(dir);
  } catch {
    return [];
  }
}

export interface TscArtifactLocation {
  /** The redirected build-info path, relative to root — the fact that decides it. */
  buildInfo: string;
  /** The tsconfig declaring it. */
  tsconfig: string;
}

/**
 * Where `tsc -b` keeps its build info, when every project in the graph provably
 * writes nothing into the working tree.
 *
 * The build-artifact paragraph opened on a premise about the adopter's repo — that
 * the build this playbook asked for left untracked files in their working tree, so
 * the four gitignore × version-control cells have something to decide. False on the
 * shape `npm create vite` generates for React + TS: both projects carry `noEmit:
 * true` AND `tsBuildInfoFile: ./node_modules/.tmp/…`, so the build leaves the tree
 * untouched and an agent copying the paragraph's instruction writes a statement
 * about untracked files that do not exist (field run #135). Third time this family
 * of sentences has been wrong about a tsconfig — `viteTsCoverage` is the second, and
 * the answer is the same one: measure it.
 *
 * Null unless certain, and only the certain negative changes the prose. "Something
 * landed" is the default the paragraph already assumes and is right about wherever a
 * bundle gets written, so this never has to establish it — a shape it cannot read is
 * a shape where the existing wording stands.
 *
 * `node_modules/` is the whole test for "out of the way", deliberately narrow: it is
 * ignored everywhere by convention, and deciding whether some other directory is
 * ignored needs the `.gitignore` reader that lives above this module.
 */
export function tscArtifactsOutOfTree(root: string): TscArtifactLocation | null {
  const rootConfig = 'tsconfig.json';
  const rootText = readText(path.join(root, rootConfig));

  if (rootText === null) {
    return null;
  }

  const projects = tsProjectGraph(root, rootConfig, rootText);

  if (projects === null) {
    return null;
  }

  let found: TscArtifactLocation | null = null;

  for (const project of projects) {
    // A solution config — pure `references`, no files of its own — builds nothing
    // and writes no build info, which is why the two-project vite shape leaves
    // exactly two files behind and both are the referenced projects'.
    if (isSolutionStub(project)) {
      continue;
    }

    const options = project.compilerOptions;

    if (!isRecord(options)) {
      return null;
    }

    const buildInfo = options.tsBuildInfoFile;

    if (options.noEmit !== true || typeof buildInfo !== 'string') {
      return null;
    }

    const rel = normalizeSlashes(buildInfo);

    if (!rel.startsWith('node_modules/')) {
      return null;
    }

    found ??= { buildInfo: rel, tsconfig: project.file };
  }

  return found;
}

/** A config that only points at others: nothing to build, nothing written. */
function isSolutionStub(project: TsProject): boolean {
  return isStringArray(project.files) && project.files.length === 0
    && project.include === undefined;
}

interface TsProject {
  /** Path relative to root, for the message. */
  file: string;
  /** Directory the config's globs resolve against, relative to root. */
  dir: string;
  compilerOptions?: unknown;
  files?: unknown;
  include?: unknown;
  exclude?: unknown;
  extends?: unknown;
}

/** The root config plus its referenced projects, one level deep; deeper = null. */
function tsProjectGraph(root: string, file: string, text: string): TsProject[] | null {
  const parsed = parseJsonc(text);

  if (!parsed.ok || !isRecord(parsed.value)) {
    return null;
  }

  const rootProject = toProject(file, parsed.value);
  const refs = rootProject.references;

  if (refs === undefined) {
    return [rootProject];
  }

  if (!Array.isArray(refs)) {
    return null;
  }

  const projects: TsProject[] = [rootProject];

  for (const ref of refs) {
    if (!isRecord(ref) || typeof ref.path !== 'string') {
      return null;
    }

    const resolved = resolveReference(root, ref.path);

    if (resolved === null) {
      return null;
    }

    const refParsed = parseJsonc(resolved.text);

    if (!refParsed.ok || !isRecord(refParsed.value)) {
      return null;
    }

    const project = toProject(resolved.file, refParsed.value);

    // Depth stops here — see the note above.
    if (project.references !== undefined) {
      return null;
    }

    projects.push(project);
  }

  return projects;
}

/** A `references[].path` may name the file or its directory. */
function resolveReference(root: string, ref: string): { file: string; text: string } | null {
  const candidates = ref.endsWith('.json') ? [ref] : [path.join(ref, 'tsconfig.json')];

  for (const candidate of candidates) {
    const text = readText(path.join(root, candidate));

    // Normalised because this string is printed: a `references` path is written
    // `./tsconfig.node.json` as often as not, and the playbook names the file.
    if (text !== null) {
      return { file: normalizeSlashes(candidate), text };
    }
  }

  return null;
}

function toProject(
  file: string,
  value: Record<string, unknown>,
): TsProject & { references?: unknown } {
  return {
    file,
    dir: path.dirname(file) === '.' ? '' : path.dirname(file),
    compilerOptions: value.compilerOptions,
    files: value.files,
    include: value.include,
    exclude: value.exclude,
    extends: value.extends,
    references: value.references,
  };
}

/**
 * Does `project` pull `viteFile` in? `null` for the shapes this does not
 * reimplement — `exclude`, an `extends` base, character classes, brace expansion.
 */
function projectCovers(project: TsProject, viteFile: string): boolean | null {
  if (project.exclude !== undefined) {
    return null;
  }

  // The vite config is always a ROOT file (`VITE_FILES` carries no path segments)
  // and a tsconfig's globs never reach upward.
  if (project.dir !== '') {
    return false;
  }

  const rel = viteFile;

  if (project.files !== undefined) {
    if (!isStringArray(project.files)) {
      return null;
    }

    if (project.files.some((entry) => normalizeSlashes(entry) === rel)) {
      return true;
    }
  }

  if (project.include === undefined) {
    // No `files` and no `include`: TypeScript includes everything under the
    // config's directory — unless `extends` supplies globs this cannot see.
    if (project.files !== undefined) {
      return false;
    }

    return project.extends === undefined ? true : null;
  }

  if (!isStringArray(project.include)) {
    return null;
  }

  for (const glob of project.include) {
    const verdict = globCovers(normalizeSlashes(glob), rel);

    if (verdict === null) {
      return null;
    }

    if (verdict) {
      return true;
    }
  }

  return false;
}

// undecidable on the `^` anchor: unanchored it strips a mid-path `./`, and every
// path a tsconfig can hold resolves the same either way. It stays because it spells
// the intent — strip a LEADING `./` — not because any reachable input needs it.
function normalizeSlashes(value: string): string {
  return value.replace(/\\/g, '/').replace(/^\.\//, '');
}

/**
 * Does a tsconfig `include` glob cover `file`? Braces and character classes
 * return null — an unusual glob yields no verdict, never a wrong one.
 */
function globCovers(glob: string, file: string): boolean | null {
  if (/[{}[\]?]/.test(glob)) {
    return null;
  }

  const pattern = glob
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*\*\//g, '(?:.*/)?')
    .replace(/\*\*/g, '.*')
    .replace(/\*/g, '[^/]*');

  return new RegExp(`^${pattern}$`).test(file);
}

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((entry) => typeof entry === 'string');
}
