import type {
  ArchitectureDef,
  AxisDef,
  Blueprint,
  PlaybookSection,
  PrincipleDef,
  RuleSetting,
  Tier,
} from '../../config';
import { getModuleShape, normalizeAllowedImporters } from '../../config';
import { LINT_GATED_RULE_IDS } from '../lint';
import { formatOwns } from '../../markdown';

function tierOf(setting: RuleSetting): Tier {
  return typeof setting === 'string' ? setting : setting.tier;
}

function valueOf(setting: RuleSetting): number | undefined {
  return typeof setting === 'string' ? undefined : setting.value;
}

function rulesOfTier(rules: Record<string, RuleSetting> | undefined, tier: Tier) {
  return Object.entries(rules ?? {}).filter(([, setting]) => tierOf(setting) === tier);
}

function claudePrinciples(principles: PrincipleDef[] | undefined): PrincipleDef[] {
  return (principles ?? []).filter((principle) => principle.land === 'claude');
}

/** Contract heading + provenance. Uses `##` so it can nest inside CLAUDE.md. */
export function renderHeader(): string {
  return [
    '## Architecture contract (generated from blueprint)',
    '',
    '> Generated by `@kekkai/blueprint` — edit the blueprint, not this block.',
  ].join('\n');
}

/** One-liner orientation: framework, alias, layer order. */
export function renderContext(blueprint: Blueprint): string {
  const { framework, architecture } = blueprint;
  const chain = architecture.layers.map((layer) => `\`${layer.name}\``).join(' → ');

  return [
    '### Context',
    '',
    `- Framework: \`${framework}\`. Import alias: \`${architecture.alias}\`.`,
    `- Layer flow: ${chain}`,
  ].join('\n');
}

/** Per-layer placement directives + the module shape rule. */
export function renderPlacement(architecture: ArchitectureDef): string {
  const lines = architecture.layers.map((layer) => {
    const parts = [`- \`src/${layer.name}/\` — ${layer.does}.`];

    if (layer.mustNot?.length) {
      parts.push(` MUST NOT: ${layer.mustNot.join('; ')}.`);
    }

    const owns = formatOwns(layer.owns);

    if (owns) {
      parts.push(` OWNS: ${owns}.`);
    }

    if (layer.allowedImporters) {
      const importers = normalizeAllowedImporters(layer.allowedImporters)
        .map((importer) => (importer.selfOnly ? `${importer.layer} (selfOnly)` : importer.layer))
        .join(', ');

      parts.push(` IMPORTABLE BY: ${importers}.`);
    }

    return parts.join('');
  });

  const { module } = architecture;
  const priv = module.private.map((part) => `\`${part}\``).join(' / ');

  const moduleLine
    = module.layout === 'folder'
      ? `- Module shape: one folder per module. Only \`${module.entry}\` is importable from outside${priv ? `; keep ${priv} private and never import them across modules` : ''}.`
      : '- Module shape: one file per module (flat). Extract shared logic to a lower layer.';

  const overrideLines = architecture.layers
    .filter((layer) => layer.module !== undefined)
    .map((layer) => {
      const shape = getModuleShape(architecture, layer.name);

      return shape.layout === 'folder'
        ? `- Exception — \`src/${layer.name}/\`: one folder per module, entry \`${shape.entry}\`.`
        : `- Exception — \`src/${layer.name}/\`: one file per module (flat).`;
    });

  return ['### Where code goes', '', ...lines, moduleLine, ...overrideLines].join('\n');
}

/** Naming conventions as directives. */
export function renderNaming(naming: Record<string, string> | undefined): string {
  const entries = Object.entries(naming ?? {});

  if (!entries.length) return '';

  return [
    '### Naming',
    '',
    ...entries.map(([concept, convention]) => `- \`${concept}\`: ${convention}`),
  ].join('\n');
}

/** The lint-enforced rules, phrased as imperatives, + how to react to a failure. */
export function renderHardRules(
  architecture: ArchitectureDef,
  rules: Record<string, RuleSetting> | undefined,
): string {
  const bullets = ['- Import only from downstream layers — never upstream, never the same layer.'];

  const folderEntries = [
    ...new Set(
      architecture.layers
        .map((layer) => getModuleShape(architecture, layer.name))
        .filter((shape) => shape.layout === 'folder')
        .map((shape) => `\`${shape.entry}\``),
    ),
  ];

  if (folderEntries.length) {
    bullets.push(`- Import a module via its ${folderEntries.join(' / ')}, never its internals.`);
  }

  bullets.push(
    '- Restricted packages / globals live only in their owning layer (see "Where code goes").',
    '- Relative imports stay inside their module; no redundant segments (`./../`, `././`).',
  );

  // Only rules a machine actually gates may be called hard — anything else
  // here would be a promise the tooling does not keep.
  for (const [id, setting] of rulesOfTier(rules, 'error')) {
    if (!LINT_GATED_RULE_IDS.includes(id)) continue;

    const value = valueOf(setting);

    bullets.push(`- \`${id}\`${value === undefined ? '' : ` = ${value}`} is a hard gate.`);
  }

  bullets.push(
    '- When lint fails, fix the structure — move the code or extract a lower layer. Never silence it with `eslint-disable`, and never relocate the violation to a sibling.',
  );

  return ['### Hard rules (lint enforces these)', '', ...bullets].join('\n');
}

/** The component-shape axes as terse directives — each judged independently. */
export function renderComponentShape(axes: AxisDef[] | undefined): string {
  if (!axes?.length) return '';

  const bullets = axes.map((axis) => {
    const triage = axis.triage
      ? ` (triage: \`${axis.triage}\` is an entry point, never the verdict)`
      : '';

    return `- **${axis.name}** — ${axis.say} ${axis.why}${triage}`;
  });

  return [
    '### Component shape (orthogonal axes — judge each independently)',
    '',
    'A set, not a pipeline: never infer one axis holds because another does.',
    '',
    ...bullets,
  ].join('\n');
}

/** Rules no tool can catch — the agent is the only gate. */
export function renderBehavioral(
  architecture: ArchitectureDef,
  principles: PrincipleDef[] | undefined,
  rules: Record<string, RuleSetting> | undefined,
): string {
  const bullets = [
    `- Do not create undeclared folders under \`${architecture.alias}/\`. Every folder is a declared layer or a module inside one. (lint can't see this — inspect will.)`,
    ...claudePrinciples(principles).map(
      (principle) => `- **${principle.say}** — ${principle.why}`,
    ),
  ];

  if (rules?.deadCode !== undefined && tierOf(rules.deadCode) === 'error') {
    bullets.push(
      '- **Dead code is error-tier, but no lint rule can gate it** — `npx knip` is the gate (in init\'s install set); the generated CI carries the step commented — uncomment it to make the gate hard.',
    );
  }

  if (rulesOfTier(rules, 'warn').length) {
    bullets.push(
      '- Treat a `warn`-tier lint result as a review entry point — look there, don\'t ignore it.',
    );
  }

  return [
    '### Behavioral rules (no tool enforces these — you are the gate)',
    '',
    ...bullets,
  ].join('\n');
}

/** The working playbook as terse directives, one block per theme. */
export function renderPlaybook(playbook: PlaybookSection[] | undefined): string {
  if (!playbook?.length) return '';

  const blocks = playbook.map((section) =>
    [
      `#### ${section.title}`,
      '',
      ...section.rules.map(
        (rule) => `- **${rule.say}**${rule.why ? ` ${rule.why}` : ''}`,
      ),
    ].join('\n'));

  return [
    '### Working playbook (judgment rules — you are the gate)',
    '',
    ...blocks.join('\n\n').split('\n'),
  ].join('\n');
}

/** A short pre-commit checklist, growing with the blueprint's data. */
export function renderChecklist(blueprint: Blueprint): string {
  const { architecture, principles } = blueprint;

  const items = [
    '- [ ] Imports follow the one-way flow (no upstream / same-layer).',
    `- [ ] New code sits in the right layer; modules expose only \`${architecture.module.entry}\`.`,
  ];

  if (architecture.naming && Object.keys(architecture.naming).length) {
    items.push('- [ ] Names follow the conventions above.');
  }

  items.push(`- [ ] No new undeclared folders under \`${architecture.alias}/\`.`);

  if (blueprint.componentShape?.length) {
    items.push('- [ ] Changed units hold against every component-shape axis, judged one by one.');
  }

  if (claudePrinciples(principles).length) {
    items.push('- [ ] The behavioral principles above are upheld.');
  }

  return ['### Before you commit', '', ...items].join('\n');
}
