import type {
  ArchitectureDef,
  AxisDef,
  Blueprint,
  PlaybookSection,
  PrincipleDef,
  ResolvedArchitecture,
  RuleSetting,
  Tier,
} from '../../config';
import {
  readSetting,
  resolveArchitecture,
} from '../../config';
import { handbookPath } from '../docs';
import { enforcedBy, resolveTestFiles, unavailableForEmit } from '../lint';
import type { StackFacts } from '../lint';
import { formatOwns } from '../../markdown';

function rulesOfTier(rules: Record<string, RuleSetting> | undefined, tier: Tier) {
  return Object.entries(rules ?? {}).filter(([, setting]) => readSetting(setting).tier === tier);
}

function claudePrinciples(principles: PrincipleDef[] | undefined): PrincipleDef[] {
  if (!principles) {
    return [];
  }

  return principles.filter((principle) => principle.land === 'claude');
}

function gateLabel([id, setting]: [string, RuleSetting]): string {
  const value = readSetting(setting).value;

  return `\`${id}\`${value === undefined ? '' : ` = ${value}`}`;
}

function emittableGates(blueprint: Blueprint, stack: StackFacts): [string, RuleSetting][] {
  const { architecture, framework, rules } = blueprint;

  return rulesOfTier(rules, 'error').filter(
    ([id]) => unavailableForEmit(id, {
      framework,
      testFiles: architecture.testFiles,
      hasTypescript: stack.hasTypescript,
    }) === null,
  );
}

function inspectDiagnosisClause(gates: string): string {
  return `${gates} is diagnosed only when \`npx blueprint inspect --baseline\` runs; `
    + 'the baseline grandfathers recorded findings, so this is not continuous '
    + 'edit-time prevention and a green lint says nothing about it';
}

export function renderHeader(): string {
  return [
    '## Architecture contract (generated from blueprint)',
    '',
    '> Generated by `@kekkai/blueprint` — edit the blueprint, not this block.',
    '> Your own notes belong OUTSIDE the markers; init rewrites only between them.',
    '> The strictness is the product — it keeps AI development inside the declared',
    '> architecture. Never soften or bypass; disagreements go to the maintainer.',
  ].join('\n');
}

const CONTRACT_DOC = 'node_modules/@kekkai/blueprint/agent-contract.md';

export function renderCompactContract(blueprint: Blueprint, stack: StackFacts = {}): string {
  const { architecture } = blueprint;
  const resolved = resolveArchitecture(architecture);
  const chain = resolved.layers.map((layer) => `\`${layer.name}\``).join(' → ');
  const handbook = handbookPath(blueprint);

  const topology = resolved.topology === 'module-first'
    ? 'Module → Layer → Unit'
    : 'Layer → Unit';

  const declared = emittableGates(blueprint, stack);
  const lintGates = declared.filter(([id]) => enforcedBy(id) === 'lint').map(gateLabel);
  const inspectGates = declared.filter(([id]) => enforcedBy(id) === 'inspect').map(gateLabel);

  const extras = [
    ...(blueprint.componentShape?.length ? ['component-shape axes'] : []),
    ...(claudePrinciples(blueprint.principles).length ? ['behavioral principles'] : []),
    ...(blueprint.playbook?.length ? ['the working playbook'] : []),
  ];

  return [
    renderHeader(),
    '',
    `- Framework: \`${blueprint.framework}\`. Import alias: \`${architecture.alias}\`.`,
    ...moduleFlowLine(resolved),
    `- Layer flow: ${chain} — transitive: a layer may import **any** layer after it, unless the target narrows its importers.`,
    `- **Before adding, moving, or renaming any file** — placement, ${resolved.topology === 'module-first' ? 'module boundaries, ' : ''}unit shapes, ownership, naming${extras.length ? `, ${extras.join(', ')}` : ''}: read [${handbook}](${handbook}) (generated from the same blueprint — always current).`,
    '- **Operating discipline** — how to follow the flow, react to lint failures, '
    + `and the pre-commit checklist: read [${CONTRACT_DOC}](${CONTRACT_DOC}) `
    + '(ships inside the package — present once dependencies are installed, '
    + 'always matching the installed version).',

    `- Hard gates (machine-enforced on the files the architecture globs match — a declared position holding no code has nothing failing yet, which is runway, not protection): one-way imports, unit entries, ownership, relative escapes${lintGates.length ? `, ${lintGates.join(', ')}` : ''} fail the project's lint run${inspectGates.length ? `; ${inspectDiagnosisClause(inspectGates.join(', '))}` : ''}. When lint fails, fix the structure — never \`eslint-disable\`, never relocate the violation to a sibling.`,

    `- You are the gate for: no undeclared architectural folders under \`${architecture.alias}/\` (\`blueprint inspect --baseline\` verifies — red only on what you introduced). Move code into the declared ${topology} topology. If the architecture has genuinely outgrown this config, that is the owner's decision — say so and stop; never expand it yourself.`,
  ].join('\n');
}

function moduleFlowLine(resolved: ResolvedArchitecture): string[] {
  return resolved.modules.length
    ? ['- Module flow: each module may import itself and modules transitively reachable through '
      + '`dependsOn`; declaration order grants no permission. The layer flow must also pass.']
    : [];
}

export function renderContext(blueprint: Blueprint): string {
  const { framework, architecture } = blueprint;
  const resolved = resolveArchitecture(architecture);
  const chain = resolved.layers.map((layer) => `\`${layer.name}\``).join(' → ');

  return [
    '### Context',
    '',
    `- Framework: \`${framework}\`. Import alias: \`${architecture.alias}\`.`,
    ...(resolved.modules.length
      ? [`- Modules: ${resolved.modules.map((module) => {
          const dependencies = module.dependsOn.length
            ? module.dependsOn.map((dependency) => `\`${dependency}\``).join(', ')
            : 'none';

          return `\`${module.name}\` (depends on ${dependencies})`;
        }).join('; ')}`]
      : []),
    `- Layer flow: ${chain}`,
  ].join('\n');
}

export function renderPlacement(architecture: ArchitectureDef): string {
  const resolved = resolveArchitecture(architecture);

  const moduleLines = resolved.modules.map((module) => {
    const dependencies = module.dependsOn.length
      ? module.dependsOn.map((dependency) => `\`${dependency}\``).join(', ')
      : 'none';

    return `- \`${module.root}/\` — module: ${module.definition.does}. `
      + `DIRECT DEPENDENCIES: ${dependencies}.`;
  });

  const lines = resolved.layerPositions.map((position) => {
    const { definition: layer, allowedImporters } = position.layer;
    const parts = [`- \`${position.root}/\` — layer: ${layer.does}.`];

    if (layer.mustNot?.length) {
      parts.push(` MUST NOT: ${layer.mustNot.join('; ')}.`);
    }

    const owns = formatOwns(layer.owns);

    if (owns) {
      parts.push(` OWNS: ${owns}.`);
    }

    if (layer.allowedImporters) {
      const importers = allowedImporters
        .map((importer) => (importer.selfOnly ? `${importer.layer} (selfOnly)` : importer.layer))
        .join(', ');

      parts.push(` IMPORTABLE BY: ${importers}.`);
    }

    return parts.join('');
  });

  const unitLines = resolved.layers.map((layer) => layer.unit.layout === 'folder'
    ? `- \`${layer.name}\` units: one folder per unit; only \`${layer.unit.entry}\` is importable from outside.`
    : `- \`${layer.name}\` units: one file per unit.`);

  const testGlobs = resolveTestFiles(architecture.testFiles);

  const exemptLine = testGlobs.length
    ? [`- Test support is exempt from every placement rule above as far as those globs reach: files matching ${testGlobs.map((glob) => `\`${glob}\``).join(' / ')} sit outside them, and a file none of them matches is placed by the rules above like any other. If a placement rule stops you on files that exist only to serve tests, that is a question for the owner — say so and name them; never widen \`architecture.testFiles\` yourself, and never rename a file to match those globs.`]
    : [];

  return [
    '### Where code goes',
    '',
    ...moduleLines,
    ...lines,
    ...unitLines,
    ...exemptLine,
  ].join('\n');
}

export function renderNaming(naming: Record<string, string> | undefined): string {
  const entries = Object.entries(naming ?? {});

  if (!entries.length) {
    return '';
  }

  return [
    '### Naming',
    '',
    ...entries.map(([concept, convention]) => `- \`${concept}\`: ${convention}`),
  ].join('\n');
}

export function renderHardRules(blueprint: Blueprint, stack: StackFacts = {}): string {
  const { architecture } = blueprint;

  const bullets = [
    '- Cross-layer imports go only downstream; local same-layer imports never use the alias.',
  ];

  const folderEntries = [
    ...new Set(
      resolveArchitecture(architecture).layers
        .map((layer) => layer.unit)
        .filter((shape) => shape.layout === 'folder')
        .map((shape) => `\`${shape.entry}\``),
    ),
  ];

  if (folderEntries.length) {
    bullets.push(`- Import a folder unit via its ${folderEntries.join(' / ')}, never its internals.`);
  }

  bullets.push(
    '- Restricted packages / globals live only in their owning layer (see "Where code goes").',
    '- Relative imports stay inside their layer. Folder units reach siblings only through '
    + 'their entries; no redundant segments (`./../`, `././`).',
  );

  for (const [id, setting] of emittableGates(blueprint, stack)) {
    const held = enforcedBy(id);
    const gate = gateLabel([id, setting]);

    if (held === 'lint') {
      bullets.push(`- ${gate} is a hard gate.`);
    }

    if (held === 'inspect') {
      bullets.push(`- ${inspectDiagnosisClause(gate)}.`);
    }
  }

  bullets.push(
    '- When lint fails, fix the structure — move the code or extract a lower layer. '
    + 'Never silence it with `eslint-disable`, and never relocate the violation to a sibling.',
  );

  return ['### Machine checks', '', ...bullets].join('\n');
}

export function renderComponentShape(axes: AxisDef[] | undefined): string {
  if (!axes?.length) {
    return '';
  }

  const bullets = axes.map((axis) => {
    const triage = axis.triage
      ? ` (triage: \`${axis.triage}\` is an entry point, never the verdict)`
      : '';

    return `- **${axis.name}** — ${axis.say} ${axis.why}${triage}`;
  });

  return [
    '### Component shape (orthogonal axes — judge each independently)',
    '',
    'A set, not a pipeline: never infer one axis holds because another does.',
    '',
    ...bullets,
  ].join('\n');
}

export function renderBehavioral(
  architecture: ArchitectureDef,
  principles: PrincipleDef[] | undefined,
  rules: Record<string, RuleSetting> | undefined,
): string {
  const topology = resolveArchitecture(architecture).topology === 'module-first'
    ? 'Module → Layer → Unit'
    : 'Layer → Unit';

  const bullets = [
    `- Do not create undeclared architectural folders under \`${architecture.alias}/\`. Follow the declared ${topology} topology. (lint can't see every folder — inspect will.) Outgrowing the config is the owner's call to make — report it, do not edit the architecture to fit what you just wrote.`,
    ...claudePrinciples(principles).map(
      (principle) => `- **${principle.say}** — ${principle.why}`,
    ),
  ];

  if (rules?.deadCode !== undefined && readSetting(rules.deadCode).tier === 'error') {
    bullets.push(
      '- **Dead code is error-tier, but no lint rule can gate it** — '
      + '`npx knip` is the gate (in init\'s install set); '
      + 'wire it into whatever verification you run.',
    );
  }

  if (rulesOfTier(rules, 'warn').length) {
    bullets.push(
      '- Treat a `warn`-tier lint result as a review entry point — look there, don\'t ignore it.',
    );
  }

  return [
    '### Behavioral rules (no tool enforces these — you are the gate)',
    '',
    ...bullets,
  ].join('\n');
}

export function renderPlaybook(playbook: PlaybookSection[] | undefined): string {
  if (!playbook?.length) {
    return '';
  }

  const blocks = playbook.map((section) =>
    [
      `#### ${section.title}`,
      '',
      ...section.rules.map(
        (rule) => `- **${rule.say}**${rule.why ? ` ${rule.why}` : ''}`,
      ),
    ].join('\n'));

  return [
    '### Working playbook (judgment rules — you are the gate)',
    '',
    ...blocks.join('\n\n').split('\n'),
  ].join('\n');
}

export function renderChecklist(blueprint: Blueprint): string {
  const { architecture, principles } = blueprint;
  const resolved = resolveArchitecture(architecture);

  const items = [
    '- [ ] Imports follow the one-way flow (no upstream layers or local same-layer aliases).',
    `- [ ] New code sits in the declared ${resolved.topology === 'module-first'
      ? 'module and layer'
      : 'layer'}; folder units expose only their declared entry.`,
  ];

  if (architecture.naming && Object.keys(architecture.naming).length) {
    items.push('- [ ] Names follow the conventions above.');
  }

  items.push(`- [ ] No new undeclared folders under \`${architecture.alias}/\`.`);

  if (blueprint.componentShape?.length) {
    items.push('- [ ] Changed units hold against every component-shape axis, judged one by one.');
  }

  if (claudePrinciples(principles).length) {
    items.push('- [ ] The behavioral principles above are upheld.');
  }

  return ['### Before you commit', '', ...items].join('\n');
}
