import type {
  ArchitectureDef,
  AxisDef,
  Blueprint,
  PlaybookSection,
  PrincipleDef,
  RuleSetting,
  Tier,
} from '../../config';
import { folderEntries, readSetting, moduleShapeGroups, normalizeAllowedImporters } from '../../config';
import { handbookPath } from '../docs';
import { enforcedBy, LINT_GATED_RULE_IDS, resolveTestFiles, unavailableFromBlueprint } from '../lint';
import { formatOwns } from '../../markdown';

function rulesOfTier(rules: Record<string, RuleSetting> | undefined, tier: Tier) {
  return Object.entries(rules ?? {}).filter(([, setting]) => readSetting(setting).tier === tier);
}

function claudePrinciples(principles: PrincipleDef[] | undefined): PrincipleDef[] {
  if (!principles) return [];

  return principles.filter((principle) => principle.land === 'claude');
}

/** Contract heading + provenance. Uses `##` so it can nest inside CLAUDE.md. */
export function renderHeader(): string {
  return [
    '## Architecture contract (generated from blueprint)',
    '',
    '> Generated by `@kekkai/blueprint` — edit the blueprint, not this block.',
    '> Your own notes belong OUTSIDE the markers; init rewrites only between them.',
    '> The strictness is the product — it keeps AI development inside the declared',
    '> architecture. Never soften or bypass; disagreements go to the maintainer.',
  ].join('\n');
}

/**
 * The compact pointer block for shared context files (CLAUDE.md, AGENTS.md,
 * GEMINI.md, copilot). One screen of project facts; the bulk lives behind two
 * links — the generated handbook (project half) and the discipline document
 * shipped inside the package (generic half). Tool-owned rule files
 * (Cursor/Windsurf) still carry the full contract: they are generated files,
 * not documents a person maintains.
 */
export function renderCompactContract(blueprint: Blueprint): string {
  const { architecture, rules } = blueprint;
  const chain = architecture.layers.map((layer) => `\`${layer.name}\``).join(' → ');
  const handbook = handbookPath(blueprint);

  const label = ([id, setting]: [string, RuleSetting]): string => {
    const value = readSetting(setting).value;

    return `\`${id}\`${value === undefined ? '' : ` = ${value}`}`;
  };

  // Split by WHICH machine holds each gate: `cycles` is lint-gated by id while its
  // runtime is `inspect`, so an undivided list promises that lint catches cycles
  // (field issue #52). The singular verb below is pinned by this module's tests —
  // exactly one declared rule is inspect-held, so a plural arm is unreachable.
  //
  // No `LINT_GATED_RULE_IDS` pre-filter: `enforcedBy` answers `docs` off that list
  // anyway. And a gate this blueprint cannot emit is excluded, or the contract makes
  // a false claim about the reader's own repo (field run #150).
  const emittable = ([id]: [string, unknown]): boolean =>
    unavailableFromBlueprint(id, blueprint.framework, architecture.testFiles) === null;

  const declared = rulesOfTier(rules, 'error').filter(emittable);
  const lintGates = declared.filter(([id]) => enforcedBy(id) === 'lint').map(label);
  const inspectGates = declared.filter(([id]) => enforcedBy(id) === 'inspect').map(label);

  const extras = [
    ...(blueprint.componentShape?.length ? ['component-shape axes'] : []),
    ...(claudePrinciples(blueprint.principles).length ? ['behavioral principles'] : []),
    ...(blueprint.playbook?.length ? ['the working playbook'] : []),
  ];

  return [
    renderHeader(),
    '',
    `- Framework: \`${blueprint.framework}\`. Import alias: \`${architecture.alias}\`.`,
    `- Layer flow: ${chain} — transitive: a layer may import **any** layer after it, unless the target narrows its importers.`,
    `- **Before adding, moving, or renaming any file** — placement, module shapes, ownership, naming${extras.length ? `, ${extras.join(', ')}` : ''}: read [${handbook}](${handbook}) (generated from the same blueprint — always current).`,
    '- **Operating discipline** — how to follow the flow, react to lint failures, and the pre-commit checklist: read [node_modules/@kekkai/blueprint/agent-contract.md](node_modules/@kekkai/blueprint/agent-contract.md) (ships inside the package — present once dependencies are installed, always matching the installed version).',
    // Names the gates' REACH as a clause, not a second line: every other CLI surface
    // marks an empty net as vacuous, and this contract is the one artifact read with
    // no CLI output beside it. "the project's lint run", never `npm run lint` — the
    // runner is a repo fact this emitter cannot see (field run #141).
    `- Hard gates (machine-enforced on the files the layer globs match — a layer holding no code has nothing failing yet, which is runway, not protection): one-way imports, module entries, ownership, relative escapes${lintGates.length ? `, ${lintGates.join(', ')}` : ''} fail the project's lint run${inspectGates.length ? `; ${inspectGates.join(', ')} is held by \`npx blueprint inspect --baseline\` instead, so a green lint says nothing about it` : ''}. When lint fails, fix the structure — never \`eslint-disable\`, never relocate the violation to a sibling.`,
    // --baseline, or the verify loop stays red forever on locked brownfield debt
    // (field issue #10). Both remedies are named, and whose each is: told only "move
    // the code", an agent contorts it into an existing layer instead of reporting
    // that the architecture outgrew the config.
    `- You are the gate for: no undeclared folders under \`${architecture.alias}/\` (\`blueprint inspect --baseline\` verifies — red only on what you introduced). Its finding names two remedies and only one is yours: move the code into a module of an existing layer. If the architecture has genuinely outgrown this config, that is the owner's decision — say so and stop; never declare the layer yourself.`,
  ].join('\n');
}

/** One-liner orientation: framework, alias, layer order. */
export function renderContext(blueprint: Blueprint): string {
  const { framework, architecture } = blueprint;
  const chain = architecture.layers.map((layer) => `\`${layer.name}\``).join(' → ');

  return [
    '### Context',
    '',
    `- Framework: \`${framework}\`. Import alias: \`${architecture.alias}\`.`,
    `- Layer flow: ${chain}`,
  ].join('\n');
}

/** Per-layer placement directives + the module shape rule. */
export function renderPlacement(architecture: ArchitectureDef): string {
  const lines = architecture.layers.map((layer) => {
    const parts = [`- \`src/${layer.name}/\` — ${layer.does}.`];

    if (layer.mustNot?.length) {
      parts.push(` MUST NOT: ${layer.mustNot.join('; ')}.`);
    }

    const owns = formatOwns(layer.owns);

    if (owns) {
      parts.push(` OWNS: ${owns}.`);
    }

    if (layer.allowedImporters) {
      const importers = normalizeAllowedImporters(layer.allowedImporters)
        .map((importer) => (importer.selfOnly ? `${importer.layer} (selfOnly)` : importer.layer))
        .join(', ');

      parts.push(` IMPORTABLE BY: ${importers}.`);
    }

    return parts.join('');
  });

  const groups = moduleShapeGroups(architecture);

  const moduleLines = groups.map((group) => {
    // One shape is the project's; several are stated per layer set, since a
    // single line would hand one layer the other's rule.
    const scope = groups.length === 1
      ? ''
      : ` in ${group.layers.map((layer) => `\`src/${layer}/\``).join(' / ')}`;

    return group.layout === 'folder'
      ? `- Module shape${scope}: one folder per module. Only \`${group.entry}\` is importable from outside.`
      : `- Module shape${scope}: one file per module (flat).`;
  });

  // Reporting instruction, not a third remedy. An agent that learns "files matching
  // these globs are exempt from placement", while under pressure to get a gate green,
  // has been handed a rename-to-escape route — the same move the contract already
  // forbids next door ("never relocate the violation to a sibling").
  const testGlobs = resolveTestFiles(architecture.testFiles);

  const exemptLine = testGlobs.length
    ? [`- Test support is exempt from every placement rule above: files matching ${testGlobs.map((glob) => `\`${glob}\``).join(' / ')} sit outside them. If a placement rule stops you on files that exist only to serve tests, that is a question for the owner — say so and name them; never widen \`architecture.testFiles\` yourself, and never rename a file to match those globs.`]
    : [];

  return ['### Where code goes', '', ...lines, ...moduleLines, ...exemptLine].join('\n');
}

/** Naming conventions as directives. */
export function renderNaming(naming: Record<string, string> | undefined): string {
  const entries = Object.entries(naming ?? {});

  if (!entries.length) return '';

  return [
    '### Naming',
    '',
    ...entries.map(([concept, convention]) => `- \`${concept}\`: ${convention}`),
  ].join('\n');
}

/** The lint-enforced rules, phrased as imperatives, + how to react to a failure. */
export function renderHardRules(
  architecture: ArchitectureDef,
  rules: Record<string, RuleSetting> | undefined,
): string {
  const bullets = [
    '- Import only from downstream layers — never upstream. A same-layer import is legal'
    + ' only as a relative path reaching the sibling\'s public surface: never through the'
    + ' alias, and never past a folder module\'s entry.',
  ];

  const entries = folderEntries(architecture).map((entry) => `\`${entry}\``);

  if (entries.length) {
    bullets.push(`- Import a module via its ${entries.join(' / ')}, never its internals.`);
  }

  bullets.push(
    '- Restricted packages / globals live only in their owning layer (see "Where code goes").',
    '- Relative imports stay inside their module; no redundant segments (`./../`, `././`).',
  );

  // Only rules a machine actually gates may be called hard — anything else
  // here would be a promise the tooling does not keep.
  for (const [id, setting] of rulesOfTier(rules, 'error')) {
    if (!LINT_GATED_RULE_IDS.includes(id)) continue;

    const value = readSetting(setting).value;

    bullets.push(`- \`${id}\`${value === undefined ? '' : ` = ${value}`} is a hard gate.`);
  }

  bullets.push(
    '- When lint fails, fix the structure — move the code or extract a lower layer. Never silence it with `eslint-disable`, and never relocate the violation to a sibling.',
  );

  return ['### Hard rules (lint enforces these)', '', ...bullets].join('\n');
}

/** The component-shape axes as terse directives — each judged independently. */
export function renderComponentShape(axes: AxisDef[] | undefined): string {
  if (!axes?.length) return '';

  const bullets = axes.map((axis) => {
    const triage = axis.triage
      ? ` (triage: \`${axis.triage}\` is an entry point, never the verdict)`
      : '';

    return `- **${axis.name}** — ${axis.say} ${axis.why}${triage}`;
  });

  return [
    '### Component shape (orthogonal axes — judge each independently)',
    '',
    'A set, not a pipeline: never infer one axis holds because another does.',
    '',
    ...bullets,
  ].join('\n');
}

/** Rules no tool can catch — the agent is the only gate. */
export function renderBehavioral(
  architecture: ArchitectureDef,
  principles: PrincipleDef[] | undefined,
  rules: Record<string, RuleSetting> | undefined,
): string {
  const bullets = [
    `- Do not create undeclared folders under \`${architecture.alias}/\`. Every folder is a declared layer or a module inside one. (lint can't see this — inspect will.) Inspect offers to declare the folder instead; that one is not yours. Outgrowing the config is the owner's call to make — report it, do not edit the architecture to fit what you just wrote.`,
    ...claudePrinciples(principles).map(
      (principle) => `- **${principle.say}** — ${principle.why}`,
    ),
  ];

  if (rules?.deadCode !== undefined && readSetting(rules.deadCode).tier === 'error') {
    bullets.push(
      '- **Dead code is error-tier, but no lint rule can gate it** — `npx knip` is the gate (in init\'s install set); wire it into whatever verification you run.',
    );
  }

  if (rulesOfTier(rules, 'warn').length) {
    bullets.push(
      '- Treat a `warn`-tier lint result as a review entry point — look there, don\'t ignore it.',
    );
  }

  return [
    '### Behavioral rules (no tool enforces these — you are the gate)',
    '',
    ...bullets,
  ].join('\n');
}

/** The working playbook as terse directives, one block per theme. */
export function renderPlaybook(playbook: PlaybookSection[] | undefined): string {
  if (!playbook?.length) return '';

  const blocks = playbook.map((section) =>
    [
      `#### ${section.title}`,
      '',
      ...section.rules.map(
        (rule) => `- **${rule.say}**${rule.why ? ` ${rule.why}` : ''}`,
      ),
    ].join('\n'));

  return [
    '### Working playbook (judgment rules — you are the gate)',
    '',
    ...blocks.join('\n\n').split('\n'),
  ].join('\n');
}

/** A short pre-commit checklist, growing with the blueprint's data. */
export function renderChecklist(blueprint: Blueprint): string {
  const { architecture, principles } = blueprint;

  // Only folder layers have an entry to expose; an all-flat project gets the
  // placement half alone rather than a filename that governs nothing there.
  const entries = folderEntries(architecture).map((entry) => `\`${entry}\``);

  const items = [
    '- [ ] Imports follow the one-way flow (no upstream; same-layer only as a relative path to the sibling).',
    entries.length
      ? `- [ ] New code sits in the right layer; modules expose only ${entries.join(' / ')}.`
      : '- [ ] New code sits in the right layer.',
  ];

  if (architecture.naming && Object.keys(architecture.naming).length) {
    items.push('- [ ] Names follow the conventions above.');
  }

  items.push(`- [ ] No new undeclared folders under \`${architecture.alias}/\`.`);

  if (blueprint.componentShape?.length) {
    items.push('- [ ] Changed units hold against every component-shape axis, judged one by one.');
  }

  if (claudePrinciples(principles).length) {
    items.push('- [ ] The behavioral principles above are upheld.');
  }

  return ['### Before you commit', '', ...items].join('\n');
}
