import type { PackageManager } from '../project';
import { renderSurvey } from '../survey';
import type { SurveyResult } from '../survey';
import { installCommand } from './plan';
import type { Action } from './types';

/**
 * The brownfield authoring flow: when `init` runs on a repo with real code
 * and no blueprint.config, scaffolding a preset would be a lie — the layers
 * already exist, someone has to *read* them. This module emits the executable
 * playbook for that judgment call (for an agent or a human), plus the
 * `/blueprint-author` command file that hands it to Claude Code. Everything
 * lands on disk before any agent starts: the manual path is not a fallback,
 * it is the same path — an agent just walks it for you.
 */

export const AUTHORING_FILE = 'blueprint-authoring.md';
export const COMMAND_FILE = '.claude/commands/blueprint-author.md';

/** The entry prompt every launcher (or human) feeds the agent. */
export const AGENT_PROMPT
  = `Read ${AUTHORING_FILE} at the repository root and execute it end to end.`;

/** A repo counts as brownfield when src/ already holds this many source files. */
export const BROWNFIELD_MIN_FILES = 10;

export interface AuthoringOptions {
  packageManager: PackageManager;
  /** True when `@kekkai/blueprint` is not yet a dependency of the project. */
  needsInstall: boolean;
  /** Skip the install action when false (`--no-install`) — instruct instead. */
  install?: boolean;
  /** Next.js project — the playbook carries framework-specific guidance. */
  next?: boolean;
}

/** The `init` actions for the authoring flow. Pure — writes nothing itself. */
export function authoringActions(survey: SurveyResult, options: AuthoringOptions): Action[] {
  const command = installCommand(options.packageManager, ['@kekkai/blueprint']);

  // The playbook's config imports @kekkai/blueprint and every follow-up step
  // resolves it from the project — the authoring flow must leave it installed,
  // or the very first `npx blueprint inspect` after authoring falls over.
  const install: Action[] = !options.needsInstall
    ? []
    : options.install !== false
      ? [{ kind: 'install', command, note: 'install @kekkai/blueprint (the config imports it)' }]
      : [{ kind: 'instruct', note: `Install skipped — the config imports @kekkai/blueprint, so run it before authoring:\n    ${command}` }];

  return [
    {
      kind: 'write',
      path: AUTHORING_FILE,
      content: authoringBrief(survey, command, options.next),
      note: `${AUTHORING_FILE} (authoring playbook + survey evidence)`,
    },
    {
      kind: 'write',
      path: COMMAND_FILE,
      content: `${AGENT_PROMPT}\n`,
      note: `${COMMAND_FILE} (/blueprint-author)`,
    },
    ...install,
    {
      kind: 'instruct',
      note: [
        'This repo already has code but no blueprint.config.mjs — authoring one is a',
        '  judgment call, so init generated a playbook instead of guessing. Have an agent',
        '  execute it (it ends by re-running init and locking a baseline):',
        `    claude "${AGENT_PROMPT}"     # or: /blueprint-author inside Claude Code`,
        `    codex "${AGENT_PROMPT}"`,
        '  …or follow the playbook yourself. Prefer a preset scaffold instead? Re-run:',
        '    blueprint init --preset',
      ].join('\n'),
    },
  ];
}

/** The playbook: goal, method, acceptance gates, and the survey evidence. */
export function authoringBrief(survey: SurveyResult, install: string, next = false): string {
  const nextNote = !next
    ? ''
    : `

> **Next.js project.** The route tree (\`app/\`, or \`pages/\` on the Pages
> Router) is itself a layer — declare it at the top of the flow (a typical
> shape: \`app\` → \`components\` → \`hooks\` → \`lib\`). Never scaffold or
> declare an empty \`src/pages\` alongside the App Router: that folder name is
> a routing convention. Flat module layout fits the route tree — relative
> imports stay free inside a segment while cross-layer traffic uses the alias.`;

  // The most common repo init ever meets is a starter, and the correct
  // outcome there is the early exit — a conclusion that must not sit buried
  // mid-playbook where a hurried agent walks the full ceremony past it
  // (field batch 10). Below the threshold, the verdict leads.
  const verdict = survey.totalFiles >= BROWNFIELD_MIN_FILES
    ? ''
    : `

## Read this first — the survey already points at the exit

The survey counted ${survey.totalFiles} source file(s) — below the
brownfield threshold (${BROWNFIELD_MIN_FILES}). At this size the expected
conclusion is the early exit: run \`npx blueprint init --preset\`, wire its
outputs, delete this playbook and \`${COMMAND_FILE}\`, and stop — "preset
was enough" is a complete, correct report. Walk the full method below only
if you find structure the file count hides: existing intent documents
(Method step 1) or meaningful layer folders.`;

  return `# Blueprint authoring playbook${nextNote}

> Generated by \`blueprint init\`. Execute top to bottom. When you finish,
> delete this file and \`${COMMAND_FILE}\`.${verdict}

## Prerequisites

\`@kekkai/blueprint\` must be a devDependency — the config you will write
imports it, and every \`npx blueprint\` step resolves it from the project.
\`init\` already installed it unless \`--no-install\` was passed; verify, or run:

\`\`\`bash
${install}
\`\`\`

## Goal and boundary

Author \`blueprint.config.mjs\` for this repository so that its architecture
rules match the code's *intent*, then generate the artifacts and lock the
baseline. Deliverables:

1. \`blueprint.config.mjs\` — validated, findings explainable
2. \`npx blueprint init\` artifacts (lint config, handbook, agent contracts)
3. \`npx blueprint inspect --update-baseline\` run — it writes
   \`.blueprint-baseline.json\` only when debt exists; on a clean repo
   "No debt to lock" and no file IS the correct outcome
4. A short report: the layer table, debt counts by category, any cycles

Out of scope: fixing the debt. Existing violations are recorded in the
baseline and paid down later — do not refactor application code in this pass.

**Early exit is a legitimate verdict.** On a repo below the brownfield
threshold (${BROWNFIELD_MIN_FILES} source files) whose shape a framework
preset already fits, the correct conclusion is to run
\`npx blueprint init --preset\`, wire its outputs, delete this playbook and
the command file, and stop. Walking the full method on a starter is
ceremony, not judgment; this playbook earns its cost on repos whose layer
boundaries have grown fuzzy.

**An empty net is equally legitimate.** On a root-only app the layer rules
reach nothing — that is the true state, not a failure to fix. Never invent
a layer to make coverage non-zero (a \`*\` name, a glob contortion): root
files are wiring, and their hygiene (line counts, unused vars) belongs to
the project's own lint, not to a manufactured layer. The net starts biting
when code lands inside declared layers.

## Method

1. **Look for existing intent documents first.** An architecture config or doc
   already in the repo (\`structure.config.json\`, dependency-cruiser rules,
   \`docs/architecture*\`, \`CLAUDE.md\`/\`AGENTS.md\` sections, ADRs) is intent
   evidence *senior* to the import matrix: the matrix shows what the code
   *does*, those documents say what it *should* do. They also carry what the
   matrix cannot — the position of empty (zero-file) layers, selfOnly-style
   constraints, and ownership rules. Translate them; use the matrix to verify.
   Documents also go stale: cross-check every translated clause against the
   survey below. Where they disagree, the document governs *intent* (layer
   order, ownership) and the code governs *shape* (module layout) — downgrade
   the stale clause and record the conflict in your report. Flow documents
   often draw a DAG; blueprint's order is linear (a layer may import *any*
   later layer). Linearize, then verify against the matrix — linear is
   transitive, so it is usually a strict relaxation, not a real change.
2. **Study the survey evidence below.** Every number is deterministic fact
   from this repo; do not re-derive it by grepping.
3. **Decide what is a layer.** Top-level folders under \`src/\` are candidates;
   root files are app wiring (never a layer). Test plumbing (\`test/\`,
   \`__tests__/\`) belongs in \`testFiles\`, not in \`layers\`. A folder that
   exists but holds no source files usually signals declared intent — check
   the documents from step 1 before dropping it.
4. **Infer the one-way flow.** Order layers so the *majority* direction of the
   import matrix points downward. Counter-edges are debt to surface, not
   intent to encode — never contort the order to make findings zero.
5. **Choose module shape per layer.** High \`index\`-coverage child folders →
   \`module: { layout: 'folder', entry: 'index' }\` on that layer; plain files
   → the flat default. Mixed repos usually need per-layer overrides.
6. **Assign ownership.** A package imported by exactly one folder (see the
   concentration list) is an \`owns\` candidate for that layer.
7. **Write the config** with \`defineBlueprint\` (schema sketch below).
8. **Validate — the loop that keeps you honest.** Run \`npx blueprint inspect\`.
   A findings explosion (roughly more findings than source files, or one
   dominant rule everywhere) means you mistranslated intent — revisit the
   order or the module shapes. Converged means: every finding is explainable
   as real, nameable debt.
9. **Finish — and finish means integrated, not parked.** Run
   \`npx blueprint init\`, then \`npx blueprint inspect --update-baseline\`,
   write the report, and delete the two authoring files. The tool never
   touches files you own, so it leaves \`*.blueprint.*\` references next to
   them — **those references are your input, not the deliverable. Adoption
   is not done while any reference file remains:**
   - **Declare your own tool** in the config — \`emit: { agents: ['claude'] }\`
     (Claude Code) or \`['agents']\` (codex & friends) — so init generates one
     contract file, not one per tool nobody uses.
   - **Wire the lint.** If \`eslint.config.blueprint.mjs\` was written, merge
     it into the existing flat config: spread \`...emitLint(blueprint, …)\`
     (with the TS plugin on TypeScript projects), then resolve every rule
     conflict *explicitly* — house disable conventions, thresholds, rules an
     existing structure tool already enforces — and note each decision in the
     report. Before merging, run \`npx blueprint impact\`: it lints the layer
     files with only the emitted config and reports hits per rule, so every
     conflict is decided on numbers, not by reading the emitted config
     against the code. Mind flat-config semantics while merging: when two
     entries configure the same rule, the later entry *replaces* the earlier
     — nothing merges, and ordering alone cannot save a rule **both sides
     set** (\`no-restricted-imports\`, \`no-restricted-syntax\`): whichever
     comes later silently deletes the other's defense while lint stays
     green. Combine both option sets into ONE entry — blueprint's patterns
     and selectors plus your own — and \`blueprint doctor\` verifies the
     emitted structural rules survived the merge. Run the project's own lint command; new findings introduced by
     the merge are fixed or explicitly judged, never left dangling. Delete
     the reference once wired. Exception: a **legacy-format config**
     (\`.eslintrc.*\`) needs a flat-config/ESLint-9 migration that can break
     the project's own lint pipeline — do not do that unilaterally; surface
     it as a decision item in the report instead.
   - **Red is correct — ratchet it, don't mute it.** Keep severity at
     \`error\`; adoption's job is to make debt visible and lock it, not to
     quiet the screen. Lock each side in its native ledger: architecture
     findings via \`npx blueprint inspect --update-baseline\`, lint
     violations via \`npx eslint . --suppress-all\` (ESLint ≥ 9.24 — counts
     per file × rule, so NEW violations still fail). CI then blocks only new
     debt on both gates, and \`blueprint doctor\` verifies neither ledger has
     gone stale. The inverse is equally correct: **zero findings and zero
     lint hits is a complete outcome** — the ledgers simply stay absent
     (plain \`inspect\` and the project's own lint are the gates), and
     manufacturing debt just to demo the ratchet is mistranslation, not
     adoption. Still on ESLint 8 / a legacy config? Transitional fallback:
     \`emit: { lint: { severity: 'warn' } }\` — but state the cost in the
     report: severity only covers the structural rules, so until the
     migration, new metric debt (maxLines…) is not gated.
   - **If a hand-written CLAUDE.md / AGENTS.md exists**, integrate the
     \`<name>.blueprint.md\` reference into the existing document following
     *its* structure — link, don't duplicate; keep project facts to one
     screen — then delete the reference.
   - **If the repo already runs an overlapping structure tool** (e.g.
     structure-lint, dependency-cruiser), say so in the report: blueprint's
     lint layer duplicates it, and consolidating onto one gate is a scope
     decision for the user — flag it, don't decide it. **Exception:** when
     the existing tool configures the *same ESLint rules* emitLint emits
     (\`no-restricted-imports\`, \`no-restricted-syntax\`), coexistence is
     mechanically impossible — the entries overwrite each other and
     doctor's survival check fails. There, consolidation stops being a
     scope decision and becomes a wiring precondition; do it, and name
     which gate won in the report.

## Semantics the linter holds you to

Facts about the emitted rules that drive authoring decisions — stated here so
you never have to reverse-engineer them from the bundle:

- **Flat layout:** the module is the whole layer, so same-layer *relative*
  imports are always legal. The alias is for crossing layers — a same-layer
  import through the alias becomes an error the moment the lint is wired.
- **Folder layout:** a module is one child folder with private internals.
  *Same-layer* sibling modules must not import each other at all — via the
  alias or \`../\` alike; the shared part wants to live in a lower layer.
  Only *lower-layer* folder modules are importable, and entry-only; \`../\`
  escapes are caught at any depth by \`blueprint/relative-escape\`.
- **Pre-wiring check:** the survey's "Same-folder imports via the alias"
  count is exactly how many errors the wiring will introduce, and the fix is
  layout-dependent — flat: rewrite them as relative imports; folder: extract
  the shared code downward (a relative rewrite just trades the error for
  \`relative-escape\`). Whatever stays unresolved lands in the suppressions
  ledger. Once the config exists, \`npx blueprint impact\` reports the full
  per-rule count.
- **\`unusedVars\`** emits with \`argsIgnorePattern: '^_'\` and nothing else:
  \`_\`-prefixed *arguments* are exempt; unused variables and catch
  parameters are not.
- **\`doctor\`'s "eslint wired" check** passes when the eslint config's text
  references \`@kekkai/blueprint\` (or the config is the generated file
  itself).

## Config schema sketch

\`\`\`js
import { defineBlueprint } from '@kekkai/blueprint';

export default defineBlueprint({
  name: '<project>',
  framework: '<vue|react>',
  architecture: {
    alias: '<alias>',
    layers: [
      // Order defines the one-way flow: a layer may import only layers
      // declared AFTER it. allowedImporters (optional) narrows who may
      // import a layer; selfOnly = depend on it but never re-export it.
      { name: 'pages', does: '<one-line responsibility>' },
      {
        name: 'features',
        does: '…',
        module: { layout: 'folder', entry: 'index' }, // per-layer override
      },
      { name: 'services', does: '…', owns: ['axios'] },
    ],
    flow: 'one-way',
    module: { layout: 'flat', entry: 'index', private: [] },
    layerFiles: 'src/{layer}/**/*.<ext glob>',
    testFiles: ['**/*.test.*', '**/__tests__/**'],
  },
  rules: { cycles: 'error', unusedVars: 'error' },
});
\`\`\`

## Acceptance gates

- [ ] \`npx blueprint inspect\` findings are all explainable as real debt
- [ ] \`npx blueprint inspect --baseline\` exits 0 — ledger locked when debt
      exists, correctly absent when it does not
- [ ] The blueprint lint rules run inside the project's own lint command
      (merged, conflicts resolved) — or the legacy-config migration is a named
      decision item in the report
- [ ] No \`*.blueprint.*\` reference file remains in the repo
- [ ] The report names every import cycle and every upward dependency found

## If you stop midway

Nothing is lost. This playbook and the survey stay on disk; \`inspect\` is
read-only, \`init\` is idempotent, and the baseline is only written at the
final step. A human (or another agent) resumes from the same loop.

## Survey evidence

\`\`\`
${renderSurvey(survey)}
\`\`\`
`;
}
