import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { runInit } from './bootstrap';
import { reactPreset, vuePreset } from '../presets';

let root: string;

beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'bp-init-'));
});

afterEach(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

function writePkg(content: Record<string, unknown>): void {
  fs.writeFileSync(path.join(root, 'package.json'), JSON.stringify(content));
}

const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf-8');
const exists = (file: string) => fs.existsSync(path.join(root, file));

const silent = () => {};

describe('runInit · artifact hygiene', () => {
  it('regenerates its own eslint config in place instead of writing a reference', async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });

    await runInit(root, { install: false, log: silent });
    expect(read('eslint.config.mjs')).toContain('Generated by @kekkai/blueprint init');

    const again = await runInit(root, {
      install: false,
      log: silent,
      loadConfig: async () => vuePreset({ name: 'demo' }),
    });

    expect(again.some(
      (action) => action.kind === 'write' && action.path === 'eslint.config.mjs',
    )).toBe(true);

    expect(exists('eslint.config.blueprint.mjs')).toBe(false);
  });

  it('still treats a hand-made eslint config as brownfield', async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });
    fs.writeFileSync(path.join(root, 'eslint.config.mjs'), 'export default [];');

    await runInit(root, { install: false, log: silent });

    expect(read('eslint.config.mjs')).toBe('export default [];');
    expect(exists('eslint.config.blueprint.mjs')).toBe(true);
  });

  it('re-includes gitignored artifacts via negations instead of instructing (field '
    + '#4)', async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });
    fs.writeFileSync(path.join(root, '.gitignore'), 'CLAUDE.md\ndocs\n');

    await runInit(root, { install: false, log: silent });

    const gitignore = read('.gitignore');

    // Original content preserved; negations appended (they win by coming later).
    expect(gitignore).toContain('CLAUDE.md\ndocs\n');
    expect(gitignore).toContain('!CLAUDE.md');
    expect(gitignore).toContain('!docs/architecture-handbook.md');
    expect(gitignore).toContain('keep them tracked');

    // Idempotent: the negations satisfy the matcher, so a re-run appends
    // nothing (loadConfig injected — the scaffolded config imports the
    // package, which the offline test env cannot resolve).
    await runInit(root, { install: false, log: silent, loadConfig: async () => vuePreset() });

    expect(read('.gitignore').match(/!CLAUDE\.md/g)).toHaveLength(1);
  });

  it('joins the negation block on with exactly one blank line, '
    + 'whatever the file ended in', async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });
    // How many trailing newlines a .gitignore carries is an editor accident;
    // the seam this write produces must not be.
    fs.writeFileSync(path.join(root, '.gitignore'), 'CLAUDE.md\ndocs\n\n\n');

    await runInit(root, { install: false, log: silent });

    // Anchored at the start, with the blank lines counted: a leading blank
    // line or a surviving run of trailing ones both show up as an unexplained
    // edit in a file people read as a diff.
    expect(read('.gitignore')).toMatch(/^CLAUDE\.md\ndocs\n\n# @kekkai/);
  });

  it('states the edit and the directory-exclusion caveat in the note', async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });
    fs.writeFileSync(path.join(root, '.gitignore'), 'AGENTS.md\n');

    const actions = await runInit(root, { install: false, log: silent });

    const patch = actions.find(
      (action) => action.kind === 'write' && action.path === '.gitignore',
    );

    expect(patch?.note).toContain('re-included AGENTS.md');
    // The rule that hid it, not only the file. Without it a reader can only check
    // the claim AFTER the negation lands, where `git check-ignore` answers "not
    // ignored" — the fix working, which reads exactly like a fix that was never
    // needed. A field agent filed it as a no-op on that reading.
    expect(patch?.note).toContain('hidden by `AGENTS.md`');
    expect(patch?.note).toContain('delete the appended lines to keep it hidden');
    expect(patch?.note).toContain('parent directory');
    expect(read('.gitignore')).toContain('!AGENTS.md');
  });

  it('phrases the greenfield --agent skip by what happened', async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });

    const logs: string[] = [];

    await runInit(root, {
      install: false,
      agent: 'claude',
      spawn: () => {
        throw new Error('must not spawn');
      },
      log: (message) => logs.push(message),
    });

    expect(logs.join('\n')).toContain('fresh scaffold, nothing to author');
  });
});

describe('runInit · wired eslint config detection', () => {
  it('stops nagging once the user config imports @kekkai/blueprint', async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });

    fs.writeFileSync(
      path.join(root, 'eslint.config.mjs'),
      [
        'import { emitLint } from \'@kekkai/blueprint\';',
        'import blueprint from \'./blueprint.config.mjs\';',
        'export default [...emitLint(blueprint)];',
      ].join('\n'),
    );

    const actions = await runInit(root, { install: false, log: silent });

    expect(exists('eslint.config.blueprint.mjs')).toBe(false);
    expect(read('eslint.config.mjs')).toContain('emitLint(blueprint)');

    expect(actions.some(
      (action) => action.kind === 'instruct' && action.note.includes('already wires'),
    )).toBe(true);
  });
});

describe('runInit · how the plan is reported', () => {
  it('lists the plan up front only in dry-run', async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });

    const dry: string[] = [];

    await runInit(root, { dryRun: true, install: false, log: (m) => dry.push(m) });

    expect(dry.join('\n')).toContain('would write');

    const applied: string[] = [];

    await runInit(root, { install: false, log: (m) => applied.push(m) });

    // Outside dry-run the applied lines ARE the report. A "would" among them
    // claims something about disk that already happened, or did not.
    expect(applied.join('\n')).not.toContain('would ');
    expect(applied.join('\n')).toContain('✓ write:');
  });

  it('marks an instruction with a bullet, never with an effect mark', async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });

    const lines: string[] = [];

    await runInit(root, { install: false, log: (m) => lines.push(m) });
    const out = lines.join('\n');

    // An instruction reports nothing about disk. Wearing the ✓ of the writes
    // around it, it skims past as one more thing that happened — the same
    // confusion the − mark for deletions exists to prevent (field issue #36).
    expect(out).toContain('  · ');
    expect(out).not.toContain('✓ instruct:');
  });
});

describe('runInit · default agent targets are surfaced', () => {
  it('suggests emit.agents when both default contracts are written', async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });

    const actions = await runInit(root, { install: false, log: silent });

    expect(
      actions.some(
        (action) => action.kind === 'instruct' && action.note.includes('emit.agents'),
      ),
    ).toBe(true);
  });
});

describe('runInit · the codeStyle heads-up is scoped to a fresh scaffold', () => {
  it('announces what codeStyle will demand when init generated the config', async () => {
    writePkg({ name: 'demo', dependencies: { react: '^18' } });

    const actions = await runInit(root, { install: false, log: silent });

    expect(actions.some(
      (action) => action.kind === 'instruct' && action.note.includes(
        '`codeStyle` on at error tier',
      ),
    )).toBe(true);
  });

  it('says nothing when the config was already the repo\'s own', async () => {
    // The owner already chose; there is nothing to announce. Both halves matter — a
    // repo with its own config and codeStyle at error tier must stay quiet, which is
    // what stops the condition collapsing to its second half.
    writePkg({ name: 'demo', dependencies: { react: '^18' } });
    fs.writeFileSync(path.join(root, 'blueprint.config.mjs'), '// user config');

    const actions = await runInit(root, {
      install: false,
      log: silent,
      loadConfig: async () => reactPreset({ name: 'demo' }),
    });

    expect(actions.some(
      (action) => action.kind === 'instruct' && action.note.includes('codeStyle` on at error tier'),
    )).toBe(false);
  });
});

describe('runInit · what a second run must not repeat', () => {
  const secondRun = async () => {
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });
    await runInit(root, { install: false, log: silent });

    const lines: string[] = [];

    const actions = await runInit(root, {
      install: false,
      log: (m) => lines.push(m),
      loadConfig: async () => vuePreset(),
    });

    return { actions, out: lines.join('\n') };
  };

  it('narrates no fork, no template cleanup, and no introduced alias', async () => {
    const { actions, out } = await secondRun();

    // The fork note only exists on the path that made the fork decision. Logging
    // it unconditionally prints "· null" — a bullet with no content, which reads
    // as a message init failed to fill in.
    expect(out).not.toContain('· null');

    // Template cleanup describes starter-template code the PRESET just landed
    // on. On a repo whose config already existed, nothing was scaffolded, so a
    // cleanup to-do points at violations init did not introduce.
    expect(actions.some(
      (action) => action.kind === 'instruct' && action.note.includes('starter template'),
    )).toBe(false);

    // Same for the alias: this repo has no tsconfig alias, but init introduced
    // nothing on this run — the alias came from the config that was already here.
    expect(actions.some(
      (action) => action.kind === 'instruct' && action.note.includes('first import alias'),
    )).toBe(false);
  });

  it('does not report an agent flag that was not passed', async () => {
    const { out } = await secondRun();

    // The line explains what `--agent` did. Printing it without the flag says
    // "--agent undefined", which reads as a flag init mangled.
    expect(out).not.toContain('--agent undefined');
    expect(out).not.toContain('nothing to author');
  });

  it('stays quiet about the default target set once the config declares one', async () => {
    // The note exists to surface a narrowing the user has not made yet. Once
    // `emit.agents` is in the config, repeating it tells them to declare
    // something they already declared.
    writePkg({ name: 'demo', dependencies: { vue: '^3' } });
    await runInit(root, { install: false, log: silent, agent: 'claude' });

    const actions = await runInit(root, {
      install: false,
      log: silent,
      loadConfig: async () => ({ ...vuePreset(), emit: { agents: ['claude' as const] } }),
    });

    expect(actions.some(
      (action) => action.kind === 'instruct' && action.note.includes('Wrote both'),
    )).toBe(false);
  });
});
