import type { Finding } from '../inspect';
import type { ProjectState } from '../project';
import type { ModuleToLayerEvidence } from '../survey';
import type { TransformationPreflight } from './preflight';

export interface ModuleToLayerBriefFacts {
  evidence: ModuleToLayerEvidence;
  preflight: TransformationPreflight;
  findings: Finding[];
  state: ProjectState;
  install: string;
  cleanup: string;
}

export function moduleToLayerBrief(facts: ModuleToLayerBriefFacts): string {
  return [
    header(facts.cleanup),
    snapshot(facts),
    mapping(facts.evidence),
    decisions(facts.state),
    movement(),
    cutover(facts.evidence),
    baseline(facts.findings),
    verification(facts.install, facts.cleanup),
  ].join('\n');
}

function header(cleanup: string): string {
  return [
    '# Blueprint module-first → layer-first transformation playbook',
    '',
    '> Generated by `blueprint init --topology layer-first` after topology decision and Git',
    '> preflight. The CLI measured structural destinations and risks; you own collision names,',
    '> router semantics, import rewrites, and the final reviewed cutover.',
    `> When complete, delete ${cleanup}`,
    '',
    '## Goal and boundary',
    '',
    'Flatten one selected module-first application back to its global layer axis. Keep the',
    'starting commit, source, config, baseline, and generated artifacts recoverable until the',
    'new tree is verified. Use `git mv` for tracked source and never overwrite a collision.',
    '',
    'The destination table below is deterministic evidence, not an automatic migration plan.',
    'Do not introduce a transformer, codemod, formatter pass, or old-module-DAG replacement.',
  ].join('\n');
}

function snapshot(facts: ModuleToLayerBriefFacts): string {
  const { evidence, preflight, state } = facts;

  return [
    '',
    '## Measured transformation snapshot',
    '',
    '- Current topology: `module-first`',
    '- Target topology: `layer-first`',
    `- Framework/router: \`${state.framework ?? 'unknown'}\`${state.hasNext ? ` / Next.js ${state.nextRouter ?? 'unresolved'} Router` : ''}`,
    `- Selected source root/application scope: \`${evidence.sourceRoot}\``,
    `- Recoverable starting commit: \`${preflight.head.commit}\``,
    `- Git worktree at preflight: clean (${preflight.worktree.changes?.length ?? 0} changes)`,
    `- Canonical source-root alias: \`${evidence.architectureBasis.alias}\` → \`${evidence.sourceRoot}\``,
    `- Pre-transform additional aliases: ${additionalAliases(evidence)}`,
    `- Source-root bootstrap/wiring: ${list(evidence.rootWiring)}`,
    `- Module DAG before movement: ${moduleList(evidence.modules)}`,
    `- Canonical governed unit edges: ${edgeList(evidence.edges)}`,
    `- Import-analysis limits: ${evidence.unknownDynamicImports} runtime-dependent dynamic import(s), ${evidence.parseFailures.length} parse failure(s)`,
    '',
    'Source-root bootstrap/provider wiring stays at the source root. The module DAG is migration',
    'evidence only; it disappears after final placement passes the layer-first rules.',
  ].join('\n');
}

function mapping(evidence: ModuleToLayerEvidence): string {
  return [
    '',
    '## Complete structural destination table',
    '',
    ...(evidence.mappings.length
      ? evidence.mappings.map((entry) => [
          `- \`${entry.source}\` → \`${entry.destination}\``,
          `  (${entry.module}; ${entry.layer}; ${entry.layout}; ${entry.disposition})`,
        ].join('\n'))
      : ['- (no governed source mapping was measured; stop before movement)']),
    '',
    'Folder-layout units retain their unit directories and file-layout units retain file-level',
    'identity. Ordinary module-root/container-position source maps below `containers/<module>`.',
    'A listed destination is never permission to overwrite an existing or incoming file.',
    '',
    '### Additional-alias cutover',
    '',
    ...(evidence.aliasCutovers.length
      ? evidence.aliasCutovers.map((entry) => [
          `- \`${entry.alias}\` → \`${entry.target}\` · ${entry.disposition}`,
          `  mapped files → ${list(entry.mappedDestinations)}`,
        ].join('\n'))
      : ['- (none configured)']),
    '',
    'A `rewrite-or-remove` alias is deliberately absent from the proposed architecture basis.',
    'Map it to one verified final target only when that target still represents every use;',
    'otherwise rewrite every import to the canonical source-root alias, then remove the alias',
    'from config and toolchain wiring.',
    'Never preserve an alias that points at an obsolete module path.',
    '',
    '### Destination collisions',
    '',
    ...(evidence.collisions.length
      ? evidence.collisions.map((entry) =>
          `- \`${entry.destination}\` ← ${entry.sources.map((source) => `\`${source}\``).join(', ')}`)
      : ['- (none measured)']),
    '',
    `Ungoverned/orphan source: ${list(evidence.orphans)}`,
    `Cycles in pre-transform governed graph: ${evidence.cycles.map((cycle) => cycle.join(' → ')).join('; ') || '(none)'}`,
    `Unresolved alias-like imports: ${evidence.unresolvedAliasLikeImports.map((entry) => `${entry.unit}: ${entry.specifier}`).join('; ') || '(none)'}`,
    `Relative import structural evidence: ${relativeImports(evidence)}`,
    ...evidence.parseFailures.map((failure) => `Parse failure: ${failure.path} — ${failure.message}`),
    '',
    'Relative evidence uses Blueprint’s canonical resolver. It does not prove exact extension,',
    'index resolution, or runtime-dependent imports; keep every unverified import explicit.',
  ].join('\n');
}

function decisions(state: ProjectState): string {
  const router = state.hasNext
    ? [
        'This is a Next.js App Router application. Preserve every physical `app/**` route segment',
        'and framework file in place. At cutover it becomes the governed layer-first route surface',
        'and no longer carries module DAG identity.',
      ]
    : [
        'For React/Vue, classify each reserved `app/**` file as page/route composition, router',
        'registration, bootstrap/provider wiring, or misplaced domain code. Move composition to',
        '`pages/**` or the existing route surface; keep wiring at the source root. Place domain',
        'code by responsibility. A nested `app/**` path is not automatically a page.',
      ];

  return [
    '',
    '## Agent-owned semantic decisions',
    '',
    '1. Resolve every exact and case-insensitive destination collision before moving anything.',
    '   Qualify or regroup colliding names by domain evidence; never invent numeric suffixes.',
    '2. Decide whether ambiguous module-root code needs splitting or consolidation under',
    '   `containers/<module>`, and whether providers or route support belong elsewhere.',
    '3. Abort rather than normalize an invalid or hybrid tree whose identity cannot be proven.',
    ...router,
  ].join('\n');
}

function movement(): string {
  return [
    '',
    '## Filesystem movement and import rewrite',
    '',
    '1. Record the approved source → destination table and collision decisions in the handoff.',
    '2. Use `git mv` for every tracked move. Flatten declared inner layers into their global',
    '   layer surfaces and map ordinary module roots below `containers/<module>`.',
    '3. Rewrite static imports, statically determinable dynamic imports, and every affected',
    '   additional-alias use through the canonical source-root alias. Preserve source-root wiring',
    '   and framework route locations.',
    '4. Account for every source file before removing obsolete empty module directories.',
  ].join('\n');
}

function cutover(evidence: ModuleToLayerEvidence): string {
  return [
    '',
    '## Layer-first config and synchronized cutover',
    '',
    `- Existing inner-layer order and unit contracts: ${layerList(evidence.layers)}`,
    '- Proposed layer-first architecture basis (module declarations removed; route/container',
    '  surfaces still require the placement decision below):',
    '',
    '```json',
    JSON.stringify(evidence.architectureBasis, null, 2),
    '```',
    '- The CLI does not auto-sort layers merely to make a graph acyclic. Keep the existing',
    '  order as the starting authority; the Agent places the route surface and `containers`',
    '  according to existing product contracts and resulting imports.',
    `- Preserve source root \`${evidence.sourceRoot}\` and its canonical alias`,
    `  \`${evidence.architectureBasis.alias}\`. Preserve only additional aliases marked`,
    '  `preserve`; retarget or remove every `rewrite-or-remove` alias after its imports move.',
    '- Preserve code-style rules, ownership clauses, unit layouts, emit targets, and project',
    '  contracts.',
    '- Remove `architecture.modules` and every `dependsOn` only when all governed source has a',
    '  valid layer-first identity. Do not translate module edges into an ad hoc dependency system.',
    '- Restore or author the correct global layer order, including the framework route surface.',
    '- Apply source placement, imports, config, emitted ESLint, handbook, and Agent contracts as',
    '  one reviewable cutover. Then require resolver, inspect, deps, and ESLint to agree.',
    '',
    'If an import is illegal under the final one-way layer direction, change the semantic',
    'placement or dependency—not the rule—and do not retain a hybrid topology.',
  ].join('\n');
}

function baseline(findings: Finding[]): string {
  return [
    '',
    '## Baseline review — never rewrite old paths mechanically',
    '',
    `Pre-transform inspection recorded ${findings.length} finding(s):`,
    ...(findings.length
      ? findings.map((finding) =>
          `- ${finding.rule} · ${finding.path} · ${finding.subject || '(no subject)'}`)
      : ['- (none)']),
    '',
    'After cutover, run plain `npx blueprint inspect --json` before updating the baseline.',
    'Compare findings by meaning: pre-existing debt under a new identity, understood migration',
    'residue, or new transformation regression. Fix new regressions first. Only then regenerate',
    'the baseline and rerun inspect, deps, emitted ESLint, and adopter gates.',
  ].join('\n');
}

function verification(install: string, cleanup: string): string {
  return [
    '',
    '## Verification and handoff',
    '',
    'If the package needed by the generated config is missing:',
    '',
    '```bash',
    install,
    '```',
    '',
    'Then run and inspect:',
    '',
    '```bash',
    'git status --short',
    'git diff --stat',
    'git diff --summary',
    'npx blueprint inspect --json',
    'npx blueprint deps --json',
    'npx blueprint inspect --update-baseline',
    'npx blueprint inspect --baseline',
    'npx blueprint init --topology layer-first --no-install',
    'npx blueprint doctor --json',
    '# then the adopter repository’s lint, typecheck, test, and build commands',
    '```',
    '',
    'Add a legal higher→lower import as a positive control and a forbidden lower→higher import',
    'as a temporary negative control. The negative probe must fail through inspect and emitted',
    'ESLint; remove it and rerun. Confirm static and supported dynamic imports still resolve.',
    'Confirm every configured alias target exists and no import or toolchain path still names an',
    'obsolete module directory.',
    '',
    `Delete ${cleanup} Cleanup must happen before the final doctor run. Report the before/after`,
    'tree, tracked-move evidence, collision/router decisions, removed module DAG, layer direction,',
    'baseline classification, inspect/deps/ESLint agreement, adopter gates, and unverified',
    'imports.',
  ].join('\n');
}

function relativeImports(evidence: ModuleToLayerEvidence): string {
  return evidence.relativeImports.map((entry) => [
    `${entry.importer}: ${entry.specifier}`,
    `→ ${entry.structuralTarget ?? '(outside governed structure)'}`,
    `(${entry.targetUnitMeasured ? 'target unit measured' : 'target unit not measured'})`,
  ].join(' ')).join('; ') || '(none)';
}

function edgeList(edges: ModuleToLayerEvidence['edges']): string {
  return edges.length
    ? edges.map((edge) => `${edge.from} → ${edge.to} (${edge.count})`).join('; ')
    : '(none)';
}

function additionalAliases(evidence: ModuleToLayerEvidence): string {
  return evidence.aliasCutovers.length
    ? evidence.aliasCutovers.map((entry) =>
        `\`${entry.alias}\` → \`${entry.target}\``).join(', ')
    : '(none)';
}

function moduleList(modules: ModuleToLayerEvidence['modules']): string {
  return modules.length
    ? modules.map((module) =>
        `${module.name} → [${module.dependsOn.join(', ')}]`).join('; ')
    : '(none)';
}

function layerList(layers: ModuleToLayerEvidence['layers']): string {
  return layers.length
    ? layers.map((layer) =>
        `${layer.name} (${layer.layout}; entry ${layer.entry})`).join(' → ')
    : '(none)';
}

function list(values: string[]): string {
  return values.length ? values.map((value) => `\`${value}\``).join(', ') : '(none)';
}
