import { COMMAND_FILE } from '../project';
import type { ClaudeDirState } from '../project';

/**
 * The playbook's frame — the title block, the prerequisites and the goal — plus
 * the two passages more than one section renders. `authoringBrief`'s call list is
 * the table of contents, and a passage used twice is one function: `verdict.ts`,
 * `method.ts`, `merge.ts` and `catalog.ts` quote these two rather than restate
 * them.
 */

/** A repo counts as brownfield when src/ already holds this many source files. */
export const BROWNFIELD_MIN_FILES = 10;

/**
 * The four facts that make a *correct* resolved config look broken, for the two
 * paths reaching `--print-config`. Each caller opens the sentence itself, where
 * the framing genuinely differs; this carries the part that must not.
 *
 * `indent` is the caller's continuation indent. Lines are wrapped for the deeper
 * of the two and reused at the shallower; the first carries no indent, since it
 * continues the caller's own line.
 */
export function printConfigCaveats(): string {
  return [
    ', or a correct config looks broken: resolved keys carry their plugin prefix '
    + '(`@stylistic/max-len`, never bare `max-len`); '
    + 'a rule scoped to a net that holds no files does not appear at all (inspect\'s '
    + '`declaratory-self-only` note, not a loss); '
    + 'selfOnly\'s re-export ban resolves on the IMPORTER net inspect names, '
    + 'not on the net being protected; and **inspect\'s finding names are not ESLint rule '
    + 'ids** — `deep-import`, `flow-violation` and `package-ownership` all fold into the single '
    + '`no-restricted-imports` entry, so searching for `blueprint/deep-import` finds nothing and '
    + 'proves nothing.',
    'Inspect\'s migration steps name the carrying rule for each finding, '
    + 'and mark the ones no lint run will ever show.',
  ].join(' ');
}

/**
 * What authoring leaves behind — the two files AND the directories init created
 * for them, with `claudeDir` deciding whether `.claude/` is one. One passage, four
 * call sites including the banner: doctor's leftover check matches file families
 * and never looks at a directory, so nothing downstream catches a copy that drops
 * the directories (field runs #124, #145).
 */
export function cleanupTargets(claudeDir: ClaudeDirState): string {
  // The owner's own commands live here too, and "now-empty" was asserted about a
  // directory the tool can read. Half of this sentence was already measured — the
  // `.claude/` arm — so a field agent with `my-existing-command.md` beside blueprint's
  // got the pre-existing `.claude/` right and `commands/` wrong in the same breath
  // (field run #139). Nothing about `.claude/` needs deciding when its child stays.
  if (claudeDir.otherCommands > 0) {
    return `this playbook and \`${COMMAND_FILE}\`, and nothing else: `
      + `\`.claude/commands/\` holds ${claudeDir.otherCommands} other command file(s) that `
      + 'are the owner\'s, so it and `.claude/` both stay.';
  }

  return [
    `this playbook, \`${COMMAND_FILE}\`, and the now-empty`,
    ...(claudeDir.hadDir
      ? [
          '`.claude/commands/` directory — but NOT `.claude/` itself: '
          + 'it was already here before this run, so it is the owner\'s, '
          + 'whatever ends up left in it.',
        ]
      : [
          '`.claude/commands/` directory — and `.claude/` itself, '
          + 'which init created only to hold this command (it was not here before this run).',
        ]),
  ].join(' ');
}

/**
 * The Next.js addendum, appended to the H1 — the route tree is itself a layer,
 * and `src/pages` beside the App Router is a routing convention, not a layer to
 * scaffold. Empty on every other framework.
 */
export function renderNextNote(next: boolean): string {
  if (!next) {
    return '';
  }

  return [
    '',
    '',
    '> **Next.js project.** The route tree (`app/`, or `pages/` on the Pages Router) '
    + 'is itself a layer — declare it at the top of the flow (a typical shape: '
    + '`app` → `components` → `hooks` → `lib`).',
    '> Never scaffold or declare an empty `src/pages` alongside the App Router: '
    + 'that folder name is a routing convention.',
    '> Flat folder layout fits the route tree — '
    + 'relative imports stay free inside a segment while cross-layer traffic uses the alias.',
  ].join('\n');
}

/**
 * Title, the provenance banner, and the two conditional blocks that ride with
 * them. The banner states the deletion up front because `doctor` treats this
 * file and the command file as leftovers while they remain.
 */
export function renderHeader(
  nextNote: string,
  verdict: string,
  claudeDir: ClaudeDirState,
): string {
  return [
    `# Blueprint authoring playbook${nextNote}`,
    '',
    `> Generated by \`blueprint init\`.`,
    `> Execute top to bottom, autonomously — do not stop to ask for confirmation.`,
    `> When you finish, delete ${cleanupTargets(claudeDir)} Then \`blueprint doctor\` has the final word: it flags the two files as leftovers while they remain.${verdict}`,
  ].join('\n');
}

/**
 * The one precondition: the package must be a devDependency, because the config
 * the agent writes imports it and every `npx blueprint` step resolves it from
 * the project.
 */
export function renderPrerequisites(install: string): string {
  return [
    '',
    '## Prerequisites',
    '',
    '`@kekkai/blueprint` must be a devDependency — the config you will write imports it, '
    + 'and every `npx blueprint` step resolves it from the project.',
    '`init` already installed it unless `--no-install` was passed; verify, or run:',
    '',
    '```bash',
    `${install}`,
    '```',
  ].join('\n');
}

/**
 * What is being installed and where the job stops: the four deliverables, the
 * no-refactor boundary, and the three verdicts an agent must be licensed to
 * reach — the preset early exit, the honestly empty net, and drafting before
 * reading. Each one exists because a field run talked itself out of it.
 */
export function renderGoal(): string {
  return [
    '',
    '## Goal and boundary',
    '',
    '**Know what you are installing.** Blueprint is a governance tool for AI-driven development: '
    + 'its job is to keep agents — including you, '
    + 'and every agent that touches this repo after you — '
    + 'from drifting outside the declared architecture.',
    'The strictness is the product, not a cost to negotiate down.',
    'When you feel the urge to soften a tier, skip a gate, or leave yourself an escape hatch, '
    + 'that urge is exactly what this tool exists to catch: install faithfully, '
    + 'and put disagreements in the report for the maintainer — never into a weakened config.',
    '',
    'Author `blueprint.config.mjs` for this repository so that its architecture rules match the '
    + 'code\'s *intent*, then generate the artifacts and lock the baseline.',
    'Deliverables:',
    '',
    '1. `blueprint.config.mjs` — validated, findings explainable',
    '2. `npx blueprint init` artifacts (lint config, handbook, agent contracts)',
    '3. `npx blueprint inspect --update-baseline` run — '
    + 'it writes `.blueprint-baseline.json` only when debt exists; '
    + 'on a clean repo "No debt to lock" and no file IS the correct outcome',
    '4. A short report: the layer table, debt counts by category, any cycles.',
    '   It is a message, not an artifact — deliver it as your closing reply to the user (or the PR '
    + 'description when one is opened); never commit a report file',
    '',
    'Out of scope: fixing the debt.',
    'Existing violations are recorded in the baseline and paid down later — '
    + 'do not refactor application code in this pass.',
    '',
    `**Early exit is a legitimate verdict.** On a repo below the brownfield threshold (${BROWNFIELD_MIN_FILES} source files) whose shape a framework preset already fits, the correct conclusion is to run \`npx blueprint init --preset\`, wire its outputs, delete this playbook and the command file, and stop.`,
    `Walking the full method on a starter is ceremony, not judgment; this playbook earns its cost on repos whose layer boundaries have grown fuzzy.`,
    '',
    '**An empty net is equally legitimate.** On a root-only app the layer rules reach nothing — '
    + 'that is the true state, not a failure to fix.',
    'Never invent a layer to make coverage non-zero (a `*` name, a glob contortion): '
    + 'root files are wiring, and their hygiene (line counts, unused vars) '
    + 'belongs to the project\'s own lint, not to a manufactured layer.',
    'The net starts biting when code lands inside declared layers.',
    'The inverse also holds: a preset\'s declared-but-empty layers are the runway, '
    + 'not a manufactured net — declaring intent costs nothing and `inspect` tracks them '
    + 'honestly (missing-layer info, the coverage line), so keep them.',
    '**Runway comes in three shapes, and `inspect` names two of them.** An empty layer gets its '
    + 'note, and so does an `owns` entry for a package the repo has not installed (a preset\'s '
    + '`hooks` owns `zustand` whether or not you use it) — '
    + 'an `owns-not-installed` note naming the layer that declares it.',
    'An alias no import uses yet gets none — nothing imports it, '
    + 'so there is nothing to count and no finding to raise.',
    'All three are still runway: they say where a thing goes if it arrives, '
    + 'ban nothing until then, and need no dependency added to justify them.',
    'Keep them on the same default as the layers, '
    + 'and know that the alias is the one shape you have to recognize yourself rather than read '
    + 'off a report.',
    'Keeping is the DEFAULT — the preset layers are the baseline, '
    + 'and slimming them is the project owner\'s later decision, never the adopting agent\'s.',
    'When a declared-but-empty layer ALSO looks stale, the tiebreak is prose intent: '
    + 'an intent document describing it as a future seam makes it runway (keep); '
    + 'one the prose never mentions, contradicted by where the code actually lives, '
    + 'is a stale clause (downgrade it and record the conflict — Method step 1).',
    '**A drawn diagram is part of what that document says.** A layer absent from every per-layer '
    + 'section but still drawn in the same file\'s flow graph HAS been mentioned — '
    + 'read both before calling a clause unmentioned, '
    + 'or the tiebreak decides on half the evidence and drops a layer the document is still '
    + 'declaring.',
    '**Those two branches are not a partition, and the third state is the common one: mentioned, '
    + 'but nowhere described as intent.** A box in a diagram and nothing else is exactly that — '
    + 'it says the clause is not stale without saying it is a seam, so neither branch fires.',
    'Do not force it into one.',
    'Keeping is already the default, so keep it and hand the owner the specific question: '
    + 'this layer is drawn in <file> and described nowhere, '
    + 'and the code it names lives at <path> instead.',
    'That sentence is worth more than a verdict you reached by picking the nearer branch — '
    + 'the owner knows which of the two the drawing meant, and you do not.',
    'Adding a state to the diagram-mention rule is what opened this gap: '
    + 'broadening "mentioned" narrowed the stale branch and left the middle unowned, '
    + 'so it is named rather than implied.',
    '',
    '**Work the loop, not the archive.** Everything below is evidence and reference — '
    + 'it is NOT a syllabus to master before touching the config.',
    'Draft `blueprint.config.mjs` early from the survey and the rule catalog, '
    + 'then let `inspect` correct you: it is read-only, cheap, and needs nothing installed, '
    + 'and a wrong draft fixed in two runs beats a perfect draft after an hour of code '
    + 'archaeology.',
    '`impact` is the same kind of read-only feedback but is NOT available at this point — '
    + 'it lints with the emitted config, so it needs the plugins `init` installs; '
    + 'it joins the loop at Method step 9, after init.',
    'Reaching for it while drafting only earns you a load error.',
    'In field runs, agents that drafted first finished in a fraction of the time of agents that '
    + 'studied first — at the same quality, because the acceptance gates are the same.',
    'And if you ever feel the need to read the package\'s `dist/` bundle to answer a question, '
    + 'stop: the answer belongs in this playbook — note the gap in your report instead.',
  ].join('\n');
}
