import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { runInit } from '../bootstrap';
import { runInspect } from '../inspect';
import { reactPreset } from '../presets';

/**
 * Adoption end-to-end: real template shapes (committed under
 * fixtures/adoption/) copied to a tmpdir, then driven through the same
 * runInit / runInspect calls the CLI makes. This suite runs in the default
 * vitest set, so the husky pre-push hook and the release workflow both gate
 * on it before anything reaches npm.
 */

const FIXTURES = fileURLToPath(new URL('../../fixtures/adoption', import.meta.url));

let root: string;

const silent = () => {};

beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'bp-e2e-'));
});

afterEach(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

function useFixture(name: string): void {
  fs.cpSync(path.join(FIXTURES, name), root, { recursive: true });
}

const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf-8');
const exists = (file: string) => fs.existsSync(path.join(root, file));

describe('e2e · vite-react-ts (greenfield preset + alias surgery)', () => {
  it('wires the alias into vite.config and the commented tsconfig, and stays idempotent', async () => {
    useFixture('vite-react-ts');

    await runInit(root, { install: false, log: silent });

    // Vite surgery: resolve.alias + the node:url import, template shape intact.
    const vite = read('vite.config.ts');

    expect(vite).toContain('\'~app\': fileURLToPath(new URL(\'./src\', import.meta.url))');
    expect(vite).toContain('import { fileURLToPath, URL } from \'node:url\'');
    expect(vite).toContain('plugins: [react()]');

    // JSONC tsconfig surgery: paths inserted, comment preserved.
    const tsconfig = read('tsconfig.app.json');

    expect(tsconfig).toContain('"paths": { "~app/*": ["./src/*"] }');
    expect(tsconfig).toContain('/* Bundler mode */');

    expect(read('eslint.config.mjs')).toContain('Generated by @kekkai/blueprint init');

    // The tmpdir has no node_modules — inject the preset the config resolves to.
    const { ok } = await runInspect(root, { log: silent, loadConfig: async () => reactPreset() });

    expect(ok).toBe(true);

    // Second run: config exists → no greenfield surgery, files unchanged.
    await runInit(root, {
      install: false,
      log: silent,
      loadConfig: async () => reactPreset(),
    });

    expect(read('vite.config.ts')).toBe(vite);
    expect(read('tsconfig.app.json')).toBe(tsconfig);
  });
});

describe('e2e · vite-vue-ts (template cleanup)', () => {
  it('names the starter violations, then converges once imports move to the alias', async () => {
    useFixture('vite-vue-ts');

    const actions = await runInit(root, { install: false, log: silent });

    const cleanup = actions.find(
      (action) => action.kind === 'instruct' && action.note.includes('Template cleanup'),
    );

    expect(cleanup?.note).toContain('3 finding(s)');
    expect(cleanup?.note).toContain('src/components/HelloWorld.vue');
    expect(read('vite.config.ts')).toContain('\'~app\':'); // surgery ran here too

    const hello = path.join(root, 'src/components/HelloWorld.vue');

    fs.writeFileSync(
      hello,
      fs.readFileSync(hello, 'utf-8').replaceAll('../assets/', '~app/assets/'),
    );

    const { vuePreset } = await import('../presets');
    const { ok } = await runInspect(root, { log: silent, loadConfig: async () => vuePreset() });

    expect(ok).toBe(true);
  });
});

describe('e2e · next-app (authoring flow, hands off)', () => {
  it('routes to the playbook, never scaffolds src/pages, and leaves the agent files alone', async () => {
    useFixture('next-app');

    const actions = await runInit(root, { install: false, log: silent });

    expect(exists('blueprint-authoring.md')).toBe(true);
    expect(exists('src/pages')).toBe(false);
    expect(exists('blueprint.config.mjs')).toBe(false);
    expect(actions.some((action) => action.kind === 'mkdir')).toBe(false);

    const playbook = read('blueprint-authoring.md');

    expect(playbook).toContain('Next.js project');
    expect(playbook).toContain('npm install -D @kekkai/blueprint'); // lockfile → npm

    // The template's own agent files are untouched.
    expect(read('CLAUDE.md')).toBe('@AGENTS.md\n');
    expect(read('AGENTS.md')).toContain('nextjs-agent-rules');
  });
});

describe('e2e · turbo-pnpm (workspace package)', () => {
  it('detects pnpm from the workspace root and wires the package-local vite config', async () => {
    useFixture('turbo-pnpm');

    const pkg = path.join(root, 'apps', 'web');
    const commands: string[] = [];

    await runInit(pkg, {
      log: silent,
      exec: (command) => {
        commands.push(command);
      },
    });

    // Install commands come from the workspace's package manager.
    expect(commands.length).toBeGreaterThan(0);
    expect(commands.every((command) => command.startsWith('pnpm add -D'))).toBe(true);

    expect(fs.readFileSync(path.join(pkg, 'vite.config.ts'), 'utf-8')).toContain('\'~app\':');
    expect(fs.existsSync(path.join(pkg, 'blueprint.config.mjs'))).toBe(true);
    expect(fs.existsSync(path.join(root, 'blueprint.config.mjs'))).toBe(false); // package-local
  });
});

const BROWNFIELD_CONFIG = `// Authored during the e2e as the known-good translation of the fixture.
export default {
  name: 'brownfield-fixture',
  framework: 'react',
  architecture: {
    alias: '@',
    layers: [
      { name: 'pages', does: 'routes' },
      { name: 'features', does: 'feature slices' },
      { name: 'services', does: 'network', owns: ['axios'] },
      { name: 'utils', does: 'pure helpers' },
    ],
    flow: 'one-way',
    module: { layout: 'flat', entry: 'index', private: [] },
    layerFiles: 'src/{layer}/**/*.{ts,tsx}',
  },
  rules: { cycles: 'error' },
  emit: { agents: ['claude'] },
};
`;

describe('e2e · brownfield (the full adoption arc)', () => {
  it('walks authoring → findings → baseline → references → wired/integrated quiet', async () => {
    useFixture('brownfield');

    // 1. No config: authoring flow, hand-written files untouched.
    await runInit(root, { install: false, log: silent });

    expect(exists('blueprint-authoring.md')).toBe(true);
    expect(read('CLAUDE.md')).toContain('Do not clobber');
    expect(read('eslint.config.js')).toContain('hand-maintained');

    // 2. The authored config: inspect finds exactly the planted debt.
    fs.writeFileSync(path.join(root, 'blueprint.config.mjs'), BROWNFIELD_CONFIG);

    const { findings, ok } = await runInspect(root, { log: silent });

    const byRule = findings.reduce<Record<string, number>>((acc, finding) => {
      acc[finding.rule] = (acc[finding.rule] ?? 0) + 1;

      return acc;
    }, {});

    expect(ok).toBe(false);
    expect(byRule['flow-violation']).toBe(3); // same-layer + two upward reaches
    expect(byRule.cycle).toBe(1); // services → utils → services

    // 3. Baseline locks the debt; the ratchet goes green.
    await runInspect(root, { updateBaseline: true, log: silent });

    const ratchet = await runInspect(root, { baseline: true, log: silent });

    expect(ratchet.ok).toBe(true);

    // 4. init with the config: references land next to hand-written files.
    await runInit(root, { install: false, log: silent });

    expect(exists('CLAUDE.blueprint.md')).toBe(true);
    expect(exists('eslint.config.blueprint.mjs')).toBe(true);
    expect(read('CLAUDE.md')).toContain('Do not clobber'); // still untouched

    // 5. Simulate the agent finishing the integration; re-init goes quiet.
    fs.appendFileSync(
      path.join(root, 'CLAUDE.md'),
      '\n## Architecture contract\n\nSee node_modules/@kekkai/blueprint/agent-contract.md\n',
    );

    fs.writeFileSync(
      path.join(root, 'eslint.config.js'),
      'import { emitLint } from \'@kekkai/blueprint\';\nimport blueprint from \'./blueprint.config.mjs\';\nexport default [...emitLint(blueprint)];\n',
    );

    fs.rmSync(path.join(root, 'CLAUDE.blueprint.md'));
    fs.rmSync(path.join(root, 'eslint.config.blueprint.mjs'));

    const quiet = await runInit(root, { install: false, log: silent });

    expect(exists('CLAUDE.blueprint.md')).toBe(false);
    expect(exists('eslint.config.blueprint.mjs')).toBe(false);

    const notes = quiet
      .filter((action): action is Extract<typeof action, { kind: 'instruct' }> =>
        action.kind === 'instruct')
      .map((action) => action.note)
      .join('\n');

    expect(notes).toContain('already integrates');
    expect(notes).toContain('already wires');
  });
});
