import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { runInit } from '../bootstrap';
import { runInspect } from '../inspect';
import { reactPreset } from '../presets';

/**
 * Adoption end-to-end: real template shapes (committed under
 * fixtures/adoption/) copied to a tmpdir, then driven through the same
 * runInit / runInspect calls the CLI makes. This suite runs in the default
 * vitest set, so the husky pre-push hook and the release workflow both gate
 * on it before anything reaches npm.
 */

const FIXTURES = fileURLToPath(new URL('../../fixtures/adoption', import.meta.url));

let root: string;

const silent = () => {};

beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'bp-e2e-'));
});

afterEach(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

function useFixture(name: string): void {
  fs.cpSync(path.join(FIXTURES, name), root, { recursive: true });
}

const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf-8');
const exists = (file: string) => fs.existsSync(path.join(root, file));

describe('e2e · vite-react-ts (greenfield preset + alias surgery)', () => {
  it('wires the alias into vite.config and the commented tsconfig, and stays idempotent', async () => {
    useFixture('vite-react-ts');

    await runInit(root, { install: false, log: silent });

    // Vite surgery: resolve.alias + the node:url import, template shape intact.
    const vite = read('vite.config.ts');

    expect(vite).toContain('\'~app\': fileURLToPath(new URL(\'./src\', import.meta.url))');
    expect(vite).toContain('import { fileURLToPath, URL } from \'node:url\'');
    expect(vite).toContain('plugins: [react()]');

    // JSONC tsconfig surgery: paths inserted, comment preserved.
    const tsconfig = read('tsconfig.app.json');

    expect(tsconfig).toContain('"paths": { "~app/*": ["./src/*"] }');
    expect(tsconfig).toContain('/* Bundler mode */');

    expect(read('eslint.config.mjs')).toContain('Generated by @kekkai/blueprint init');

    // The tmpdir has no node_modules — inject the preset the config resolves to.
    const { ok } = await runInspect(root, { log: silent, loadConfig: async () => reactPreset() });

    expect(ok).toBe(true);

    // Second run: config exists → no greenfield surgery, files unchanged.
    await runInit(root, {
      install: false,
      log: silent,
      loadConfig: async () => reactPreset(),
    });

    expect(read('vite.config.ts')).toBe(vite);
    expect(read('tsconfig.app.json')).toBe(tsconfig);
  });
});

describe('e2e · vite-vue-ts (template cleanup)', () => {
  it('names the starter violations, then converges once imports move to the alias', async () => {
    useFixture('vite-vue-ts');

    const actions = await runInit(root, { install: false, log: silent });

    const cleanup = actions.find(
      (action) => action.kind === 'instruct' && action.note.includes('Template cleanup'),
    );

    expect(cleanup?.note).toContain('3 finding(s)');
    expect(cleanup?.note).toContain('src/components/HelloWorld.vue');
    expect(read('vite.config.ts')).toContain('\'~app\':'); // surgery ran here too

    const hello = path.join(root, 'src/components/HelloWorld.vue');

    fs.writeFileSync(
      hello,
      fs.readFileSync(hello, 'utf-8').replaceAll('../assets/', '~app/assets/'),
    );

    const { vuePreset } = await import('../presets');
    const { ok } = await runInspect(root, { log: silent, loadConfig: async () => vuePreset() });

    expect(ok).toBe(true);
  });
});

describe('e2e · next-app (App Router preset, hands off on owned files)', () => {
  it('scaffolds with nextPreset, never touches src/pages, leaves hand-written agent files alone', async () => {
    useFixture('next-app');

    await runInit(root, { install: false, log: silent });

    const config = read('blueprint.config.mjs');

    expect(config).toContain('nextPreset');
    expect(config).toContain('router: \'app\'');
    expect(config).toContain('srcDir: true');
    expect(exists('blueprint-authoring.md')).toBe(false); // preset path, not authoring
    expect(exists('src/pages')).toBe(false);

    // The template's own agent files are hand-written → left untouched, reference written.
    expect(read('CLAUDE.md')).toBe('@AGENTS.md\n');
    expect(read('AGENTS.md')).toContain('nextjs-agent-rules');

    // Its flat eslint config is not blueprint-owned → a reference is emitted.
    expect(exists('eslint.config.blueprint.mjs')).toBe(true);

    // inspect resolves the route tree under src/app and finds no violations.
    const { nextPreset } = await import('../presets');

    const { ok } = await runInspect(root, {
      log: silent,
      loadConfig: async () => nextPreset({ router: 'app', srcDir: true }),
    });

    expect(ok).toBe(true);
  });
});

describe('e2e · next-app-no-srcdir (root-level App Router)', () => {
  it('detects the root app/ tree and scans it via sourceRoot "."', async () => {
    useFixture('next-app-no-srcdir');

    await runInit(root, { install: false, log: silent });

    const config = read('blueprint.config.mjs');

    expect(config).toContain('router: \'app\'');
    expect(config).not.toContain('srcDir');

    const { nextPreset } = await import('../presets');

    const { ok, findings } = await runInspect(root, {
      log: silent,
      loadConfig: async () => nextPreset({ router: 'app' }),
    });

    // The root-level app/ + lib/ are seen; the planted upward import is caught.
    expect(findings.some((f) => f.rule === 'flow-violation')).toBe(true);
    expect(ok).toBe(false);
  });
});

describe('e2e · next-pages-router', () => {
  it('places the pages/ tree as the top layer under src/', async () => {
    useFixture('next-pages-router');

    await runInit(root, { install: false, log: silent });

    expect(read('blueprint.config.mjs')).toContain('router: \'pages\'');

    const { nextPreset } = await import('../presets');

    const { ok } = await runInspect(root, {
      log: silent,
      loadConfig: async () => nextPreset({ router: 'pages', srcDir: true }),
    });

    expect(ok).toBe(true);
  });
});

describe('e2e · turbo-pnpm (workspace package)', () => {
  it('detects pnpm from the workspace root and wires the package-local vite config', async () => {
    useFixture('turbo-pnpm');

    const pkg = path.join(root, 'apps', 'web');
    const commands: string[] = [];

    await runInit(pkg, {
      log: silent,
      exec: (command) => {
        commands.push(command);
      },
    });

    // Install commands come from the workspace's package manager.
    expect(commands.length).toBeGreaterThan(0);
    expect(commands.every((command) => command.startsWith('pnpm add -D'))).toBe(true);

    expect(fs.readFileSync(path.join(pkg, 'vite.config.ts'), 'utf-8')).toContain('\'~app\':');
    expect(fs.existsSync(path.join(pkg, 'blueprint.config.mjs'))).toBe(true);
    expect(fs.existsSync(path.join(root, 'blueprint.config.mjs'))).toBe(false); // package-local
  });
});

const BROWNFIELD_CONFIG = `// Authored during the e2e as the known-good translation of the fixture.
export default {
  name: 'brownfield-fixture',
  framework: 'react',
  architecture: {
    alias: '@',
    layers: [
      { name: 'pages', does: 'routes' },
      { name: 'features', does: 'feature slices' },
      { name: 'services', does: 'network', owns: ['axios'] },
      { name: 'utils', does: 'pure helpers' },
    ],
    module: { layout: 'flat', entry: 'index', private: [] },
    layerFiles: 'src/{layer}/**/*.{ts,tsx}',
  },
  rules: { cycles: 'error' },
  emit: { agents: ['claude'] },
};
`;

describe('e2e · brownfield (the full adoption arc)', () => {
  it('walks authoring → findings → baseline → references → wired/integrated quiet', async () => {
    useFixture('brownfield');

    // 1. No config: authoring flow, hand-written files untouched.
    await runInit(root, { install: false, log: silent });

    expect(exists('blueprint-authoring.md')).toBe(true);
    expect(read('CLAUDE.md')).toContain('Do not clobber');
    expect(read('eslint.config.js')).toContain('hand-maintained');

    // 2. The authored config: inspect finds exactly the planted debt.
    fs.writeFileSync(path.join(root, 'blueprint.config.mjs'), BROWNFIELD_CONFIG);

    const { findings, ok } = await runInspect(root, { log: silent });

    const byRule = findings.reduce<Record<string, number>>((acc, finding) => {
      acc[finding.rule] = (acc[finding.rule] ?? 0) + 1;

      return acc;
    }, {});

    expect(ok).toBe(false);
    expect(byRule['flow-violation']).toBe(3); // same-layer + two upward reaches
    expect(byRule.cycle).toBe(1); // services → utils → services

    // 3. Baseline locks the debt; the ratchet goes green.
    await runInspect(root, { updateBaseline: true, log: silent });

    const ratchet = await runInspect(root, { baseline: true, log: silent });

    expect(ratchet.ok).toBe(true);

    // 4. init with the config: references land next to hand-written files.
    await runInit(root, { install: false, log: silent });

    expect(exists('CLAUDE.blueprint.md')).toBe(true);
    expect(exists('eslint.config.blueprint.mjs')).toBe(true);
    expect(read('CLAUDE.md')).toContain('Do not clobber'); // still untouched

    // 5. Simulate the agent finishing the integration; re-init goes quiet.
    fs.appendFileSync(
      path.join(root, 'CLAUDE.md'),
      '\n## Architecture contract\n\nSee node_modules/@kekkai/blueprint/agent-contract.md\n',
    );

    fs.writeFileSync(
      path.join(root, 'eslint.config.js'),
      'import { emitLint } from \'@kekkai/blueprint\';\nimport blueprint from \'./blueprint.config.mjs\';\nexport default [...emitLint(blueprint)];\n',
    );

    fs.rmSync(path.join(root, 'CLAUDE.blueprint.md'));
    fs.rmSync(path.join(root, 'eslint.config.blueprint.mjs'));

    const quiet = await runInit(root, { install: false, log: silent });

    expect(exists('CLAUDE.blueprint.md')).toBe(false);
    expect(exists('eslint.config.blueprint.mjs')).toBe(false);

    const notes = quiet
      .filter((action): action is Extract<typeof action, { kind: 'instruct' }> =>
        action.kind === 'instruct')
      .map((action) => action.note)
      .join('\n');

    expect(notes).toContain('already integrates');
    expect(notes).toContain('already wires');
  });
});

// ─── Tier 1: cross-cutting behaviors the per-terrain happy paths don't cover ───

describe('e2e · ratchet catches a new violation (Tier 1)', () => {
  it('reddens only on debt introduced after the baseline is locked', async () => {
    useFixture('brownfield');
    fs.writeFileSync(path.join(root, 'blueprint.config.mjs'), BROWNFIELD_CONFIG);

    // Lock today's debt; the ratchet is green.
    await runInspect(root, { updateBaseline: true, log: silent });
    expect((await runInspect(root, { baseline: true, log: silent })).ok).toBe(true);

    // Introduce a NEW upward reach: utils → pages (not in the baseline).
    fs.writeFileSync(
      path.join(root, 'src/utils/noop.ts'),
      'import { Home } from \'@/pages/Home\';\nexport const noop = () => Home;\n',
    );

    const after = await runInspect(root, { baseline: true, log: silent });

    expect(after.ok).toBe(false);
    // Only the fresh finding surfaces — the baselined debt stays suppressed.
    expect(after.findings.every((f) => f.path.includes('utils/noop'))).toBe(true);
  });
});

describe('e2e · JS project gets a jsconfig (Tier 1)', () => {
  it('creates jsconfig.json with the alias and runs the vite surgery', async () => {
    useFixture('vite-react-js');

    await runInit(root, { install: false, log: silent });

    // No tsconfig anywhere → init creates jsconfig.json with the alias paths.
    expect(JSON.parse(read('jsconfig.json'))).toEqual({
      compilerOptions: { paths: { '~app/*': ['./src/*'] } },
    });

    expect(read('vite.config.js')).toContain('\'~app\': fileURLToPath(new URL(\'./src\', import.meta.url))');
  });
});

describe('e2e · --dry-run writes nothing (Tier 1)', () => {
  it('produces a full plan but leaves the filesystem untouched', async () => {
    useFixture('vite-react-ts');
    const before = fs.readFileSync(path.join(root, 'vite.config.ts'), 'utf-8');

    const actions = await runInit(root, { install: false, dryRun: true, log: silent });

    expect(actions.length).toBeGreaterThan(0);
    expect(exists('blueprint.config.mjs')).toBe(false);
    expect(exists('eslint.config.mjs')).toBe(false);
    expect(read('vite.config.ts')).toBe(before); // surgery planned, not applied
  });
});

// ─── Tier 2: read-only commands + the agent launch wiring, on real fixtures ───

describe('e2e · survey and deps on a real repo (Tier 2)', () => {
  it('surveys the import matrix and answers blast radius', async () => {
    useFixture('brownfield');

    // The fixture's tsconfig is JSONC (comments) so alias detection misses —
    // exactly why `--alias` exists; pass it as a user/agent would.
    const { runSurvey } = await import('../survey');
    const survey = runSurvey(root, { alias: '@', log: silent });

    // The planted edges show up in the matrix.
    expect(survey.edges.some((e) => e.from === 'features' && e.to === 'services')).toBe(true);
    expect(survey.packageUsage).toContainEqual({ package: 'axios', folders: ['services'] });

    fs.writeFileSync(path.join(root, 'blueprint.config.mjs'), BROWNFIELD_CONFIG);

    const { runDeps } = await import('../inspect');
    const { modules } = await runDeps(root, { target: 'services', log: silent });

    // Flat layout → module keys are layer names. services is imported by
    // features (feed) and utils (fmt, the cycle) — blast radius sees both.
    expect(modules[0].importedBy).toEqual(expect.arrayContaining(['features', 'utils']));
  });
});

describe('e2e · --agent launches after the playbook lands (Tier 2)', () => {
  it('writes every artifact before spawning, and spawns in the repo root', async () => {
    useFixture('brownfield');
    const calls: { bin: string; cwd: string; playbookExisted: boolean }[] = [];

    await runInit(root, {
      install: false,
      agent: 'claude',
      spawn: (bin, _args, cwd) => {
        calls.push({ bin, cwd, playbookExisted: exists('blueprint-authoring.md') });

        return { status: 0 };
      },
      log: silent,
    });

    expect(calls).toHaveLength(1);
    expect(calls[0].bin).toBe('claude');
    expect(calls[0].cwd).toBe(root);
    expect(calls[0].playbookExisted).toBe(true); // artifacts land BEFORE the spawn
  });
});

describe('e2e · greenfield emits the CI gate (Tier 2)', () => {
  it('writes a GitHub workflow that runs blueprint inspect', async () => {
    useFixture('vite-react-ts');

    await runInit(root, { install: false, log: silent });

    const ci = read('.github/workflows/blueprint-ci.yml');

    expect(ci).toContain('blueprint inspect');
  });
});

// ─── Tier 3: workspace + flag paths (unit-covered; pinned here on real shapes) ───

describe('e2e · yarn workspace package (Tier 3)', () => {
  it('detects yarn from the workspace root', async () => {
    useFixture('yarn-workspace');
    const commands: string[] = [];

    await runInit(path.join(root, 'packages', 'ui'), {
      log: silent,
      exec: (command) => {
        commands.push(command);
      },
    });

    expect(commands.every((command) => command.startsWith('yarn add -D'))).toBe(true);
  });
});

describe('e2e · --no-install surfaces the exact command (Tier 3)', () => {
  it('downgrades the brownfield install to an instruct with the command', async () => {
    useFixture('brownfield');

    const actions = await runInit(root, { install: false, log: silent });

    const skipped = actions.find(
      (action) => action.kind === 'instruct' && action.note.includes('Install skipped'),
    );

    expect(skipped?.note).toContain('npm install -D @kekkai/blueprint');
  });
});
